/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// EarlyAccessFeatureAPIService EarlyAccessFeatureAPI service
type EarlyAccessFeatureAPIService service

type ApiEarlyAccessFeatureCreateRequest struct {
	ctx context.Context
	ApiService *EarlyAccessFeatureAPIService
	projectId string
	earlyAccessFeatureSerializerCreateOnly *EarlyAccessFeatureSerializerCreateOnly
}

func (r ApiEarlyAccessFeatureCreateRequest) EarlyAccessFeatureSerializerCreateOnly(earlyAccessFeatureSerializerCreateOnly EarlyAccessFeatureSerializerCreateOnly) ApiEarlyAccessFeatureCreateRequest {
	r.earlyAccessFeatureSerializerCreateOnly = &earlyAccessFeatureSerializerCreateOnly
	return r
}

func (r ApiEarlyAccessFeatureCreateRequest) Execute() (*EarlyAccessFeatureSerializerCreateOnly, *http.Response, error) {
	return r.ApiService.EarlyAccessFeatureCreateExecute(r)
}

/*
EarlyAccessFeatureCreate Method for EarlyAccessFeatureCreate

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param projectId Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/.
 @return ApiEarlyAccessFeatureCreateRequest
*/
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureCreate(ctx context.Context, projectId string) ApiEarlyAccessFeatureCreateRequest {
	return ApiEarlyAccessFeatureCreateRequest{
		ApiService: a,
		ctx: ctx,
		projectId: projectId,
	}
}

// Execute executes the request
//  @return EarlyAccessFeatureSerializerCreateOnly
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureCreateExecute(r ApiEarlyAccessFeatureCreateRequest) (*EarlyAccessFeatureSerializerCreateOnly, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EarlyAccessFeatureSerializerCreateOnly
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EarlyAccessFeatureAPIService.EarlyAccessFeatureCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/projects/{project_id}/early_access_feature/"
	localVarPath = strings.Replace(localVarPath, "{"+"project_id"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.earlyAccessFeatureSerializerCreateOnly == nil {
		return localVarReturnValue, nil, reportError("earlyAccessFeatureSerializerCreateOnly is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.earlyAccessFeatureSerializerCreateOnly
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEarlyAccessFeatureDestroyRequest struct {
	ctx context.Context
	ApiService *EarlyAccessFeatureAPIService
	id string
	projectId string
}

func (r ApiEarlyAccessFeatureDestroyRequest) Execute() (*http.Response, error) {
	return r.ApiService.EarlyAccessFeatureDestroyExecute(r)
}

/*
EarlyAccessFeatureDestroy Method for EarlyAccessFeatureDestroy

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id A UUID string identifying this early access feature.
 @param projectId Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/.
 @return ApiEarlyAccessFeatureDestroyRequest
*/
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureDestroy(ctx context.Context, id string, projectId string) ApiEarlyAccessFeatureDestroyRequest {
	return ApiEarlyAccessFeatureDestroyRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		projectId: projectId,
	}
}

// Execute executes the request
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureDestroyExecute(r ApiEarlyAccessFeatureDestroyRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EarlyAccessFeatureAPIService.EarlyAccessFeatureDestroy")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/projects/{project_id}/early_access_feature/{id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"project_id"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiEarlyAccessFeatureListRequest struct {
	ctx context.Context
	ApiService *EarlyAccessFeatureAPIService
	projectId string
	limit *int32
	offset *int32
}

// Number of results to return per page.
func (r ApiEarlyAccessFeatureListRequest) Limit(limit int32) ApiEarlyAccessFeatureListRequest {
	r.limit = &limit
	return r
}

// The initial index from which to return the results.
func (r ApiEarlyAccessFeatureListRequest) Offset(offset int32) ApiEarlyAccessFeatureListRequest {
	r.offset = &offset
	return r
}

func (r ApiEarlyAccessFeatureListRequest) Execute() (*PaginatedEarlyAccessFeatureList, *http.Response, error) {
	return r.ApiService.EarlyAccessFeatureListExecute(r)
}

/*
EarlyAccessFeatureList Method for EarlyAccessFeatureList

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param projectId Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/.
 @return ApiEarlyAccessFeatureListRequest
*/
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureList(ctx context.Context, projectId string) ApiEarlyAccessFeatureListRequest {
	return ApiEarlyAccessFeatureListRequest{
		ApiService: a,
		ctx: ctx,
		projectId: projectId,
	}
}

// Execute executes the request
//  @return PaginatedEarlyAccessFeatureList
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureListExecute(r ApiEarlyAccessFeatureListRequest) (*PaginatedEarlyAccessFeatureList, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PaginatedEarlyAccessFeatureList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EarlyAccessFeatureAPIService.EarlyAccessFeatureList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/projects/{project_id}/early_access_feature/"
	localVarPath = strings.Replace(localVarPath, "{"+"project_id"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEarlyAccessFeaturePartialUpdateRequest struct {
	ctx context.Context
	ApiService *EarlyAccessFeatureAPIService
	id string
	projectId string
	patchedEarlyAccessFeature *PatchedEarlyAccessFeature
}

func (r ApiEarlyAccessFeaturePartialUpdateRequest) PatchedEarlyAccessFeature(patchedEarlyAccessFeature PatchedEarlyAccessFeature) ApiEarlyAccessFeaturePartialUpdateRequest {
	r.patchedEarlyAccessFeature = &patchedEarlyAccessFeature
	return r
}

func (r ApiEarlyAccessFeaturePartialUpdateRequest) Execute() (*EarlyAccessFeature, *http.Response, error) {
	return r.ApiService.EarlyAccessFeaturePartialUpdateExecute(r)
}

/*
EarlyAccessFeaturePartialUpdate Method for EarlyAccessFeaturePartialUpdate

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id A UUID string identifying this early access feature.
 @param projectId Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/.
 @return ApiEarlyAccessFeaturePartialUpdateRequest
*/
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeaturePartialUpdate(ctx context.Context, id string, projectId string) ApiEarlyAccessFeaturePartialUpdateRequest {
	return ApiEarlyAccessFeaturePartialUpdateRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		projectId: projectId,
	}
}

// Execute executes the request
//  @return EarlyAccessFeature
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeaturePartialUpdateExecute(r ApiEarlyAccessFeaturePartialUpdateRequest) (*EarlyAccessFeature, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EarlyAccessFeature
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EarlyAccessFeatureAPIService.EarlyAccessFeaturePartialUpdate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/projects/{project_id}/early_access_feature/{id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"project_id"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.patchedEarlyAccessFeature
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEarlyAccessFeatureRetrieveRequest struct {
	ctx context.Context
	ApiService *EarlyAccessFeatureAPIService
	id string
	projectId string
}

func (r ApiEarlyAccessFeatureRetrieveRequest) Execute() (*EarlyAccessFeature, *http.Response, error) {
	return r.ApiService.EarlyAccessFeatureRetrieveExecute(r)
}

/*
EarlyAccessFeatureRetrieve Method for EarlyAccessFeatureRetrieve

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id A UUID string identifying this early access feature.
 @param projectId Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/.
 @return ApiEarlyAccessFeatureRetrieveRequest
*/
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureRetrieve(ctx context.Context, id string, projectId string) ApiEarlyAccessFeatureRetrieveRequest {
	return ApiEarlyAccessFeatureRetrieveRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		projectId: projectId,
	}
}

// Execute executes the request
//  @return EarlyAccessFeature
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureRetrieveExecute(r ApiEarlyAccessFeatureRetrieveRequest) (*EarlyAccessFeature, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EarlyAccessFeature
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EarlyAccessFeatureAPIService.EarlyAccessFeatureRetrieve")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/projects/{project_id}/early_access_feature/{id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"project_id"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEarlyAccessFeatureUpdateRequest struct {
	ctx context.Context
	ApiService *EarlyAccessFeatureAPIService
	id string
	projectId string
	earlyAccessFeature *EarlyAccessFeature
}

func (r ApiEarlyAccessFeatureUpdateRequest) EarlyAccessFeature(earlyAccessFeature EarlyAccessFeature) ApiEarlyAccessFeatureUpdateRequest {
	r.earlyAccessFeature = &earlyAccessFeature
	return r
}

func (r ApiEarlyAccessFeatureUpdateRequest) Execute() (*EarlyAccessFeature, *http.Response, error) {
	return r.ApiService.EarlyAccessFeatureUpdateExecute(r)
}

/*
EarlyAccessFeatureUpdate Method for EarlyAccessFeatureUpdate

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id A UUID string identifying this early access feature.
 @param projectId Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/.
 @return ApiEarlyAccessFeatureUpdateRequest
*/
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureUpdate(ctx context.Context, id string, projectId string) ApiEarlyAccessFeatureUpdateRequest {
	return ApiEarlyAccessFeatureUpdateRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		projectId: projectId,
	}
}

// Execute executes the request
//  @return EarlyAccessFeature
func (a *EarlyAccessFeatureAPIService) EarlyAccessFeatureUpdateExecute(r ApiEarlyAccessFeatureUpdateRequest) (*EarlyAccessFeature, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EarlyAccessFeature
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EarlyAccessFeatureAPIService.EarlyAccessFeatureUpdate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/projects/{project_id}/early_access_feature/{id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"project_id"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.earlyAccessFeature == nil {
		return localVarReturnValue, nil, reportError("earlyAccessFeature is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.earlyAccessFeature
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
