/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EndpointLastExecutionTimesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointLastExecutionTimesRequest{}

// EndpointLastExecutionTimesRequest struct for EndpointLastExecutionTimesRequest
type EndpointLastExecutionTimesRequest struct {
	Names []string `json:"names"`
}

type _EndpointLastExecutionTimesRequest EndpointLastExecutionTimesRequest

// NewEndpointLastExecutionTimesRequest instantiates a new EndpointLastExecutionTimesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointLastExecutionTimesRequest(names []string) *EndpointLastExecutionTimesRequest {
	this := EndpointLastExecutionTimesRequest{}
	this.Names = names
	return &this
}

// NewEndpointLastExecutionTimesRequestWithDefaults instantiates a new EndpointLastExecutionTimesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointLastExecutionTimesRequestWithDefaults() *EndpointLastExecutionTimesRequest {
	this := EndpointLastExecutionTimesRequest{}
	return &this
}

// GetNames returns the Names field value
func (o *EndpointLastExecutionTimesRequest) GetNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Names
}

// GetNamesOk returns a tuple with the Names field value
// and a boolean to check if the value has been set.
func (o *EndpointLastExecutionTimesRequest) GetNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Names, true
}

// SetNames sets field value
func (o *EndpointLastExecutionTimesRequest) SetNames(v []string) {
	o.Names = v
}

func (o EndpointLastExecutionTimesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointLastExecutionTimesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["names"] = o.Names
	return toSerialize, nil
}

func (o *EndpointLastExecutionTimesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"names",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointLastExecutionTimesRequest := _EndpointLastExecutionTimesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointLastExecutionTimesRequest)

	if err != nil {
		return err
	}

	*o = EndpointLastExecutionTimesRequest(varEndpointLastExecutionTimesRequest)

	return err
}

type NullableEndpointLastExecutionTimesRequest struct {
	value *EndpointLastExecutionTimesRequest
	isSet bool
}

func (v NullableEndpointLastExecutionTimesRequest) Get() *EndpointLastExecutionTimesRequest {
	return v.value
}

func (v *NullableEndpointLastExecutionTimesRequest) Set(val *EndpointLastExecutionTimesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointLastExecutionTimesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointLastExecutionTimesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointLastExecutionTimesRequest(val *EndpointLastExecutionTimesRequest) *NullableEndpointLastExecutionTimesRequest {
	return &NullableEndpointLastExecutionTimesRequest{value: val, isSet: true}
}

func (v NullableEndpointLastExecutionTimesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointLastExecutionTimesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


