/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FileSystem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileSystem{}

// FileSystem struct for FileSystem
type FileSystem struct {
	Id string `json:"id"`
	Path string `json:"path"`
	Depth NullableInt32 `json:"depth"`
	Type *string `json:"type,omitempty"`
	Ref NullableString `json:"ref,omitempty"`
	Href NullableString `json:"href,omitempty"`
	Meta interface{} `json:"meta,omitempty"`
	Shortcut NullableBool `json:"shortcut,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	LastViewedAt NullableTime `json:"last_viewed_at"`
}

type _FileSystem FileSystem

// NewFileSystem instantiates a new FileSystem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileSystem(id string, path string, depth NullableInt32, createdAt time.Time, lastViewedAt NullableTime) *FileSystem {
	this := FileSystem{}
	this.Id = id
	this.Path = path
	this.Depth = depth
	this.CreatedAt = createdAt
	this.LastViewedAt = lastViewedAt
	return &this
}

// NewFileSystemWithDefaults instantiates a new FileSystem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileSystemWithDefaults() *FileSystem {
	this := FileSystem{}
	return &this
}

// GetId returns the Id field value
func (o *FileSystem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FileSystem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FileSystem) SetId(v string) {
	o.Id = v
}

// GetPath returns the Path field value
func (o *FileSystem) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *FileSystem) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *FileSystem) SetPath(v string) {
	o.Path = v
}

// GetDepth returns the Depth field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *FileSystem) GetDepth() int32 {
	if o == nil || o.Depth.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Depth.Get()
}

// GetDepthOk returns a tuple with the Depth field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileSystem) GetDepthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Depth.Get(), o.Depth.IsSet()
}

// SetDepth sets field value
func (o *FileSystem) SetDepth(v int32) {
	o.Depth.Set(&v)
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FileSystem) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSystem) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FileSystem) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FileSystem) SetType(v string) {
	o.Type = &v
}

// GetRef returns the Ref field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileSystem) GetRef() string {
	if o == nil || IsNil(o.Ref.Get()) {
		var ret string
		return ret
	}
	return *o.Ref.Get()
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileSystem) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ref.Get(), o.Ref.IsSet()
}

// HasRef returns a boolean if a field has been set.
func (o *FileSystem) HasRef() bool {
	if o != nil && o.Ref.IsSet() {
		return true
	}

	return false
}

// SetRef gets a reference to the given NullableString and assigns it to the Ref field.
func (o *FileSystem) SetRef(v string) {
	o.Ref.Set(&v)
}
// SetRefNil sets the value for Ref to be an explicit nil
func (o *FileSystem) SetRefNil() {
	o.Ref.Set(nil)
}

// UnsetRef ensures that no value is present for Ref, not even an explicit nil
func (o *FileSystem) UnsetRef() {
	o.Ref.Unset()
}

// GetHref returns the Href field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileSystem) GetHref() string {
	if o == nil || IsNil(o.Href.Get()) {
		var ret string
		return ret
	}
	return *o.Href.Get()
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileSystem) GetHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Href.Get(), o.Href.IsSet()
}

// HasHref returns a boolean if a field has been set.
func (o *FileSystem) HasHref() bool {
	if o != nil && o.Href.IsSet() {
		return true
	}

	return false
}

// SetHref gets a reference to the given NullableString and assigns it to the Href field.
func (o *FileSystem) SetHref(v string) {
	o.Href.Set(&v)
}
// SetHrefNil sets the value for Href to be an explicit nil
func (o *FileSystem) SetHrefNil() {
	o.Href.Set(nil)
}

// UnsetHref ensures that no value is present for Href, not even an explicit nil
func (o *FileSystem) UnsetHref() {
	o.Href.Unset()
}

// GetMeta returns the Meta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileSystem) GetMeta() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileSystem) GetMetaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return &o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *FileSystem) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given interface{} and assigns it to the Meta field.
func (o *FileSystem) SetMeta(v interface{}) {
	o.Meta = v
}

// GetShortcut returns the Shortcut field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileSystem) GetShortcut() bool {
	if o == nil || IsNil(o.Shortcut.Get()) {
		var ret bool
		return ret
	}
	return *o.Shortcut.Get()
}

// GetShortcutOk returns a tuple with the Shortcut field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileSystem) GetShortcutOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Shortcut.Get(), o.Shortcut.IsSet()
}

// HasShortcut returns a boolean if a field has been set.
func (o *FileSystem) HasShortcut() bool {
	if o != nil && o.Shortcut.IsSet() {
		return true
	}

	return false
}

// SetShortcut gets a reference to the given NullableBool and assigns it to the Shortcut field.
func (o *FileSystem) SetShortcut(v bool) {
	o.Shortcut.Set(&v)
}
// SetShortcutNil sets the value for Shortcut to be an explicit nil
func (o *FileSystem) SetShortcutNil() {
	o.Shortcut.Set(nil)
}

// UnsetShortcut ensures that no value is present for Shortcut, not even an explicit nil
func (o *FileSystem) UnsetShortcut() {
	o.Shortcut.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *FileSystem) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *FileSystem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *FileSystem) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetLastViewedAt returns the LastViewedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *FileSystem) GetLastViewedAt() time.Time {
	if o == nil || o.LastViewedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastViewedAt.Get()
}

// GetLastViewedAtOk returns a tuple with the LastViewedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileSystem) GetLastViewedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastViewedAt.Get(), o.LastViewedAt.IsSet()
}

// SetLastViewedAt sets field value
func (o *FileSystem) SetLastViewedAt(v time.Time) {
	o.LastViewedAt.Set(&v)
}

func (o FileSystem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileSystem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["path"] = o.Path
	toSerialize["depth"] = o.Depth.Get()
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Ref.IsSet() {
		toSerialize["ref"] = o.Ref.Get()
	}
	if o.Href.IsSet() {
		toSerialize["href"] = o.Href.Get()
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Shortcut.IsSet() {
		toSerialize["shortcut"] = o.Shortcut.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["last_viewed_at"] = o.LastViewedAt.Get()
	return toSerialize, nil
}

func (o *FileSystem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"path",
		"depth",
		"created_at",
		"last_viewed_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileSystem := _FileSystem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFileSystem)

	if err != nil {
		return err
	}

	*o = FileSystem(varFileSystem)

	return err
}

type NullableFileSystem struct {
	value *FileSystem
	isSet bool
}

func (v NullableFileSystem) Get() *FileSystem {
	return v.value
}

func (v *NullableFileSystem) Set(val *FileSystem) {
	v.value = val
	v.isSet = true
}

func (v NullableFileSystem) IsSet() bool {
	return v.isSet
}

func (v *NullableFileSystem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileSystem(val *FileSystem) *NullableFileSystem {
	return &NullableFileSystem{value: val, isSet: true}
}

func (v NullableFileSystem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileSystem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


