/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecordingPropertyFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordingPropertyFilter{}

// RecordingPropertyFilter struct for RecordingPropertyFilter
type RecordingPropertyFilter struct {
	Key Key1 `json:"key"`
	Label NullableString `json:"label,omitempty"`
	Operator PropertyOperator `json:"operator"`
	Type *string `json:"type,omitempty"`
	Value NullableValue2 `json:"value,omitempty"`
}

type _RecordingPropertyFilter RecordingPropertyFilter

// NewRecordingPropertyFilter instantiates a new RecordingPropertyFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordingPropertyFilter(key Key1, operator PropertyOperator) *RecordingPropertyFilter {
	this := RecordingPropertyFilter{}
	this.Key = key
	this.Operator = operator
	var type_ string = "recording"
	this.Type = &type_
	var value Value2 = null
	this.Value = *NewNullableValue2(&value)
	return &this
}

// NewRecordingPropertyFilterWithDefaults instantiates a new RecordingPropertyFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordingPropertyFilterWithDefaults() *RecordingPropertyFilter {
	this := RecordingPropertyFilter{}
	var type_ string = "recording"
	this.Type = &type_
	var value Value2 = null
	this.Value = *NewNullableValue2(&value)
	return &this
}

// GetKey returns the Key field value
func (o *RecordingPropertyFilter) GetKey() Key1 {
	if o == nil {
		var ret Key1
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *RecordingPropertyFilter) GetKeyOk() (*Key1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *RecordingPropertyFilter) SetKey(v Key1) {
	o.Key = v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingPropertyFilter) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingPropertyFilter) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *RecordingPropertyFilter) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *RecordingPropertyFilter) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *RecordingPropertyFilter) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *RecordingPropertyFilter) UnsetLabel() {
	o.Label.Unset()
}

// GetOperator returns the Operator field value
func (o *RecordingPropertyFilter) GetOperator() PropertyOperator {
	if o == nil {
		var ret PropertyOperator
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *RecordingPropertyFilter) GetOperatorOk() (*PropertyOperator, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *RecordingPropertyFilter) SetOperator(v PropertyOperator) {
	o.Operator = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RecordingPropertyFilter) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordingPropertyFilter) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RecordingPropertyFilter) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RecordingPropertyFilter) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingPropertyFilter) GetValue() Value2 {
	if o == nil || IsNil(o.Value.Get()) {
		var ret Value2
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingPropertyFilter) GetValueOk() (*Value2, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *RecordingPropertyFilter) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableValue2 and assigns it to the Value field.
func (o *RecordingPropertyFilter) SetValue(v Value2) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *RecordingPropertyFilter) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *RecordingPropertyFilter) UnsetValue() {
	o.Value.Unset()
}

func (o RecordingPropertyFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordingPropertyFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	toSerialize["operator"] = o.Operator
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	return toSerialize, nil
}

func (o *RecordingPropertyFilter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"operator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordingPropertyFilter := _RecordingPropertyFilter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecordingPropertyFilter)

	if err != nil {
		return err
	}

	*o = RecordingPropertyFilter(varRecordingPropertyFilter)

	return err
}

type NullableRecordingPropertyFilter struct {
	value *RecordingPropertyFilter
	isSet bool
}

func (v NullableRecordingPropertyFilter) Get() *RecordingPropertyFilter {
	return v.value
}

func (v *NullableRecordingPropertyFilter) Set(val *RecordingPropertyFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordingPropertyFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordingPropertyFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordingPropertyFilter(val *RecordingPropertyFilter) *NullableRecordingPropertyFilter {
	return &NullableRecordingPropertyFilter{value: val, isSet: true}
}

func (v NullableRecordingPropertyFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordingPropertyFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


