/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Response2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response2{}

// Response2 struct for Response2
type Response2 struct {
	Columns []interface{} `json:"columns"`
	// Query error. Returned only if 'explain' or `modifiers.debug` is true. Throws an error otherwise.
	Error NullableString `json:"error,omitempty"`
	HasMore NullableBool `json:"hasMore,omitempty"`
	// Generated HogQL query.
	Hogql string `json:"hogql"`
	Kind *string `json:"kind,omitempty"`
	Limit int32 `json:"limit"`
	Modifiers *HogQLQueryModifiers `json:"modifiers,omitempty"`
	Offset int32 `json:"offset"`
	QueryStatus *QueryStatus `json:"query_status,omitempty"`
	ResolvedDateRange *ResolvedDateRangeResponse `json:"resolved_date_range,omitempty"`
	Results [][]interface{} `json:"results"`
	// Measured timings for different parts of the query generation process
	Timings []QueryTiming `json:"timings,omitempty"`
	Types []string `json:"types"`
}

type _Response2 Response2

// NewResponse2 instantiates a new Response2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse2(columns []interface{}, hogql string, limit int32, offset int32, results [][]interface{}, types []string) *Response2 {
	this := Response2{}
	this.Columns = columns
	this.Hogql = hogql
	var kind string = "GroupsQuery"
	this.Kind = &kind
	this.Limit = limit
	this.Offset = offset
	this.Results = results
	this.Types = types
	return &this
}

// NewResponse2WithDefaults instantiates a new Response2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse2WithDefaults() *Response2 {
	this := Response2{}
	var kind string = "GroupsQuery"
	this.Kind = &kind
	return &this
}

// GetColumns returns the Columns field value
func (o *Response2) GetColumns() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value
// and a boolean to check if the value has been set.
func (o *Response2) GetColumnsOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Columns, true
}

// SetColumns sets field value
func (o *Response2) SetColumns(v []interface{}) {
	o.Columns = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Response2) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Response2) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *Response2) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *Response2) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *Response2) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *Response2) UnsetError() {
	o.Error.Unset()
}

// GetHasMore returns the HasMore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Response2) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore.Get()) {
		var ret bool
		return ret
	}
	return *o.HasMore.Get()
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Response2) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.HasMore.Get(), o.HasMore.IsSet()
}

// HasHasMore returns a boolean if a field has been set.
func (o *Response2) HasHasMore() bool {
	if o != nil && o.HasMore.IsSet() {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given NullableBool and assigns it to the HasMore field.
func (o *Response2) SetHasMore(v bool) {
	o.HasMore.Set(&v)
}
// SetHasMoreNil sets the value for HasMore to be an explicit nil
func (o *Response2) SetHasMoreNil() {
	o.HasMore.Set(nil)
}

// UnsetHasMore ensures that no value is present for HasMore, not even an explicit nil
func (o *Response2) UnsetHasMore() {
	o.HasMore.Unset()
}

// GetHogql returns the Hogql field value
func (o *Response2) GetHogql() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hogql
}

// GetHogqlOk returns a tuple with the Hogql field value
// and a boolean to check if the value has been set.
func (o *Response2) GetHogqlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hogql, true
}

// SetHogql sets field value
func (o *Response2) SetHogql(v string) {
	o.Hogql = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Response2) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response2) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Response2) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *Response2) SetKind(v string) {
	o.Kind = &v
}

// GetLimit returns the Limit field value
func (o *Response2) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *Response2) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *Response2) SetLimit(v int32) {
	o.Limit = v
}

// GetModifiers returns the Modifiers field value if set, zero value otherwise.
func (o *Response2) GetModifiers() HogQLQueryModifiers {
	if o == nil || IsNil(o.Modifiers) {
		var ret HogQLQueryModifiers
		return ret
	}
	return *o.Modifiers
}

// GetModifiersOk returns a tuple with the Modifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response2) GetModifiersOk() (*HogQLQueryModifiers, bool) {
	if o == nil || IsNil(o.Modifiers) {
		return nil, false
	}
	return o.Modifiers, true
}

// HasModifiers returns a boolean if a field has been set.
func (o *Response2) HasModifiers() bool {
	if o != nil && !IsNil(o.Modifiers) {
		return true
	}

	return false
}

// SetModifiers gets a reference to the given HogQLQueryModifiers and assigns it to the Modifiers field.
func (o *Response2) SetModifiers(v HogQLQueryModifiers) {
	o.Modifiers = &v
}

// GetOffset returns the Offset field value
func (o *Response2) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *Response2) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *Response2) SetOffset(v int32) {
	o.Offset = v
}

// GetQueryStatus returns the QueryStatus field value if set, zero value otherwise.
func (o *Response2) GetQueryStatus() QueryStatus {
	if o == nil || IsNil(o.QueryStatus) {
		var ret QueryStatus
		return ret
	}
	return *o.QueryStatus
}

// GetQueryStatusOk returns a tuple with the QueryStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response2) GetQueryStatusOk() (*QueryStatus, bool) {
	if o == nil || IsNil(o.QueryStatus) {
		return nil, false
	}
	return o.QueryStatus, true
}

// HasQueryStatus returns a boolean if a field has been set.
func (o *Response2) HasQueryStatus() bool {
	if o != nil && !IsNil(o.QueryStatus) {
		return true
	}

	return false
}

// SetQueryStatus gets a reference to the given QueryStatus and assigns it to the QueryStatus field.
func (o *Response2) SetQueryStatus(v QueryStatus) {
	o.QueryStatus = &v
}

// GetResolvedDateRange returns the ResolvedDateRange field value if set, zero value otherwise.
func (o *Response2) GetResolvedDateRange() ResolvedDateRangeResponse {
	if o == nil || IsNil(o.ResolvedDateRange) {
		var ret ResolvedDateRangeResponse
		return ret
	}
	return *o.ResolvedDateRange
}

// GetResolvedDateRangeOk returns a tuple with the ResolvedDateRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response2) GetResolvedDateRangeOk() (*ResolvedDateRangeResponse, bool) {
	if o == nil || IsNil(o.ResolvedDateRange) {
		return nil, false
	}
	return o.ResolvedDateRange, true
}

// HasResolvedDateRange returns a boolean if a field has been set.
func (o *Response2) HasResolvedDateRange() bool {
	if o != nil && !IsNil(o.ResolvedDateRange) {
		return true
	}

	return false
}

// SetResolvedDateRange gets a reference to the given ResolvedDateRangeResponse and assigns it to the ResolvedDateRange field.
func (o *Response2) SetResolvedDateRange(v ResolvedDateRangeResponse) {
	o.ResolvedDateRange = &v
}

// GetResults returns the Results field value
func (o *Response2) GetResults() [][]interface{} {
	if o == nil {
		var ret [][]interface{}
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *Response2) GetResultsOk() ([][]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *Response2) SetResults(v [][]interface{}) {
	o.Results = v
}

// GetTimings returns the Timings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Response2) GetTimings() []QueryTiming {
	if o == nil {
		var ret []QueryTiming
		return ret
	}
	return o.Timings
}

// GetTimingsOk returns a tuple with the Timings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Response2) GetTimingsOk() ([]QueryTiming, bool) {
	if o == nil || IsNil(o.Timings) {
		return nil, false
	}
	return o.Timings, true
}

// HasTimings returns a boolean if a field has been set.
func (o *Response2) HasTimings() bool {
	if o != nil && !IsNil(o.Timings) {
		return true
	}

	return false
}

// SetTimings gets a reference to the given []QueryTiming and assigns it to the Timings field.
func (o *Response2) SetTimings(v []QueryTiming) {
	o.Timings = v
}

// GetTypes returns the Types field value
func (o *Response2) GetTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *Response2) GetTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Types, true
}

// SetTypes sets field value
func (o *Response2) SetTypes(v []string) {
	o.Types = v
}

func (o Response2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["columns"] = o.Columns
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.HasMore.IsSet() {
		toSerialize["hasMore"] = o.HasMore.Get()
	}
	toSerialize["hogql"] = o.Hogql
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	toSerialize["limit"] = o.Limit
	if !IsNil(o.Modifiers) {
		toSerialize["modifiers"] = o.Modifiers
	}
	toSerialize["offset"] = o.Offset
	if !IsNil(o.QueryStatus) {
		toSerialize["query_status"] = o.QueryStatus
	}
	if !IsNil(o.ResolvedDateRange) {
		toSerialize["resolved_date_range"] = o.ResolvedDateRange
	}
	toSerialize["results"] = o.Results
	if o.Timings != nil {
		toSerialize["timings"] = o.Timings
	}
	toSerialize["types"] = o.Types
	return toSerialize, nil
}

func (o *Response2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"columns",
		"hogql",
		"limit",
		"offset",
		"results",
		"types",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse2 := _Response2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse2)

	if err != nil {
		return err
	}

	*o = Response2(varResponse2)

	return err
}

type NullableResponse2 struct {
	value *Response2
	isSet bool
}

func (v NullableResponse2) Get() *Response2 {
	return v.value
}

func (v *NullableResponse2) Set(val *Response2) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse2) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse2(val *Response2) *NullableResponse2 {
	return &NullableResponse2{value: val, isSet: true}
}

func (v NullableResponse2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


