/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
)

// checks if the PersonsNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PersonsNode{}

// PersonsNode struct for PersonsNode
type PersonsNode struct {
	Cohort NullableInt32 `json:"cohort,omitempty"`
	DistinctId NullableString `json:"distinctId,omitempty"`
	// Fixed properties in the query, can't be edited in the interface (e.g. scoping down by person)
	FixedProperties []FixedpropertiesInner `json:"fixedProperties,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Limit NullableInt32 `json:"limit,omitempty"`
	Modifiers *HogQLQueryModifiers `json:"modifiers,omitempty"`
	Offset NullableInt32 `json:"offset,omitempty"`
	// Properties configurable in the interface
	Properties []FixedpropertiesInner `json:"properties,omitempty"`
	Response map[string]interface{} `json:"response,omitempty"`
	Search NullableString `json:"search,omitempty"`
	Tags *QueryLogTags `json:"tags,omitempty"`
	// version of the node, used for schema migrations
	Version NullableFloat32 `json:"version,omitempty"`
}

// NewPersonsNode instantiates a new PersonsNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPersonsNode() *PersonsNode {
	this := PersonsNode{}
	var kind string = "PersonsNode"
	this.Kind = &kind
	return &this
}

// NewPersonsNodeWithDefaults instantiates a new PersonsNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonsNodeWithDefaults() *PersonsNode {
	this := PersonsNode{}
	var kind string = "PersonsNode"
	this.Kind = &kind
	return &this
}

// GetCohort returns the Cohort field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonsNode) GetCohort() int32 {
	if o == nil || IsNil(o.Cohort.Get()) {
		var ret int32
		return ret
	}
	return *o.Cohort.Get()
}

// GetCohortOk returns a tuple with the Cohort field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonsNode) GetCohortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cohort.Get(), o.Cohort.IsSet()
}

// HasCohort returns a boolean if a field has been set.
func (o *PersonsNode) HasCohort() bool {
	if o != nil && o.Cohort.IsSet() {
		return true
	}

	return false
}

// SetCohort gets a reference to the given NullableInt32 and assigns it to the Cohort field.
func (o *PersonsNode) SetCohort(v int32) {
	o.Cohort.Set(&v)
}
// SetCohortNil sets the value for Cohort to be an explicit nil
func (o *PersonsNode) SetCohortNil() {
	o.Cohort.Set(nil)
}

// UnsetCohort ensures that no value is present for Cohort, not even an explicit nil
func (o *PersonsNode) UnsetCohort() {
	o.Cohort.Unset()
}

// GetDistinctId returns the DistinctId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonsNode) GetDistinctId() string {
	if o == nil || IsNil(o.DistinctId.Get()) {
		var ret string
		return ret
	}
	return *o.DistinctId.Get()
}

// GetDistinctIdOk returns a tuple with the DistinctId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonsNode) GetDistinctIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DistinctId.Get(), o.DistinctId.IsSet()
}

// HasDistinctId returns a boolean if a field has been set.
func (o *PersonsNode) HasDistinctId() bool {
	if o != nil && o.DistinctId.IsSet() {
		return true
	}

	return false
}

// SetDistinctId gets a reference to the given NullableString and assigns it to the DistinctId field.
func (o *PersonsNode) SetDistinctId(v string) {
	o.DistinctId.Set(&v)
}
// SetDistinctIdNil sets the value for DistinctId to be an explicit nil
func (o *PersonsNode) SetDistinctIdNil() {
	o.DistinctId.Set(nil)
}

// UnsetDistinctId ensures that no value is present for DistinctId, not even an explicit nil
func (o *PersonsNode) UnsetDistinctId() {
	o.DistinctId.Unset()
}

// GetFixedProperties returns the FixedProperties field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonsNode) GetFixedProperties() []FixedpropertiesInner {
	if o == nil {
		var ret []FixedpropertiesInner
		return ret
	}
	return o.FixedProperties
}

// GetFixedPropertiesOk returns a tuple with the FixedProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonsNode) GetFixedPropertiesOk() ([]FixedpropertiesInner, bool) {
	if o == nil || IsNil(o.FixedProperties) {
		return nil, false
	}
	return o.FixedProperties, true
}

// HasFixedProperties returns a boolean if a field has been set.
func (o *PersonsNode) HasFixedProperties() bool {
	if o != nil && !IsNil(o.FixedProperties) {
		return true
	}

	return false
}

// SetFixedProperties gets a reference to the given []FixedpropertiesInner and assigns it to the FixedProperties field.
func (o *PersonsNode) SetFixedProperties(v []FixedpropertiesInner) {
	o.FixedProperties = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *PersonsNode) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonsNode) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *PersonsNode) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *PersonsNode) SetKind(v string) {
	o.Kind = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonsNode) GetLimit() int32 {
	if o == nil || IsNil(o.Limit.Get()) {
		var ret int32
		return ret
	}
	return *o.Limit.Get()
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonsNode) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Limit.Get(), o.Limit.IsSet()
}

// HasLimit returns a boolean if a field has been set.
func (o *PersonsNode) HasLimit() bool {
	if o != nil && o.Limit.IsSet() {
		return true
	}

	return false
}

// SetLimit gets a reference to the given NullableInt32 and assigns it to the Limit field.
func (o *PersonsNode) SetLimit(v int32) {
	o.Limit.Set(&v)
}
// SetLimitNil sets the value for Limit to be an explicit nil
func (o *PersonsNode) SetLimitNil() {
	o.Limit.Set(nil)
}

// UnsetLimit ensures that no value is present for Limit, not even an explicit nil
func (o *PersonsNode) UnsetLimit() {
	o.Limit.Unset()
}

// GetModifiers returns the Modifiers field value if set, zero value otherwise.
func (o *PersonsNode) GetModifiers() HogQLQueryModifiers {
	if o == nil || IsNil(o.Modifiers) {
		var ret HogQLQueryModifiers
		return ret
	}
	return *o.Modifiers
}

// GetModifiersOk returns a tuple with the Modifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonsNode) GetModifiersOk() (*HogQLQueryModifiers, bool) {
	if o == nil || IsNil(o.Modifiers) {
		return nil, false
	}
	return o.Modifiers, true
}

// HasModifiers returns a boolean if a field has been set.
func (o *PersonsNode) HasModifiers() bool {
	if o != nil && !IsNil(o.Modifiers) {
		return true
	}

	return false
}

// SetModifiers gets a reference to the given HogQLQueryModifiers and assigns it to the Modifiers field.
func (o *PersonsNode) SetModifiers(v HogQLQueryModifiers) {
	o.Modifiers = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonsNode) GetOffset() int32 {
	if o == nil || IsNil(o.Offset.Get()) {
		var ret int32
		return ret
	}
	return *o.Offset.Get()
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonsNode) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Offset.Get(), o.Offset.IsSet()
}

// HasOffset returns a boolean if a field has been set.
func (o *PersonsNode) HasOffset() bool {
	if o != nil && o.Offset.IsSet() {
		return true
	}

	return false
}

// SetOffset gets a reference to the given NullableInt32 and assigns it to the Offset field.
func (o *PersonsNode) SetOffset(v int32) {
	o.Offset.Set(&v)
}
// SetOffsetNil sets the value for Offset to be an explicit nil
func (o *PersonsNode) SetOffsetNil() {
	o.Offset.Set(nil)
}

// UnsetOffset ensures that no value is present for Offset, not even an explicit nil
func (o *PersonsNode) UnsetOffset() {
	o.Offset.Unset()
}

// GetProperties returns the Properties field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonsNode) GetProperties() []FixedpropertiesInner {
	if o == nil {
		var ret []FixedpropertiesInner
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonsNode) GetPropertiesOk() ([]FixedpropertiesInner, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *PersonsNode) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given []FixedpropertiesInner and assigns it to the Properties field.
func (o *PersonsNode) SetProperties(v []FixedpropertiesInner) {
	o.Properties = v
}

// GetResponse returns the Response field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonsNode) GetResponse() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonsNode) GetResponseOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Response) {
		return map[string]interface{}{}, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *PersonsNode) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given map[string]interface{} and assigns it to the Response field.
func (o *PersonsNode) SetResponse(v map[string]interface{}) {
	o.Response = v
}

// GetSearch returns the Search field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonsNode) GetSearch() string {
	if o == nil || IsNil(o.Search.Get()) {
		var ret string
		return ret
	}
	return *o.Search.Get()
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonsNode) GetSearchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Search.Get(), o.Search.IsSet()
}

// HasSearch returns a boolean if a field has been set.
func (o *PersonsNode) HasSearch() bool {
	if o != nil && o.Search.IsSet() {
		return true
	}

	return false
}

// SetSearch gets a reference to the given NullableString and assigns it to the Search field.
func (o *PersonsNode) SetSearch(v string) {
	o.Search.Set(&v)
}
// SetSearchNil sets the value for Search to be an explicit nil
func (o *PersonsNode) SetSearchNil() {
	o.Search.Set(nil)
}

// UnsetSearch ensures that no value is present for Search, not even an explicit nil
func (o *PersonsNode) UnsetSearch() {
	o.Search.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PersonsNode) GetTags() QueryLogTags {
	if o == nil || IsNil(o.Tags) {
		var ret QueryLogTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonsNode) GetTagsOk() (*QueryLogTags, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PersonsNode) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given QueryLogTags and assigns it to the Tags field.
func (o *PersonsNode) SetTags(v QueryLogTags) {
	o.Tags = &v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonsNode) GetVersion() float32 {
	if o == nil || IsNil(o.Version.Get()) {
		var ret float32
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonsNode) GetVersionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *PersonsNode) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableFloat32 and assigns it to the Version field.
func (o *PersonsNode) SetVersion(v float32) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *PersonsNode) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *PersonsNode) UnsetVersion() {
	o.Version.Unset()
}

func (o PersonsNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PersonsNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Cohort.IsSet() {
		toSerialize["cohort"] = o.Cohort.Get()
	}
	if o.DistinctId.IsSet() {
		toSerialize["distinctId"] = o.DistinctId.Get()
	}
	if o.FixedProperties != nil {
		toSerialize["fixedProperties"] = o.FixedProperties
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if o.Limit.IsSet() {
		toSerialize["limit"] = o.Limit.Get()
	}
	if !IsNil(o.Modifiers) {
		toSerialize["modifiers"] = o.Modifiers
	}
	if o.Offset.IsSet() {
		toSerialize["offset"] = o.Offset.Get()
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	if o.Search.IsSet() {
		toSerialize["search"] = o.Search.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	return toSerialize, nil
}

type NullablePersonsNode struct {
	value *PersonsNode
	isSet bool
}

func (v NullablePersonsNode) Get() *PersonsNode {
	return v.value
}

func (v *NullablePersonsNode) Set(val *PersonsNode) {
	v.value = val
	v.isSet = true
}

func (v NullablePersonsNode) IsSet() bool {
	return v.isSet
}

func (v *NullablePersonsNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersonsNode(val *PersonsNode) *NullablePersonsNode {
	return &NullablePersonsNode{value: val, isSet: true}
}

func (v NullablePersonsNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersonsNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


