/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TracesQueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TracesQueryResponse{}

// TracesQueryResponse struct for TracesQueryResponse
type TracesQueryResponse struct {
	Columns []string `json:"columns,omitempty"`
	// Query error. Returned only if 'explain' or `modifiers.debug` is true. Throws an error otherwise.
	Error NullableString `json:"error,omitempty"`
	HasMore NullableBool `json:"hasMore,omitempty"`
	// Generated HogQL query.
	Hogql NullableString `json:"hogql,omitempty"`
	Limit NullableInt32 `json:"limit,omitempty"`
	Modifiers *HogQLQueryModifiers `json:"modifiers,omitempty"`
	Offset NullableInt32 `json:"offset,omitempty"`
	QueryStatus *QueryStatus `json:"query_status,omitempty"`
	ResolvedDateRange *ResolvedDateRangeResponse `json:"resolved_date_range,omitempty"`
	Results []LLMTrace `json:"results"`
	// Measured timings for different parts of the query generation process
	Timings []QueryTiming `json:"timings,omitempty"`
}

type _TracesQueryResponse TracesQueryResponse

// NewTracesQueryResponse instantiates a new TracesQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTracesQueryResponse(results []LLMTrace) *TracesQueryResponse {
	this := TracesQueryResponse{}
	this.Results = results
	return &this
}

// NewTracesQueryResponseWithDefaults instantiates a new TracesQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTracesQueryResponseWithDefaults() *TracesQueryResponse {
	this := TracesQueryResponse{}
	return &this
}

// GetColumns returns the Columns field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TracesQueryResponse) GetColumns() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesQueryResponse) GetColumnsOk() ([]string, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []string and assigns it to the Columns field.
func (o *TracesQueryResponse) SetColumns(v []string) {
	o.Columns = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TracesQueryResponse) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesQueryResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *TracesQueryResponse) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *TracesQueryResponse) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *TracesQueryResponse) UnsetError() {
	o.Error.Unset()
}

// GetHasMore returns the HasMore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TracesQueryResponse) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore.Get()) {
		var ret bool
		return ret
	}
	return *o.HasMore.Get()
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesQueryResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.HasMore.Get(), o.HasMore.IsSet()
}

// HasHasMore returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasHasMore() bool {
	if o != nil && o.HasMore.IsSet() {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given NullableBool and assigns it to the HasMore field.
func (o *TracesQueryResponse) SetHasMore(v bool) {
	o.HasMore.Set(&v)
}
// SetHasMoreNil sets the value for HasMore to be an explicit nil
func (o *TracesQueryResponse) SetHasMoreNil() {
	o.HasMore.Set(nil)
}

// UnsetHasMore ensures that no value is present for HasMore, not even an explicit nil
func (o *TracesQueryResponse) UnsetHasMore() {
	o.HasMore.Unset()
}

// GetHogql returns the Hogql field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TracesQueryResponse) GetHogql() string {
	if o == nil || IsNil(o.Hogql.Get()) {
		var ret string
		return ret
	}
	return *o.Hogql.Get()
}

// GetHogqlOk returns a tuple with the Hogql field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesQueryResponse) GetHogqlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hogql.Get(), o.Hogql.IsSet()
}

// HasHogql returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasHogql() bool {
	if o != nil && o.Hogql.IsSet() {
		return true
	}

	return false
}

// SetHogql gets a reference to the given NullableString and assigns it to the Hogql field.
func (o *TracesQueryResponse) SetHogql(v string) {
	o.Hogql.Set(&v)
}
// SetHogqlNil sets the value for Hogql to be an explicit nil
func (o *TracesQueryResponse) SetHogqlNil() {
	o.Hogql.Set(nil)
}

// UnsetHogql ensures that no value is present for Hogql, not even an explicit nil
func (o *TracesQueryResponse) UnsetHogql() {
	o.Hogql.Unset()
}

// GetLimit returns the Limit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TracesQueryResponse) GetLimit() int32 {
	if o == nil || IsNil(o.Limit.Get()) {
		var ret int32
		return ret
	}
	return *o.Limit.Get()
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesQueryResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Limit.Get(), o.Limit.IsSet()
}

// HasLimit returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasLimit() bool {
	if o != nil && o.Limit.IsSet() {
		return true
	}

	return false
}

// SetLimit gets a reference to the given NullableInt32 and assigns it to the Limit field.
func (o *TracesQueryResponse) SetLimit(v int32) {
	o.Limit.Set(&v)
}
// SetLimitNil sets the value for Limit to be an explicit nil
func (o *TracesQueryResponse) SetLimitNil() {
	o.Limit.Set(nil)
}

// UnsetLimit ensures that no value is present for Limit, not even an explicit nil
func (o *TracesQueryResponse) UnsetLimit() {
	o.Limit.Unset()
}

// GetModifiers returns the Modifiers field value if set, zero value otherwise.
func (o *TracesQueryResponse) GetModifiers() HogQLQueryModifiers {
	if o == nil || IsNil(o.Modifiers) {
		var ret HogQLQueryModifiers
		return ret
	}
	return *o.Modifiers
}

// GetModifiersOk returns a tuple with the Modifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TracesQueryResponse) GetModifiersOk() (*HogQLQueryModifiers, bool) {
	if o == nil || IsNil(o.Modifiers) {
		return nil, false
	}
	return o.Modifiers, true
}

// HasModifiers returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasModifiers() bool {
	if o != nil && !IsNil(o.Modifiers) {
		return true
	}

	return false
}

// SetModifiers gets a reference to the given HogQLQueryModifiers and assigns it to the Modifiers field.
func (o *TracesQueryResponse) SetModifiers(v HogQLQueryModifiers) {
	o.Modifiers = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TracesQueryResponse) GetOffset() int32 {
	if o == nil || IsNil(o.Offset.Get()) {
		var ret int32
		return ret
	}
	return *o.Offset.Get()
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesQueryResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Offset.Get(), o.Offset.IsSet()
}

// HasOffset returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasOffset() bool {
	if o != nil && o.Offset.IsSet() {
		return true
	}

	return false
}

// SetOffset gets a reference to the given NullableInt32 and assigns it to the Offset field.
func (o *TracesQueryResponse) SetOffset(v int32) {
	o.Offset.Set(&v)
}
// SetOffsetNil sets the value for Offset to be an explicit nil
func (o *TracesQueryResponse) SetOffsetNil() {
	o.Offset.Set(nil)
}

// UnsetOffset ensures that no value is present for Offset, not even an explicit nil
func (o *TracesQueryResponse) UnsetOffset() {
	o.Offset.Unset()
}

// GetQueryStatus returns the QueryStatus field value if set, zero value otherwise.
func (o *TracesQueryResponse) GetQueryStatus() QueryStatus {
	if o == nil || IsNil(o.QueryStatus) {
		var ret QueryStatus
		return ret
	}
	return *o.QueryStatus
}

// GetQueryStatusOk returns a tuple with the QueryStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TracesQueryResponse) GetQueryStatusOk() (*QueryStatus, bool) {
	if o == nil || IsNil(o.QueryStatus) {
		return nil, false
	}
	return o.QueryStatus, true
}

// HasQueryStatus returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasQueryStatus() bool {
	if o != nil && !IsNil(o.QueryStatus) {
		return true
	}

	return false
}

// SetQueryStatus gets a reference to the given QueryStatus and assigns it to the QueryStatus field.
func (o *TracesQueryResponse) SetQueryStatus(v QueryStatus) {
	o.QueryStatus = &v
}

// GetResolvedDateRange returns the ResolvedDateRange field value if set, zero value otherwise.
func (o *TracesQueryResponse) GetResolvedDateRange() ResolvedDateRangeResponse {
	if o == nil || IsNil(o.ResolvedDateRange) {
		var ret ResolvedDateRangeResponse
		return ret
	}
	return *o.ResolvedDateRange
}

// GetResolvedDateRangeOk returns a tuple with the ResolvedDateRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TracesQueryResponse) GetResolvedDateRangeOk() (*ResolvedDateRangeResponse, bool) {
	if o == nil || IsNil(o.ResolvedDateRange) {
		return nil, false
	}
	return o.ResolvedDateRange, true
}

// HasResolvedDateRange returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasResolvedDateRange() bool {
	if o != nil && !IsNil(o.ResolvedDateRange) {
		return true
	}

	return false
}

// SetResolvedDateRange gets a reference to the given ResolvedDateRangeResponse and assigns it to the ResolvedDateRange field.
func (o *TracesQueryResponse) SetResolvedDateRange(v ResolvedDateRangeResponse) {
	o.ResolvedDateRange = &v
}

// GetResults returns the Results field value
func (o *TracesQueryResponse) GetResults() []LLMTrace {
	if o == nil {
		var ret []LLMTrace
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *TracesQueryResponse) GetResultsOk() ([]LLMTrace, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *TracesQueryResponse) SetResults(v []LLMTrace) {
	o.Results = v
}

// GetTimings returns the Timings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TracesQueryResponse) GetTimings() []QueryTiming {
	if o == nil {
		var ret []QueryTiming
		return ret
	}
	return o.Timings
}

// GetTimingsOk returns a tuple with the Timings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesQueryResponse) GetTimingsOk() ([]QueryTiming, bool) {
	if o == nil || IsNil(o.Timings) {
		return nil, false
	}
	return o.Timings, true
}

// HasTimings returns a boolean if a field has been set.
func (o *TracesQueryResponse) HasTimings() bool {
	if o != nil && !IsNil(o.Timings) {
		return true
	}

	return false
}

// SetTimings gets a reference to the given []QueryTiming and assigns it to the Timings field.
func (o *TracesQueryResponse) SetTimings(v []QueryTiming) {
	o.Timings = v
}

func (o TracesQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TracesQueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Columns != nil {
		toSerialize["columns"] = o.Columns
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.HasMore.IsSet() {
		toSerialize["hasMore"] = o.HasMore.Get()
	}
	if o.Hogql.IsSet() {
		toSerialize["hogql"] = o.Hogql.Get()
	}
	if o.Limit.IsSet() {
		toSerialize["limit"] = o.Limit.Get()
	}
	if !IsNil(o.Modifiers) {
		toSerialize["modifiers"] = o.Modifiers
	}
	if o.Offset.IsSet() {
		toSerialize["offset"] = o.Offset.Get()
	}
	if !IsNil(o.QueryStatus) {
		toSerialize["query_status"] = o.QueryStatus
	}
	if !IsNil(o.ResolvedDateRange) {
		toSerialize["resolved_date_range"] = o.ResolvedDateRange
	}
	toSerialize["results"] = o.Results
	if o.Timings != nil {
		toSerialize["timings"] = o.Timings
	}
	return toSerialize, nil
}

func (o *TracesQueryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTracesQueryResponse := _TracesQueryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTracesQueryResponse)

	if err != nil {
		return err
	}

	*o = TracesQueryResponse(varTracesQueryResponse)

	return err
}

type NullableTracesQueryResponse struct {
	value *TracesQueryResponse
	isSet bool
}

func (v NullableTracesQueryResponse) Get() *TracesQueryResponse {
	return v.value
}

func (v *NullableTracesQueryResponse) Set(val *TracesQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTracesQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTracesQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTracesQueryResponse(val *TracesQueryResponse) *NullableTracesQueryResponse {
	return &NullableTracesQueryResponse{value: val, isSet: true}
}

func (v NullableTracesQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTracesQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


