/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"fmt"
)

// KindEnum * `slack` - Slack * `salesforce` - Salesforce * `hubspot` - Hubspot * `google-pubsub` - Google Pubsub * `google-cloud-storage` - Google Cloud Storage * `google-ads` - Google Ads * `google-sheets` - Google Sheets * `snapchat` - Snapchat * `linkedin-ads` - Linkedin Ads * `reddit-ads` - Reddit Ads * `tiktok-ads` - Tiktok Ads * `intercom` - Intercom * `email` - Email * `linear` - Linear * `github` - Github * `gitlab` - Gitlab * `meta-ads` - Meta Ads * `twilio` - Twilio * `clickup` - Clickup * `vercel` - Vercel * `databricks` - Databricks
type KindEnum string

// List of KindEnum
const (
	SLACK KindEnum = "slack"
	SALESFORCE KindEnum = "salesforce"
	HUBSPOT KindEnum = "hubspot"
	GOOGLE_PUBSUB KindEnum = "google-pubsub"
	GOOGLE_CLOUD_STORAGE KindEnum = "google-cloud-storage"
	GOOGLE_ADS KindEnum = "google-ads"
	GOOGLE_SHEETS KindEnum = "google-sheets"
	SNAPCHAT KindEnum = "snapchat"
	LINKEDIN_ADS KindEnum = "linkedin-ads"
	REDDIT_ADS KindEnum = "reddit-ads"
	TIKTOK_ADS KindEnum = "tiktok-ads"
	INTERCOM KindEnum = "intercom"
	EMAIL KindEnum = "email"
	LINEAR KindEnum = "linear"
	GITHUB KindEnum = "github"
	GITLAB KindEnum = "gitlab"
	META_ADS KindEnum = "meta-ads"
	TWILIO KindEnum = "twilio"
	CLICKUP KindEnum = "clickup"
	VERCEL KindEnum = "vercel"
	DATABRICKS KindEnum = "databricks"
)

// All allowed values of KindEnum enum
var AllowedKindEnumEnumValues = []KindEnum{
	"slack",
	"salesforce",
	"hubspot",
	"google-pubsub",
	"google-cloud-storage",
	"google-ads",
	"google-sheets",
	"snapchat",
	"linkedin-ads",
	"reddit-ads",
	"tiktok-ads",
	"intercom",
	"email",
	"linear",
	"github",
	"gitlab",
	"meta-ads",
	"twilio",
	"clickup",
	"vercel",
	"databricks",
}

func (v *KindEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := KindEnum(value)
	for _, existing := range AllowedKindEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid KindEnum", value)
}

// NewKindEnumFromValue returns a pointer to a valid KindEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewKindEnumFromValue(v string) (*KindEnum, error) {
	ev := KindEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for KindEnum: valid values are %v", v, AllowedKindEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v KindEnum) IsValid() bool {
	for _, existing := range AllowedKindEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to KindEnum value
func (v KindEnum) Ptr() *KindEnum {
	return &v
}

type NullableKindEnum struct {
	value *KindEnum
	isSet bool
}

func (v NullableKindEnum) Get() *KindEnum {
	return v.value
}

func (v *NullableKindEnum) Set(val *KindEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableKindEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableKindEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKindEnum(val *KindEnum) *NullableKindEnum {
	return &NullableKindEnum{value: val, isSet: true}
}

func (v NullableKindEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKindEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

