/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"fmt"
)

// RoleAtOrganizationEnum * `engineering` - Engineering * `data` - Data * `product` - Product Management * `founder` - Founder * `leadership` - Leadership * `marketing` - Marketing * `sales` - Sales / Success * `other` - Other
type RoleAtOrganizationEnum string

// List of RoleAtOrganizationEnum
const (
	ENGINEERING RoleAtOrganizationEnum = "engineering"
	DATA RoleAtOrganizationEnum = "data"
	PRODUCT RoleAtOrganizationEnum = "product"
	FOUNDER RoleAtOrganizationEnum = "founder"
	LEADERSHIP RoleAtOrganizationEnum = "leadership"
	MARKETING RoleAtOrganizationEnum = "marketing"
	SALES RoleAtOrganizationEnum = "sales"
	OTHER RoleAtOrganizationEnum = "other"
)

// All allowed values of RoleAtOrganizationEnum enum
var AllowedRoleAtOrganizationEnumEnumValues = []RoleAtOrganizationEnum{
	"engineering",
	"data",
	"product",
	"founder",
	"leadership",
	"marketing",
	"sales",
	"other",
}

func (v *RoleAtOrganizationEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RoleAtOrganizationEnum(value)
	for _, existing := range AllowedRoleAtOrganizationEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RoleAtOrganizationEnum", value)
}

// NewRoleAtOrganizationEnumFromValue returns a pointer to a valid RoleAtOrganizationEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRoleAtOrganizationEnumFromValue(v string) (*RoleAtOrganizationEnum, error) {
	ev := RoleAtOrganizationEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RoleAtOrganizationEnum: valid values are %v", v, AllowedRoleAtOrganizationEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RoleAtOrganizationEnum) IsValid() bool {
	for _, existing := range AllowedRoleAtOrganizationEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RoleAtOrganizationEnum value
func (v RoleAtOrganizationEnum) Ptr() *RoleAtOrganizationEnum {
	return &v
}

type NullableRoleAtOrganizationEnum struct {
	value *RoleAtOrganizationEnum
	isSet bool
}

func (v NullableRoleAtOrganizationEnum) Get() *RoleAtOrganizationEnum {
	return v.value
}

func (v *NullableRoleAtOrganizationEnum) Set(val *RoleAtOrganizationEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleAtOrganizationEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleAtOrganizationEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleAtOrganizationEnum(val *RoleAtOrganizationEnum) *NullableRoleAtOrganizationEnum {
	return &NullableRoleAtOrganizationEnum{value: val, isSet: true}
}

func (v NullableRoleAtOrganizationEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleAtOrganizationEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

