/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"fmt"
)

// RetentionDashboardDisplayType the model 'RetentionDashboardDisplayType'
type RetentionDashboardDisplayType string

// List of RetentionDashboardDisplayType
const (
	TABLE_ONLY RetentionDashboardDisplayType = "table_only"
	GRAPH_ONLY RetentionDashboardDisplayType = "graph_only"
	ALL RetentionDashboardDisplayType = "all"
)

// All allowed values of RetentionDashboardDisplayType enum
var AllowedRetentionDashboardDisplayTypeEnumValues = []RetentionDashboardDisplayType{
	"table_only",
	"graph_only",
	"all",
}

func (v *RetentionDashboardDisplayType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RetentionDashboardDisplayType(value)
	for _, existing := range AllowedRetentionDashboardDisplayTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RetentionDashboardDisplayType", value)
}

// NewRetentionDashboardDisplayTypeFromValue returns a pointer to a valid RetentionDashboardDisplayType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRetentionDashboardDisplayTypeFromValue(v string) (*RetentionDashboardDisplayType, error) {
	ev := RetentionDashboardDisplayType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RetentionDashboardDisplayType: valid values are %v", v, AllowedRetentionDashboardDisplayTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RetentionDashboardDisplayType) IsValid() bool {
	for _, existing := range AllowedRetentionDashboardDisplayTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RetentionDashboardDisplayType value
func (v RetentionDashboardDisplayType) Ptr() *RetentionDashboardDisplayType {
	return &v
}

type NullableRetentionDashboardDisplayType struct {
	value *RetentionDashboardDisplayType
	isSet bool
}

func (v NullableRetentionDashboardDisplayType) Get() *RetentionDashboardDisplayType {
	return v.value
}

func (v *NullableRetentionDashboardDisplayType) Set(val *RetentionDashboardDisplayType) {
	v.value = val
	v.isSet = true
}

func (v NullableRetentionDashboardDisplayType) IsSet() bool {
	return v.isSet
}

func (v *NullableRetentionDashboardDisplayType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetentionDashboardDisplayType(val *RetentionDashboardDisplayType) *NullableRetentionDashboardDisplayType {
	return &NullableRetentionDashboardDisplayType{value: val, isSet: true}
}

func (v NullableRetentionDashboardDisplayType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetentionDashboardDisplayType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

