/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
)

// checks if the TableSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableSettings{}

// TableSettings struct for TableSettings
type TableSettings struct {
	Columns []ChartAxis `json:"columns,omitempty"`
	ConditionalFormatting []ConditionalFormattingRule `json:"conditionalFormatting,omitempty"`
}

// NewTableSettings instantiates a new TableSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableSettings() *TableSettings {
	this := TableSettings{}
	return &this
}

// NewTableSettingsWithDefaults instantiates a new TableSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableSettingsWithDefaults() *TableSettings {
	this := TableSettings{}
	return &this
}

// GetColumns returns the Columns field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TableSettings) GetColumns() []ChartAxis {
	if o == nil {
		var ret []ChartAxis
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TableSettings) GetColumnsOk() ([]ChartAxis, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *TableSettings) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []ChartAxis and assigns it to the Columns field.
func (o *TableSettings) SetColumns(v []ChartAxis) {
	o.Columns = v
}

// GetConditionalFormatting returns the ConditionalFormatting field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TableSettings) GetConditionalFormatting() []ConditionalFormattingRule {
	if o == nil {
		var ret []ConditionalFormattingRule
		return ret
	}
	return o.ConditionalFormatting
}

// GetConditionalFormattingOk returns a tuple with the ConditionalFormatting field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TableSettings) GetConditionalFormattingOk() ([]ConditionalFormattingRule, bool) {
	if o == nil || IsNil(o.ConditionalFormatting) {
		return nil, false
	}
	return o.ConditionalFormatting, true
}

// HasConditionalFormatting returns a boolean if a field has been set.
func (o *TableSettings) HasConditionalFormatting() bool {
	if o != nil && !IsNil(o.ConditionalFormatting) {
		return true
	}

	return false
}

// SetConditionalFormatting gets a reference to the given []ConditionalFormattingRule and assigns it to the ConditionalFormatting field.
func (o *TableSettings) SetConditionalFormatting(v []ConditionalFormattingRule) {
	o.ConditionalFormatting = v
}

func (o TableSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Columns != nil {
		toSerialize["columns"] = o.Columns
	}
	if o.ConditionalFormatting != nil {
		toSerialize["conditionalFormatting"] = o.ConditionalFormatting
	}
	return toSerialize, nil
}

type NullableTableSettings struct {
	value *TableSettings
	isSet bool
}

func (v NullableTableSettings) Get() *TableSettings {
	return v.value
}

func (v *NullableTableSettings) Set(val *TableSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableTableSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableTableSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableSettings(val *TableSettings) *NullableTableSettings {
	return &NullableTableSettings{value: val, isSet: true}
}

func (v NullableTableSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


