/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ErrorTrackingIssueCorrelationQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorTrackingIssueCorrelationQuery{}

// ErrorTrackingIssueCorrelationQuery struct for ErrorTrackingIssueCorrelationQuery
type ErrorTrackingIssueCorrelationQuery struct {
	Events []string `json:"events"`
	Kind *string `json:"kind,omitempty"`
	Modifiers *HogQLQueryModifiers `json:"modifiers,omitempty"`
	Response *ErrorTrackingIssueCorrelationQueryResponse `json:"response,omitempty"`
	Tags *QueryLogTags `json:"tags,omitempty"`
	// version of the node, used for schema migrations
	Version NullableFloat32 `json:"version,omitempty"`
}

type _ErrorTrackingIssueCorrelationQuery ErrorTrackingIssueCorrelationQuery

// NewErrorTrackingIssueCorrelationQuery instantiates a new ErrorTrackingIssueCorrelationQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorTrackingIssueCorrelationQuery(events []string) *ErrorTrackingIssueCorrelationQuery {
	this := ErrorTrackingIssueCorrelationQuery{}
	this.Events = events
	var kind string = "ErrorTrackingIssueCorrelationQuery"
	this.Kind = &kind
	return &this
}

// NewErrorTrackingIssueCorrelationQueryWithDefaults instantiates a new ErrorTrackingIssueCorrelationQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorTrackingIssueCorrelationQueryWithDefaults() *ErrorTrackingIssueCorrelationQuery {
	this := ErrorTrackingIssueCorrelationQuery{}
	var kind string = "ErrorTrackingIssueCorrelationQuery"
	this.Kind = &kind
	return &this
}

// GetEvents returns the Events field value
func (o *ErrorTrackingIssueCorrelationQuery) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *ErrorTrackingIssueCorrelationQuery) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *ErrorTrackingIssueCorrelationQuery) SetEvents(v []string) {
	o.Events = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ErrorTrackingIssueCorrelationQuery) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorTrackingIssueCorrelationQuery) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ErrorTrackingIssueCorrelationQuery) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ErrorTrackingIssueCorrelationQuery) SetKind(v string) {
	o.Kind = &v
}

// GetModifiers returns the Modifiers field value if set, zero value otherwise.
func (o *ErrorTrackingIssueCorrelationQuery) GetModifiers() HogQLQueryModifiers {
	if o == nil || IsNil(o.Modifiers) {
		var ret HogQLQueryModifiers
		return ret
	}
	return *o.Modifiers
}

// GetModifiersOk returns a tuple with the Modifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorTrackingIssueCorrelationQuery) GetModifiersOk() (*HogQLQueryModifiers, bool) {
	if o == nil || IsNil(o.Modifiers) {
		return nil, false
	}
	return o.Modifiers, true
}

// HasModifiers returns a boolean if a field has been set.
func (o *ErrorTrackingIssueCorrelationQuery) HasModifiers() bool {
	if o != nil && !IsNil(o.Modifiers) {
		return true
	}

	return false
}

// SetModifiers gets a reference to the given HogQLQueryModifiers and assigns it to the Modifiers field.
func (o *ErrorTrackingIssueCorrelationQuery) SetModifiers(v HogQLQueryModifiers) {
	o.Modifiers = &v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *ErrorTrackingIssueCorrelationQuery) GetResponse() ErrorTrackingIssueCorrelationQueryResponse {
	if o == nil || IsNil(o.Response) {
		var ret ErrorTrackingIssueCorrelationQueryResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorTrackingIssueCorrelationQuery) GetResponseOk() (*ErrorTrackingIssueCorrelationQueryResponse, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *ErrorTrackingIssueCorrelationQuery) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given ErrorTrackingIssueCorrelationQueryResponse and assigns it to the Response field.
func (o *ErrorTrackingIssueCorrelationQuery) SetResponse(v ErrorTrackingIssueCorrelationQueryResponse) {
	o.Response = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ErrorTrackingIssueCorrelationQuery) GetTags() QueryLogTags {
	if o == nil || IsNil(o.Tags) {
		var ret QueryLogTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorTrackingIssueCorrelationQuery) GetTagsOk() (*QueryLogTags, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ErrorTrackingIssueCorrelationQuery) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given QueryLogTags and assigns it to the Tags field.
func (o *ErrorTrackingIssueCorrelationQuery) SetTags(v QueryLogTags) {
	o.Tags = &v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ErrorTrackingIssueCorrelationQuery) GetVersion() float32 {
	if o == nil || IsNil(o.Version.Get()) {
		var ret float32
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ErrorTrackingIssueCorrelationQuery) GetVersionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *ErrorTrackingIssueCorrelationQuery) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableFloat32 and assigns it to the Version field.
func (o *ErrorTrackingIssueCorrelationQuery) SetVersion(v float32) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *ErrorTrackingIssueCorrelationQuery) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *ErrorTrackingIssueCorrelationQuery) UnsetVersion() {
	o.Version.Unset()
}

func (o ErrorTrackingIssueCorrelationQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorTrackingIssueCorrelationQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Modifiers) {
		toSerialize["modifiers"] = o.Modifiers
	}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	return toSerialize, nil
}

func (o *ErrorTrackingIssueCorrelationQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorTrackingIssueCorrelationQuery := _ErrorTrackingIssueCorrelationQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varErrorTrackingIssueCorrelationQuery)

	if err != nil {
		return err
	}

	*o = ErrorTrackingIssueCorrelationQuery(varErrorTrackingIssueCorrelationQuery)

	return err
}

type NullableErrorTrackingIssueCorrelationQuery struct {
	value *ErrorTrackingIssueCorrelationQuery
	isSet bool
}

func (v NullableErrorTrackingIssueCorrelationQuery) Get() *ErrorTrackingIssueCorrelationQuery {
	return v.value
}

func (v *NullableErrorTrackingIssueCorrelationQuery) Set(val *ErrorTrackingIssueCorrelationQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorTrackingIssueCorrelationQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorTrackingIssueCorrelationQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorTrackingIssueCorrelationQuery(val *ErrorTrackingIssueCorrelationQuery) *NullableErrorTrackingIssueCorrelationQuery {
	return &NullableErrorTrackingIssueCorrelationQuery{value: val, isSet: true}
}

func (v NullableErrorTrackingIssueCorrelationQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorTrackingIssueCorrelationQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


