/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventDefinition{}

// EventDefinition struct for EventDefinition
type EventDefinition struct {
	Elements []interface{} `json:"elements"`
	Event string `json:"event"`
	Properties map[string]interface{} `json:"properties"`
}

type _EventDefinition EventDefinition

// NewEventDefinition instantiates a new EventDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventDefinition(elements []interface{}, event string, properties map[string]interface{}) *EventDefinition {
	this := EventDefinition{}
	this.Elements = elements
	this.Event = event
	this.Properties = properties
	return &this
}

// NewEventDefinitionWithDefaults instantiates a new EventDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventDefinitionWithDefaults() *EventDefinition {
	this := EventDefinition{}
	return &this
}

// GetElements returns the Elements field value
func (o *EventDefinition) GetElements() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Elements
}

// GetElementsOk returns a tuple with the Elements field value
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetElementsOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Elements, true
}

// SetElements sets field value
func (o *EventDefinition) SetElements(v []interface{}) {
	o.Elements = v
}

// GetEvent returns the Event field value
func (o *EventDefinition) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *EventDefinition) SetEvent(v string) {
	o.Event = v
}

// GetProperties returns the Properties field value
func (o *EventDefinition) GetProperties() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetPropertiesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *EventDefinition) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

func (o EventDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["elements"] = o.Elements
	toSerialize["event"] = o.Event
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"elements",
		"event",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventDefinition := _EventDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventDefinition)

	if err != nil {
		return err
	}

	*o = EventDefinition(varEventDefinition)

	return err
}

type NullableEventDefinition struct {
	value *EventDefinition
	isSet bool
}

func (v NullableEventDefinition) Get() *EventDefinition {
	return v.value
}

func (v *NullableEventDefinition) Set(val *EventDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableEventDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableEventDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventDefinition(val *EventDefinition) *NullableEventDefinition {
	return &NullableEventDefinition{value: val, isSet: true}
}

func (v NullableEventDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


