/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"fmt"
)

// SummarizeTypeEnum * `trace` - trace * `event` - event
type SummarizeTypeEnum string

// List of SummarizeTypeEnum
const (
	TRACE SummarizeTypeEnum = "trace"
	EVENT SummarizeTypeEnum = "event"
)

// All allowed values of SummarizeTypeEnum enum
var AllowedSummarizeTypeEnumEnumValues = []SummarizeTypeEnum{
	"trace",
	"event",
}

func (v *SummarizeTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SummarizeTypeEnum(value)
	for _, existing := range AllowedSummarizeTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SummarizeTypeEnum", value)
}

// NewSummarizeTypeEnumFromValue returns a pointer to a valid SummarizeTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSummarizeTypeEnumFromValue(v string) (*SummarizeTypeEnum, error) {
	ev := SummarizeTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SummarizeTypeEnum: valid values are %v", v, AllowedSummarizeTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SummarizeTypeEnum) IsValid() bool {
	for _, existing := range AllowedSummarizeTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SummarizeTypeEnum value
func (v SummarizeTypeEnum) Ptr() *SummarizeTypeEnum {
	return &v
}

type NullableSummarizeTypeEnum struct {
	value *SummarizeTypeEnum
	isSet bool
}

func (v NullableSummarizeTypeEnum) Get() *SummarizeTypeEnum {
	return v.value
}

func (v *NullableSummarizeTypeEnum) Set(val *SummarizeTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableSummarizeTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableSummarizeTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummarizeTypeEnum(val *SummarizeTypeEnum) *NullableSummarizeTypeEnum {
	return &NullableSummarizeTypeEnum{value: val, isSet: true}
}

func (v NullableSummarizeTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummarizeTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

