/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
)

// checks if the RecordingsQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordingsQuery{}

// RecordingsQuery struct for RecordingsQuery
type RecordingsQuery struct {
	Actions []map[string]interface{} `json:"actions,omitempty"`
	// Cursor for pagination. Contains the ordering value and session_id from the last record of the previous page.
	After NullableString `json:"after,omitempty"`
	CommentText *RecordingPropertyFilter `json:"comment_text,omitempty"`
	ConsoleLogFilters []LogEntryPropertyFilter `json:"console_log_filters,omitempty"`
	DateFrom NullableString `json:"date_from,omitempty"`
	DateTo NullableString `json:"date_to,omitempty"`
	DistinctIds []string `json:"distinct_ids,omitempty"`
	Events []map[string]interface{} `json:"events,omitempty"`
	FilterTestAccounts NullableBool `json:"filter_test_accounts,omitempty"`
	HavingPredicates []FixedpropertiesInner `json:"having_predicates,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Limit NullableInt32 `json:"limit,omitempty"`
	Modifiers *HogQLQueryModifiers `json:"modifiers,omitempty"`
	Offset NullableInt32 `json:"offset,omitempty"`
	Operand *FilterLogicalOperator `json:"operand,omitempty"`
	Order *RecordingOrder `json:"order,omitempty"`
	OrderDirection *RecordingOrderDirection `json:"order_direction,omitempty"`
	PersonUuid NullableString `json:"person_uuid,omitempty"`
	Properties []FixedpropertiesInner `json:"properties,omitempty"`
	Response *RecordingsQueryResponse `json:"response,omitempty"`
	SessionIds []string `json:"session_ids,omitempty"`
	// If provided, this recording will be fetched and prepended to the results, even if it doesn't match the filters
	SessionRecordingId NullableString `json:"session_recording_id,omitempty"`
	Tags *QueryLogTags `json:"tags,omitempty"`
	UserModifiedFilters map[string]interface{} `json:"user_modified_filters,omitempty"`
	// version of the node, used for schema migrations
	Version NullableFloat32 `json:"version,omitempty"`
}

// NewRecordingsQuery instantiates a new RecordingsQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordingsQuery() *RecordingsQuery {
	this := RecordingsQuery{}
	var dateFrom string = "-3d"
	this.DateFrom = *NewNullableString(&dateFrom)
	var kind string = "RecordingsQuery"
	this.Kind = &kind
	return &this
}

// NewRecordingsQueryWithDefaults instantiates a new RecordingsQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordingsQueryWithDefaults() *RecordingsQuery {
	this := RecordingsQuery{}
	var dateFrom string = "-3d"
	this.DateFrom = *NewNullableString(&dateFrom)
	var kind string = "RecordingsQuery"
	this.Kind = &kind
	return &this
}

// GetActions returns the Actions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetActions() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetActionsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *RecordingsQuery) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []map[string]interface{} and assigns it to the Actions field.
func (o *RecordingsQuery) SetActions(v []map[string]interface{}) {
	o.Actions = v
}

// GetAfter returns the After field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetAfter() string {
	if o == nil || IsNil(o.After.Get()) {
		var ret string
		return ret
	}
	return *o.After.Get()
}

// GetAfterOk returns a tuple with the After field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetAfterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.After.Get(), o.After.IsSet()
}

// HasAfter returns a boolean if a field has been set.
func (o *RecordingsQuery) HasAfter() bool {
	if o != nil && o.After.IsSet() {
		return true
	}

	return false
}

// SetAfter gets a reference to the given NullableString and assigns it to the After field.
func (o *RecordingsQuery) SetAfter(v string) {
	o.After.Set(&v)
}
// SetAfterNil sets the value for After to be an explicit nil
func (o *RecordingsQuery) SetAfterNil() {
	o.After.Set(nil)
}

// UnsetAfter ensures that no value is present for After, not even an explicit nil
func (o *RecordingsQuery) UnsetAfter() {
	o.After.Unset()
}

// GetCommentText returns the CommentText field value if set, zero value otherwise.
func (o *RecordingsQuery) GetCommentText() RecordingPropertyFilter {
	if o == nil || IsNil(o.CommentText) {
		var ret RecordingPropertyFilter
		return ret
	}
	return *o.CommentText
}

// GetCommentTextOk returns a tuple with the CommentText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordingsQuery) GetCommentTextOk() (*RecordingPropertyFilter, bool) {
	if o == nil || IsNil(o.CommentText) {
		return nil, false
	}
	return o.CommentText, true
}

// HasCommentText returns a boolean if a field has been set.
func (o *RecordingsQuery) HasCommentText() bool {
	if o != nil && !IsNil(o.CommentText) {
		return true
	}

	return false
}

// SetCommentText gets a reference to the given RecordingPropertyFilter and assigns it to the CommentText field.
func (o *RecordingsQuery) SetCommentText(v RecordingPropertyFilter) {
	o.CommentText = &v
}

// GetConsoleLogFilters returns the ConsoleLogFilters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetConsoleLogFilters() []LogEntryPropertyFilter {
	if o == nil {
		var ret []LogEntryPropertyFilter
		return ret
	}
	return o.ConsoleLogFilters
}

// GetConsoleLogFiltersOk returns a tuple with the ConsoleLogFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetConsoleLogFiltersOk() ([]LogEntryPropertyFilter, bool) {
	if o == nil || IsNil(o.ConsoleLogFilters) {
		return nil, false
	}
	return o.ConsoleLogFilters, true
}

// HasConsoleLogFilters returns a boolean if a field has been set.
func (o *RecordingsQuery) HasConsoleLogFilters() bool {
	if o != nil && !IsNil(o.ConsoleLogFilters) {
		return true
	}

	return false
}

// SetConsoleLogFilters gets a reference to the given []LogEntryPropertyFilter and assigns it to the ConsoleLogFilters field.
func (o *RecordingsQuery) SetConsoleLogFilters(v []LogEntryPropertyFilter) {
	o.ConsoleLogFilters = v
}

// GetDateFrom returns the DateFrom field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetDateFrom() string {
	if o == nil || IsNil(o.DateFrom.Get()) {
		var ret string
		return ret
	}
	return *o.DateFrom.Get()
}

// GetDateFromOk returns a tuple with the DateFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetDateFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateFrom.Get(), o.DateFrom.IsSet()
}

// HasDateFrom returns a boolean if a field has been set.
func (o *RecordingsQuery) HasDateFrom() bool {
	if o != nil && o.DateFrom.IsSet() {
		return true
	}

	return false
}

// SetDateFrom gets a reference to the given NullableString and assigns it to the DateFrom field.
func (o *RecordingsQuery) SetDateFrom(v string) {
	o.DateFrom.Set(&v)
}
// SetDateFromNil sets the value for DateFrom to be an explicit nil
func (o *RecordingsQuery) SetDateFromNil() {
	o.DateFrom.Set(nil)
}

// UnsetDateFrom ensures that no value is present for DateFrom, not even an explicit nil
func (o *RecordingsQuery) UnsetDateFrom() {
	o.DateFrom.Unset()
}

// GetDateTo returns the DateTo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetDateTo() string {
	if o == nil || IsNil(o.DateTo.Get()) {
		var ret string
		return ret
	}
	return *o.DateTo.Get()
}

// GetDateToOk returns a tuple with the DateTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetDateToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateTo.Get(), o.DateTo.IsSet()
}

// HasDateTo returns a boolean if a field has been set.
func (o *RecordingsQuery) HasDateTo() bool {
	if o != nil && o.DateTo.IsSet() {
		return true
	}

	return false
}

// SetDateTo gets a reference to the given NullableString and assigns it to the DateTo field.
func (o *RecordingsQuery) SetDateTo(v string) {
	o.DateTo.Set(&v)
}
// SetDateToNil sets the value for DateTo to be an explicit nil
func (o *RecordingsQuery) SetDateToNil() {
	o.DateTo.Set(nil)
}

// UnsetDateTo ensures that no value is present for DateTo, not even an explicit nil
func (o *RecordingsQuery) UnsetDateTo() {
	o.DateTo.Unset()
}

// GetDistinctIds returns the DistinctIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetDistinctIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.DistinctIds
}

// GetDistinctIdsOk returns a tuple with the DistinctIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetDistinctIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DistinctIds) {
		return nil, false
	}
	return o.DistinctIds, true
}

// HasDistinctIds returns a boolean if a field has been set.
func (o *RecordingsQuery) HasDistinctIds() bool {
	if o != nil && !IsNil(o.DistinctIds) {
		return true
	}

	return false
}

// SetDistinctIds gets a reference to the given []string and assigns it to the DistinctIds field.
func (o *RecordingsQuery) SetDistinctIds(v []string) {
	o.DistinctIds = v
}

// GetEvents returns the Events field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetEvents() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetEventsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *RecordingsQuery) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []map[string]interface{} and assigns it to the Events field.
func (o *RecordingsQuery) SetEvents(v []map[string]interface{}) {
	o.Events = v
}

// GetFilterTestAccounts returns the FilterTestAccounts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetFilterTestAccounts() bool {
	if o == nil || IsNil(o.FilterTestAccounts.Get()) {
		var ret bool
		return ret
	}
	return *o.FilterTestAccounts.Get()
}

// GetFilterTestAccountsOk returns a tuple with the FilterTestAccounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetFilterTestAccountsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.FilterTestAccounts.Get(), o.FilterTestAccounts.IsSet()
}

// HasFilterTestAccounts returns a boolean if a field has been set.
func (o *RecordingsQuery) HasFilterTestAccounts() bool {
	if o != nil && o.FilterTestAccounts.IsSet() {
		return true
	}

	return false
}

// SetFilterTestAccounts gets a reference to the given NullableBool and assigns it to the FilterTestAccounts field.
func (o *RecordingsQuery) SetFilterTestAccounts(v bool) {
	o.FilterTestAccounts.Set(&v)
}
// SetFilterTestAccountsNil sets the value for FilterTestAccounts to be an explicit nil
func (o *RecordingsQuery) SetFilterTestAccountsNil() {
	o.FilterTestAccounts.Set(nil)
}

// UnsetFilterTestAccounts ensures that no value is present for FilterTestAccounts, not even an explicit nil
func (o *RecordingsQuery) UnsetFilterTestAccounts() {
	o.FilterTestAccounts.Unset()
}

// GetHavingPredicates returns the HavingPredicates field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetHavingPredicates() []FixedpropertiesInner {
	if o == nil {
		var ret []FixedpropertiesInner
		return ret
	}
	return o.HavingPredicates
}

// GetHavingPredicatesOk returns a tuple with the HavingPredicates field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetHavingPredicatesOk() ([]FixedpropertiesInner, bool) {
	if o == nil || IsNil(o.HavingPredicates) {
		return nil, false
	}
	return o.HavingPredicates, true
}

// HasHavingPredicates returns a boolean if a field has been set.
func (o *RecordingsQuery) HasHavingPredicates() bool {
	if o != nil && !IsNil(o.HavingPredicates) {
		return true
	}

	return false
}

// SetHavingPredicates gets a reference to the given []FixedpropertiesInner and assigns it to the HavingPredicates field.
func (o *RecordingsQuery) SetHavingPredicates(v []FixedpropertiesInner) {
	o.HavingPredicates = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *RecordingsQuery) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordingsQuery) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *RecordingsQuery) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *RecordingsQuery) SetKind(v string) {
	o.Kind = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetLimit() int32 {
	if o == nil || IsNil(o.Limit.Get()) {
		var ret int32
		return ret
	}
	return *o.Limit.Get()
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Limit.Get(), o.Limit.IsSet()
}

// HasLimit returns a boolean if a field has been set.
func (o *RecordingsQuery) HasLimit() bool {
	if o != nil && o.Limit.IsSet() {
		return true
	}

	return false
}

// SetLimit gets a reference to the given NullableInt32 and assigns it to the Limit field.
func (o *RecordingsQuery) SetLimit(v int32) {
	o.Limit.Set(&v)
}
// SetLimitNil sets the value for Limit to be an explicit nil
func (o *RecordingsQuery) SetLimitNil() {
	o.Limit.Set(nil)
}

// UnsetLimit ensures that no value is present for Limit, not even an explicit nil
func (o *RecordingsQuery) UnsetLimit() {
	o.Limit.Unset()
}

// GetModifiers returns the Modifiers field value if set, zero value otherwise.
func (o *RecordingsQuery) GetModifiers() HogQLQueryModifiers {
	if o == nil || IsNil(o.Modifiers) {
		var ret HogQLQueryModifiers
		return ret
	}
	return *o.Modifiers
}

// GetModifiersOk returns a tuple with the Modifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordingsQuery) GetModifiersOk() (*HogQLQueryModifiers, bool) {
	if o == nil || IsNil(o.Modifiers) {
		return nil, false
	}
	return o.Modifiers, true
}

// HasModifiers returns a boolean if a field has been set.
func (o *RecordingsQuery) HasModifiers() bool {
	if o != nil && !IsNil(o.Modifiers) {
		return true
	}

	return false
}

// SetModifiers gets a reference to the given HogQLQueryModifiers and assigns it to the Modifiers field.
func (o *RecordingsQuery) SetModifiers(v HogQLQueryModifiers) {
	o.Modifiers = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetOffset() int32 {
	if o == nil || IsNil(o.Offset.Get()) {
		var ret int32
		return ret
	}
	return *o.Offset.Get()
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Offset.Get(), o.Offset.IsSet()
}

// HasOffset returns a boolean if a field has been set.
func (o *RecordingsQuery) HasOffset() bool {
	if o != nil && o.Offset.IsSet() {
		return true
	}

	return false
}

// SetOffset gets a reference to the given NullableInt32 and assigns it to the Offset field.
func (o *RecordingsQuery) SetOffset(v int32) {
	o.Offset.Set(&v)
}
// SetOffsetNil sets the value for Offset to be an explicit nil
func (o *RecordingsQuery) SetOffsetNil() {
	o.Offset.Set(nil)
}

// UnsetOffset ensures that no value is present for Offset, not even an explicit nil
func (o *RecordingsQuery) UnsetOffset() {
	o.Offset.Unset()
}

// GetOperand returns the Operand field value if set, zero value otherwise.
func (o *RecordingsQuery) GetOperand() FilterLogicalOperator {
	if o == nil || IsNil(o.Operand) {
		var ret FilterLogicalOperator
		return ret
	}
	return *o.Operand
}

// GetOperandOk returns a tuple with the Operand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordingsQuery) GetOperandOk() (*FilterLogicalOperator, bool) {
	if o == nil || IsNil(o.Operand) {
		return nil, false
	}
	return o.Operand, true
}

// HasOperand returns a boolean if a field has been set.
func (o *RecordingsQuery) HasOperand() bool {
	if o != nil && !IsNil(o.Operand) {
		return true
	}

	return false
}

// SetOperand gets a reference to the given FilterLogicalOperator and assigns it to the Operand field.
func (o *RecordingsQuery) SetOperand(v FilterLogicalOperator) {
	o.Operand = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *RecordingsQuery) GetOrder() RecordingOrder {
	if o == nil || IsNil(o.Order) {
		var ret RecordingOrder
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordingsQuery) GetOrderOk() (*RecordingOrder, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *RecordingsQuery) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given RecordingOrder and assigns it to the Order field.
func (o *RecordingsQuery) SetOrder(v RecordingOrder) {
	o.Order = &v
}

// GetOrderDirection returns the OrderDirection field value if set, zero value otherwise.
func (o *RecordingsQuery) GetOrderDirection() RecordingOrderDirection {
	if o == nil || IsNil(o.OrderDirection) {
		var ret RecordingOrderDirection
		return ret
	}
	return *o.OrderDirection
}

// GetOrderDirectionOk returns a tuple with the OrderDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordingsQuery) GetOrderDirectionOk() (*RecordingOrderDirection, bool) {
	if o == nil || IsNil(o.OrderDirection) {
		return nil, false
	}
	return o.OrderDirection, true
}

// HasOrderDirection returns a boolean if a field has been set.
func (o *RecordingsQuery) HasOrderDirection() bool {
	if o != nil && !IsNil(o.OrderDirection) {
		return true
	}

	return false
}

// SetOrderDirection gets a reference to the given RecordingOrderDirection and assigns it to the OrderDirection field.
func (o *RecordingsQuery) SetOrderDirection(v RecordingOrderDirection) {
	o.OrderDirection = &v
}

// GetPersonUuid returns the PersonUuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetPersonUuid() string {
	if o == nil || IsNil(o.PersonUuid.Get()) {
		var ret string
		return ret
	}
	return *o.PersonUuid.Get()
}

// GetPersonUuidOk returns a tuple with the PersonUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetPersonUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PersonUuid.Get(), o.PersonUuid.IsSet()
}

// HasPersonUuid returns a boolean if a field has been set.
func (o *RecordingsQuery) HasPersonUuid() bool {
	if o != nil && o.PersonUuid.IsSet() {
		return true
	}

	return false
}

// SetPersonUuid gets a reference to the given NullableString and assigns it to the PersonUuid field.
func (o *RecordingsQuery) SetPersonUuid(v string) {
	o.PersonUuid.Set(&v)
}
// SetPersonUuidNil sets the value for PersonUuid to be an explicit nil
func (o *RecordingsQuery) SetPersonUuidNil() {
	o.PersonUuid.Set(nil)
}

// UnsetPersonUuid ensures that no value is present for PersonUuid, not even an explicit nil
func (o *RecordingsQuery) UnsetPersonUuid() {
	o.PersonUuid.Unset()
}

// GetProperties returns the Properties field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetProperties() []FixedpropertiesInner {
	if o == nil {
		var ret []FixedpropertiesInner
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetPropertiesOk() ([]FixedpropertiesInner, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *RecordingsQuery) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given []FixedpropertiesInner and assigns it to the Properties field.
func (o *RecordingsQuery) SetProperties(v []FixedpropertiesInner) {
	o.Properties = v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *RecordingsQuery) GetResponse() RecordingsQueryResponse {
	if o == nil || IsNil(o.Response) {
		var ret RecordingsQueryResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordingsQuery) GetResponseOk() (*RecordingsQueryResponse, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *RecordingsQuery) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given RecordingsQueryResponse and assigns it to the Response field.
func (o *RecordingsQuery) SetResponse(v RecordingsQueryResponse) {
	o.Response = &v
}

// GetSessionIds returns the SessionIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetSessionIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.SessionIds
}

// GetSessionIdsOk returns a tuple with the SessionIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetSessionIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SessionIds) {
		return nil, false
	}
	return o.SessionIds, true
}

// HasSessionIds returns a boolean if a field has been set.
func (o *RecordingsQuery) HasSessionIds() bool {
	if o != nil && !IsNil(o.SessionIds) {
		return true
	}

	return false
}

// SetSessionIds gets a reference to the given []string and assigns it to the SessionIds field.
func (o *RecordingsQuery) SetSessionIds(v []string) {
	o.SessionIds = v
}

// GetSessionRecordingId returns the SessionRecordingId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetSessionRecordingId() string {
	if o == nil || IsNil(o.SessionRecordingId.Get()) {
		var ret string
		return ret
	}
	return *o.SessionRecordingId.Get()
}

// GetSessionRecordingIdOk returns a tuple with the SessionRecordingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetSessionRecordingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SessionRecordingId.Get(), o.SessionRecordingId.IsSet()
}

// HasSessionRecordingId returns a boolean if a field has been set.
func (o *RecordingsQuery) HasSessionRecordingId() bool {
	if o != nil && o.SessionRecordingId.IsSet() {
		return true
	}

	return false
}

// SetSessionRecordingId gets a reference to the given NullableString and assigns it to the SessionRecordingId field.
func (o *RecordingsQuery) SetSessionRecordingId(v string) {
	o.SessionRecordingId.Set(&v)
}
// SetSessionRecordingIdNil sets the value for SessionRecordingId to be an explicit nil
func (o *RecordingsQuery) SetSessionRecordingIdNil() {
	o.SessionRecordingId.Set(nil)
}

// UnsetSessionRecordingId ensures that no value is present for SessionRecordingId, not even an explicit nil
func (o *RecordingsQuery) UnsetSessionRecordingId() {
	o.SessionRecordingId.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *RecordingsQuery) GetTags() QueryLogTags {
	if o == nil || IsNil(o.Tags) {
		var ret QueryLogTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordingsQuery) GetTagsOk() (*QueryLogTags, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *RecordingsQuery) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given QueryLogTags and assigns it to the Tags field.
func (o *RecordingsQuery) SetTags(v QueryLogTags) {
	o.Tags = &v
}

// GetUserModifiedFilters returns the UserModifiedFilters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetUserModifiedFilters() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.UserModifiedFilters
}

// GetUserModifiedFiltersOk returns a tuple with the UserModifiedFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetUserModifiedFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.UserModifiedFilters) {
		return map[string]interface{}{}, false
	}
	return o.UserModifiedFilters, true
}

// HasUserModifiedFilters returns a boolean if a field has been set.
func (o *RecordingsQuery) HasUserModifiedFilters() bool {
	if o != nil && !IsNil(o.UserModifiedFilters) {
		return true
	}

	return false
}

// SetUserModifiedFilters gets a reference to the given map[string]interface{} and assigns it to the UserModifiedFilters field.
func (o *RecordingsQuery) SetUserModifiedFilters(v map[string]interface{}) {
	o.UserModifiedFilters = v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecordingsQuery) GetVersion() float32 {
	if o == nil || IsNil(o.Version.Get()) {
		var ret float32
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordingsQuery) GetVersionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *RecordingsQuery) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableFloat32 and assigns it to the Version field.
func (o *RecordingsQuery) SetVersion(v float32) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *RecordingsQuery) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *RecordingsQuery) UnsetVersion() {
	o.Version.Unset()
}

func (o RecordingsQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordingsQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Actions != nil {
		toSerialize["actions"] = o.Actions
	}
	if o.After.IsSet() {
		toSerialize["after"] = o.After.Get()
	}
	if !IsNil(o.CommentText) {
		toSerialize["comment_text"] = o.CommentText
	}
	if o.ConsoleLogFilters != nil {
		toSerialize["console_log_filters"] = o.ConsoleLogFilters
	}
	if o.DateFrom.IsSet() {
		toSerialize["date_from"] = o.DateFrom.Get()
	}
	if o.DateTo.IsSet() {
		toSerialize["date_to"] = o.DateTo.Get()
	}
	if o.DistinctIds != nil {
		toSerialize["distinct_ids"] = o.DistinctIds
	}
	if o.Events != nil {
		toSerialize["events"] = o.Events
	}
	if o.FilterTestAccounts.IsSet() {
		toSerialize["filter_test_accounts"] = o.FilterTestAccounts.Get()
	}
	if o.HavingPredicates != nil {
		toSerialize["having_predicates"] = o.HavingPredicates
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if o.Limit.IsSet() {
		toSerialize["limit"] = o.Limit.Get()
	}
	if !IsNil(o.Modifiers) {
		toSerialize["modifiers"] = o.Modifiers
	}
	if o.Offset.IsSet() {
		toSerialize["offset"] = o.Offset.Get()
	}
	if !IsNil(o.Operand) {
		toSerialize["operand"] = o.Operand
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.OrderDirection) {
		toSerialize["order_direction"] = o.OrderDirection
	}
	if o.PersonUuid.IsSet() {
		toSerialize["person_uuid"] = o.PersonUuid.Get()
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if o.SessionIds != nil {
		toSerialize["session_ids"] = o.SessionIds
	}
	if o.SessionRecordingId.IsSet() {
		toSerialize["session_recording_id"] = o.SessionRecordingId.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.UserModifiedFilters != nil {
		toSerialize["user_modified_filters"] = o.UserModifiedFilters
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	return toSerialize, nil
}

type NullableRecordingsQuery struct {
	value *RecordingsQuery
	isSet bool
}

func (v NullableRecordingsQuery) Get() *RecordingsQuery {
	return v.value
}

func (v *NullableRecordingsQuery) Set(val *RecordingsQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordingsQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordingsQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordingsQuery(val *RecordingsQuery) *NullableRecordingsQuery {
	return &NullableRecordingsQuery{value: val, isSet: true}
}

func (v NullableRecordingsQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordingsQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


