/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"fmt"
)

// CohortTypeEnum * `static` - static * `person_property` - person_property * `behavioral` - behavioral * `realtime` - realtime * `analytical` - analytical
type CohortTypeEnum string

// List of CohortTypeEnum
const (
	STATIC CohortTypeEnum = "static"
	PERSON_PROPERTY CohortTypeEnum = "person_property"
	BEHAVIORAL CohortTypeEnum = "behavioral"
	REALTIME CohortTypeEnum = "realtime"
	ANALYTICAL CohortTypeEnum = "analytical"
)

// All allowed values of CohortTypeEnum enum
var AllowedCohortTypeEnumEnumValues = []CohortTypeEnum{
	"static",
	"person_property",
	"behavioral",
	"realtime",
	"analytical",
}

func (v *CohortTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CohortTypeEnum(value)
	for _, existing := range AllowedCohortTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CohortTypeEnum", value)
}

// NewCohortTypeEnumFromValue returns a pointer to a valid CohortTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCohortTypeEnumFromValue(v string) (*CohortTypeEnum, error) {
	ev := CohortTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CohortTypeEnum: valid values are %v", v, AllowedCohortTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CohortTypeEnum) IsValid() bool {
	for _, existing := range AllowedCohortTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CohortTypeEnum value
func (v CohortTypeEnum) Ptr() *CohortTypeEnum {
	return &v
}

type NullableCohortTypeEnum struct {
	value *CohortTypeEnum
	isSet bool
}

func (v NullableCohortTypeEnum) Get() *CohortTypeEnum {
	return v.value
}

func (v *NullableCohortTypeEnum) Set(val *CohortTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCohortTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCohortTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCohortTypeEnum(val *CohortTypeEnum) *NullableCohortTypeEnum {
	return &NullableCohortTypeEnum{value: val, isSet: true}
}

func (v NullableCohortTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCohortTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

