/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"time"
)

// checks if the PatchedOrganizationDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedOrganizationDomain{}

// PatchedOrganizationDomain struct for PatchedOrganizationDomain
type PatchedOrganizationDomain struct {
	Id *string `json:"id,omitempty"`
	Domain *string `json:"domain,omitempty"`
	// Determines whether a domain is verified or not.
	IsVerified *bool `json:"is_verified,omitempty"`
	VerifiedAt NullableTime `json:"verified_at,omitempty"`
	VerificationChallenge *string `json:"verification_challenge,omitempty"`
	JitProvisioningEnabled *bool `json:"jit_provisioning_enabled,omitempty"`
	SsoEnforcement *string `json:"sso_enforcement,omitempty"`
	// Returns whether SAML is configured for the instance. Does not validate the user has the required license (that check is performed in other places).
	HasSaml *bool `json:"has_saml,omitempty"`
	SamlEntityId NullableString `json:"saml_entity_id,omitempty"`
	SamlAcsUrl NullableString `json:"saml_acs_url,omitempty"`
	SamlX509Cert NullableString `json:"saml_x509_cert,omitempty"`
	// Returns whether SCIM is configured and enabled for this domain.
	HasScim *bool `json:"has_scim,omitempty"`
	ScimEnabled *bool `json:"scim_enabled,omitempty"`
	ScimBaseUrl NullableString `json:"scim_base_url,omitempty"`
	ScimBearerToken NullableString `json:"scim_bearer_token,omitempty"`
}

// NewPatchedOrganizationDomain instantiates a new PatchedOrganizationDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedOrganizationDomain() *PatchedOrganizationDomain {
	this := PatchedOrganizationDomain{}
	return &this
}

// NewPatchedOrganizationDomainWithDefaults instantiates a new PatchedOrganizationDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedOrganizationDomainWithDefaults() *PatchedOrganizationDomain {
	this := PatchedOrganizationDomain{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PatchedOrganizationDomain) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedOrganizationDomain) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PatchedOrganizationDomain) SetId(v string) {
	o.Id = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *PatchedOrganizationDomain) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedOrganizationDomain) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *PatchedOrganizationDomain) SetDomain(v string) {
	o.Domain = &v
}

// GetIsVerified returns the IsVerified field value if set, zero value otherwise.
func (o *PatchedOrganizationDomain) GetIsVerified() bool {
	if o == nil || IsNil(o.IsVerified) {
		var ret bool
		return ret
	}
	return *o.IsVerified
}

// GetIsVerifiedOk returns a tuple with the IsVerified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedOrganizationDomain) GetIsVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsVerified) {
		return nil, false
	}
	return o.IsVerified, true
}

// HasIsVerified returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasIsVerified() bool {
	if o != nil && !IsNil(o.IsVerified) {
		return true
	}

	return false
}

// SetIsVerified gets a reference to the given bool and assigns it to the IsVerified field.
func (o *PatchedOrganizationDomain) SetIsVerified(v bool) {
	o.IsVerified = &v
}

// GetVerifiedAt returns the VerifiedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedOrganizationDomain) GetVerifiedAt() time.Time {
	if o == nil || IsNil(o.VerifiedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.VerifiedAt.Get()
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedOrganizationDomain) GetVerifiedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.VerifiedAt.Get(), o.VerifiedAt.IsSet()
}

// HasVerifiedAt returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasVerifiedAt() bool {
	if o != nil && o.VerifiedAt.IsSet() {
		return true
	}

	return false
}

// SetVerifiedAt gets a reference to the given NullableTime and assigns it to the VerifiedAt field.
func (o *PatchedOrganizationDomain) SetVerifiedAt(v time.Time) {
	o.VerifiedAt.Set(&v)
}
// SetVerifiedAtNil sets the value for VerifiedAt to be an explicit nil
func (o *PatchedOrganizationDomain) SetVerifiedAtNil() {
	o.VerifiedAt.Set(nil)
}

// UnsetVerifiedAt ensures that no value is present for VerifiedAt, not even an explicit nil
func (o *PatchedOrganizationDomain) UnsetVerifiedAt() {
	o.VerifiedAt.Unset()
}

// GetVerificationChallenge returns the VerificationChallenge field value if set, zero value otherwise.
func (o *PatchedOrganizationDomain) GetVerificationChallenge() string {
	if o == nil || IsNil(o.VerificationChallenge) {
		var ret string
		return ret
	}
	return *o.VerificationChallenge
}

// GetVerificationChallengeOk returns a tuple with the VerificationChallenge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedOrganizationDomain) GetVerificationChallengeOk() (*string, bool) {
	if o == nil || IsNil(o.VerificationChallenge) {
		return nil, false
	}
	return o.VerificationChallenge, true
}

// HasVerificationChallenge returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasVerificationChallenge() bool {
	if o != nil && !IsNil(o.VerificationChallenge) {
		return true
	}

	return false
}

// SetVerificationChallenge gets a reference to the given string and assigns it to the VerificationChallenge field.
func (o *PatchedOrganizationDomain) SetVerificationChallenge(v string) {
	o.VerificationChallenge = &v
}

// GetJitProvisioningEnabled returns the JitProvisioningEnabled field value if set, zero value otherwise.
func (o *PatchedOrganizationDomain) GetJitProvisioningEnabled() bool {
	if o == nil || IsNil(o.JitProvisioningEnabled) {
		var ret bool
		return ret
	}
	return *o.JitProvisioningEnabled
}

// GetJitProvisioningEnabledOk returns a tuple with the JitProvisioningEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedOrganizationDomain) GetJitProvisioningEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.JitProvisioningEnabled) {
		return nil, false
	}
	return o.JitProvisioningEnabled, true
}

// HasJitProvisioningEnabled returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasJitProvisioningEnabled() bool {
	if o != nil && !IsNil(o.JitProvisioningEnabled) {
		return true
	}

	return false
}

// SetJitProvisioningEnabled gets a reference to the given bool and assigns it to the JitProvisioningEnabled field.
func (o *PatchedOrganizationDomain) SetJitProvisioningEnabled(v bool) {
	o.JitProvisioningEnabled = &v
}

// GetSsoEnforcement returns the SsoEnforcement field value if set, zero value otherwise.
func (o *PatchedOrganizationDomain) GetSsoEnforcement() string {
	if o == nil || IsNil(o.SsoEnforcement) {
		var ret string
		return ret
	}
	return *o.SsoEnforcement
}

// GetSsoEnforcementOk returns a tuple with the SsoEnforcement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedOrganizationDomain) GetSsoEnforcementOk() (*string, bool) {
	if o == nil || IsNil(o.SsoEnforcement) {
		return nil, false
	}
	return o.SsoEnforcement, true
}

// HasSsoEnforcement returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasSsoEnforcement() bool {
	if o != nil && !IsNil(o.SsoEnforcement) {
		return true
	}

	return false
}

// SetSsoEnforcement gets a reference to the given string and assigns it to the SsoEnforcement field.
func (o *PatchedOrganizationDomain) SetSsoEnforcement(v string) {
	o.SsoEnforcement = &v
}

// GetHasSaml returns the HasSaml field value if set, zero value otherwise.
func (o *PatchedOrganizationDomain) GetHasSaml() bool {
	if o == nil || IsNil(o.HasSaml) {
		var ret bool
		return ret
	}
	return *o.HasSaml
}

// GetHasSamlOk returns a tuple with the HasSaml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedOrganizationDomain) GetHasSamlOk() (*bool, bool) {
	if o == nil || IsNil(o.HasSaml) {
		return nil, false
	}
	return o.HasSaml, true
}

// HasHasSaml returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasHasSaml() bool {
	if o != nil && !IsNil(o.HasSaml) {
		return true
	}

	return false
}

// SetHasSaml gets a reference to the given bool and assigns it to the HasSaml field.
func (o *PatchedOrganizationDomain) SetHasSaml(v bool) {
	o.HasSaml = &v
}

// GetSamlEntityId returns the SamlEntityId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedOrganizationDomain) GetSamlEntityId() string {
	if o == nil || IsNil(o.SamlEntityId.Get()) {
		var ret string
		return ret
	}
	return *o.SamlEntityId.Get()
}

// GetSamlEntityIdOk returns a tuple with the SamlEntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedOrganizationDomain) GetSamlEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SamlEntityId.Get(), o.SamlEntityId.IsSet()
}

// HasSamlEntityId returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasSamlEntityId() bool {
	if o != nil && o.SamlEntityId.IsSet() {
		return true
	}

	return false
}

// SetSamlEntityId gets a reference to the given NullableString and assigns it to the SamlEntityId field.
func (o *PatchedOrganizationDomain) SetSamlEntityId(v string) {
	o.SamlEntityId.Set(&v)
}
// SetSamlEntityIdNil sets the value for SamlEntityId to be an explicit nil
func (o *PatchedOrganizationDomain) SetSamlEntityIdNil() {
	o.SamlEntityId.Set(nil)
}

// UnsetSamlEntityId ensures that no value is present for SamlEntityId, not even an explicit nil
func (o *PatchedOrganizationDomain) UnsetSamlEntityId() {
	o.SamlEntityId.Unset()
}

// GetSamlAcsUrl returns the SamlAcsUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedOrganizationDomain) GetSamlAcsUrl() string {
	if o == nil || IsNil(o.SamlAcsUrl.Get()) {
		var ret string
		return ret
	}
	return *o.SamlAcsUrl.Get()
}

// GetSamlAcsUrlOk returns a tuple with the SamlAcsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedOrganizationDomain) GetSamlAcsUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SamlAcsUrl.Get(), o.SamlAcsUrl.IsSet()
}

// HasSamlAcsUrl returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasSamlAcsUrl() bool {
	if o != nil && o.SamlAcsUrl.IsSet() {
		return true
	}

	return false
}

// SetSamlAcsUrl gets a reference to the given NullableString and assigns it to the SamlAcsUrl field.
func (o *PatchedOrganizationDomain) SetSamlAcsUrl(v string) {
	o.SamlAcsUrl.Set(&v)
}
// SetSamlAcsUrlNil sets the value for SamlAcsUrl to be an explicit nil
func (o *PatchedOrganizationDomain) SetSamlAcsUrlNil() {
	o.SamlAcsUrl.Set(nil)
}

// UnsetSamlAcsUrl ensures that no value is present for SamlAcsUrl, not even an explicit nil
func (o *PatchedOrganizationDomain) UnsetSamlAcsUrl() {
	o.SamlAcsUrl.Unset()
}

// GetSamlX509Cert returns the SamlX509Cert field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedOrganizationDomain) GetSamlX509Cert() string {
	if o == nil || IsNil(o.SamlX509Cert.Get()) {
		var ret string
		return ret
	}
	return *o.SamlX509Cert.Get()
}

// GetSamlX509CertOk returns a tuple with the SamlX509Cert field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedOrganizationDomain) GetSamlX509CertOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SamlX509Cert.Get(), o.SamlX509Cert.IsSet()
}

// HasSamlX509Cert returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasSamlX509Cert() bool {
	if o != nil && o.SamlX509Cert.IsSet() {
		return true
	}

	return false
}

// SetSamlX509Cert gets a reference to the given NullableString and assigns it to the SamlX509Cert field.
func (o *PatchedOrganizationDomain) SetSamlX509Cert(v string) {
	o.SamlX509Cert.Set(&v)
}
// SetSamlX509CertNil sets the value for SamlX509Cert to be an explicit nil
func (o *PatchedOrganizationDomain) SetSamlX509CertNil() {
	o.SamlX509Cert.Set(nil)
}

// UnsetSamlX509Cert ensures that no value is present for SamlX509Cert, not even an explicit nil
func (o *PatchedOrganizationDomain) UnsetSamlX509Cert() {
	o.SamlX509Cert.Unset()
}

// GetHasScim returns the HasScim field value if set, zero value otherwise.
func (o *PatchedOrganizationDomain) GetHasScim() bool {
	if o == nil || IsNil(o.HasScim) {
		var ret bool
		return ret
	}
	return *o.HasScim
}

// GetHasScimOk returns a tuple with the HasScim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedOrganizationDomain) GetHasScimOk() (*bool, bool) {
	if o == nil || IsNil(o.HasScim) {
		return nil, false
	}
	return o.HasScim, true
}

// HasHasScim returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasHasScim() bool {
	if o != nil && !IsNil(o.HasScim) {
		return true
	}

	return false
}

// SetHasScim gets a reference to the given bool and assigns it to the HasScim field.
func (o *PatchedOrganizationDomain) SetHasScim(v bool) {
	o.HasScim = &v
}

// GetScimEnabled returns the ScimEnabled field value if set, zero value otherwise.
func (o *PatchedOrganizationDomain) GetScimEnabled() bool {
	if o == nil || IsNil(o.ScimEnabled) {
		var ret bool
		return ret
	}
	return *o.ScimEnabled
}

// GetScimEnabledOk returns a tuple with the ScimEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedOrganizationDomain) GetScimEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ScimEnabled) {
		return nil, false
	}
	return o.ScimEnabled, true
}

// HasScimEnabled returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasScimEnabled() bool {
	if o != nil && !IsNil(o.ScimEnabled) {
		return true
	}

	return false
}

// SetScimEnabled gets a reference to the given bool and assigns it to the ScimEnabled field.
func (o *PatchedOrganizationDomain) SetScimEnabled(v bool) {
	o.ScimEnabled = &v
}

// GetScimBaseUrl returns the ScimBaseUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedOrganizationDomain) GetScimBaseUrl() string {
	if o == nil || IsNil(o.ScimBaseUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ScimBaseUrl.Get()
}

// GetScimBaseUrlOk returns a tuple with the ScimBaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedOrganizationDomain) GetScimBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScimBaseUrl.Get(), o.ScimBaseUrl.IsSet()
}

// HasScimBaseUrl returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasScimBaseUrl() bool {
	if o != nil && o.ScimBaseUrl.IsSet() {
		return true
	}

	return false
}

// SetScimBaseUrl gets a reference to the given NullableString and assigns it to the ScimBaseUrl field.
func (o *PatchedOrganizationDomain) SetScimBaseUrl(v string) {
	o.ScimBaseUrl.Set(&v)
}
// SetScimBaseUrlNil sets the value for ScimBaseUrl to be an explicit nil
func (o *PatchedOrganizationDomain) SetScimBaseUrlNil() {
	o.ScimBaseUrl.Set(nil)
}

// UnsetScimBaseUrl ensures that no value is present for ScimBaseUrl, not even an explicit nil
func (o *PatchedOrganizationDomain) UnsetScimBaseUrl() {
	o.ScimBaseUrl.Unset()
}

// GetScimBearerToken returns the ScimBearerToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedOrganizationDomain) GetScimBearerToken() string {
	if o == nil || IsNil(o.ScimBearerToken.Get()) {
		var ret string
		return ret
	}
	return *o.ScimBearerToken.Get()
}

// GetScimBearerTokenOk returns a tuple with the ScimBearerToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedOrganizationDomain) GetScimBearerTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScimBearerToken.Get(), o.ScimBearerToken.IsSet()
}

// HasScimBearerToken returns a boolean if a field has been set.
func (o *PatchedOrganizationDomain) HasScimBearerToken() bool {
	if o != nil && o.ScimBearerToken.IsSet() {
		return true
	}

	return false
}

// SetScimBearerToken gets a reference to the given NullableString and assigns it to the ScimBearerToken field.
func (o *PatchedOrganizationDomain) SetScimBearerToken(v string) {
	o.ScimBearerToken.Set(&v)
}
// SetScimBearerTokenNil sets the value for ScimBearerToken to be an explicit nil
func (o *PatchedOrganizationDomain) SetScimBearerTokenNil() {
	o.ScimBearerToken.Set(nil)
}

// UnsetScimBearerToken ensures that no value is present for ScimBearerToken, not even an explicit nil
func (o *PatchedOrganizationDomain) UnsetScimBearerToken() {
	o.ScimBearerToken.Unset()
}

func (o PatchedOrganizationDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedOrganizationDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.IsVerified) {
		toSerialize["is_verified"] = o.IsVerified
	}
	if o.VerifiedAt.IsSet() {
		toSerialize["verified_at"] = o.VerifiedAt.Get()
	}
	if !IsNil(o.VerificationChallenge) {
		toSerialize["verification_challenge"] = o.VerificationChallenge
	}
	if !IsNil(o.JitProvisioningEnabled) {
		toSerialize["jit_provisioning_enabled"] = o.JitProvisioningEnabled
	}
	if !IsNil(o.SsoEnforcement) {
		toSerialize["sso_enforcement"] = o.SsoEnforcement
	}
	if !IsNil(o.HasSaml) {
		toSerialize["has_saml"] = o.HasSaml
	}
	if o.SamlEntityId.IsSet() {
		toSerialize["saml_entity_id"] = o.SamlEntityId.Get()
	}
	if o.SamlAcsUrl.IsSet() {
		toSerialize["saml_acs_url"] = o.SamlAcsUrl.Get()
	}
	if o.SamlX509Cert.IsSet() {
		toSerialize["saml_x509_cert"] = o.SamlX509Cert.Get()
	}
	if !IsNil(o.HasScim) {
		toSerialize["has_scim"] = o.HasScim
	}
	if !IsNil(o.ScimEnabled) {
		toSerialize["scim_enabled"] = o.ScimEnabled
	}
	if o.ScimBaseUrl.IsSet() {
		toSerialize["scim_base_url"] = o.ScimBaseUrl.Get()
	}
	if o.ScimBearerToken.IsSet() {
		toSerialize["scim_bearer_token"] = o.ScimBearerToken.Get()
	}
	return toSerialize, nil
}

type NullablePatchedOrganizationDomain struct {
	value *PatchedOrganizationDomain
	isSet bool
}

func (v NullablePatchedOrganizationDomain) Get() *PatchedOrganizationDomain {
	return v.value
}

func (v *NullablePatchedOrganizationDomain) Set(val *PatchedOrganizationDomain) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedOrganizationDomain) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedOrganizationDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedOrganizationDomain(val *PatchedOrganizationDomain) *NullablePatchedOrganizationDomain {
	return &NullablePatchedOrganizationDomain{value: val, isSet: true}
}

func (v NullablePatchedOrganizationDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedOrganizationDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


