/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionAttributionExplorerQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionAttributionExplorerQuery{}

// SessionAttributionExplorerQuery struct for SessionAttributionExplorerQuery
type SessionAttributionExplorerQuery struct {
	Filters *Filters `json:"filters,omitempty"`
	GroupBy []SessionAttributionGroupBy `json:"groupBy"`
	Kind *string `json:"kind,omitempty"`
	Limit NullableInt32 `json:"limit,omitempty"`
	Modifiers *HogQLQueryModifiers `json:"modifiers,omitempty"`
	Offset NullableInt32 `json:"offset,omitempty"`
	Response *SessionAttributionExplorerQueryResponse `json:"response,omitempty"`
	Tags *QueryLogTags `json:"tags,omitempty"`
	// version of the node, used for schema migrations
	Version NullableFloat32 `json:"version,omitempty"`
}

type _SessionAttributionExplorerQuery SessionAttributionExplorerQuery

// NewSessionAttributionExplorerQuery instantiates a new SessionAttributionExplorerQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionAttributionExplorerQuery(groupBy []SessionAttributionGroupBy) *SessionAttributionExplorerQuery {
	this := SessionAttributionExplorerQuery{}
	this.GroupBy = groupBy
	var kind string = "SessionAttributionExplorerQuery"
	this.Kind = &kind
	return &this
}

// NewSessionAttributionExplorerQueryWithDefaults instantiates a new SessionAttributionExplorerQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionAttributionExplorerQueryWithDefaults() *SessionAttributionExplorerQuery {
	this := SessionAttributionExplorerQuery{}
	var kind string = "SessionAttributionExplorerQuery"
	this.Kind = &kind
	return &this
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *SessionAttributionExplorerQuery) GetFilters() Filters {
	if o == nil || IsNil(o.Filters) {
		var ret Filters
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionAttributionExplorerQuery) GetFiltersOk() (*Filters, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *SessionAttributionExplorerQuery) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given Filters and assigns it to the Filters field.
func (o *SessionAttributionExplorerQuery) SetFilters(v Filters) {
	o.Filters = &v
}

// GetGroupBy returns the GroupBy field value
func (o *SessionAttributionExplorerQuery) GetGroupBy() []SessionAttributionGroupBy {
	if o == nil {
		var ret []SessionAttributionGroupBy
		return ret
	}

	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value
// and a boolean to check if the value has been set.
func (o *SessionAttributionExplorerQuery) GetGroupByOk() ([]SessionAttributionGroupBy, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroupBy, true
}

// SetGroupBy sets field value
func (o *SessionAttributionExplorerQuery) SetGroupBy(v []SessionAttributionGroupBy) {
	o.GroupBy = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *SessionAttributionExplorerQuery) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionAttributionExplorerQuery) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *SessionAttributionExplorerQuery) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *SessionAttributionExplorerQuery) SetKind(v string) {
	o.Kind = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionAttributionExplorerQuery) GetLimit() int32 {
	if o == nil || IsNil(o.Limit.Get()) {
		var ret int32
		return ret
	}
	return *o.Limit.Get()
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionAttributionExplorerQuery) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Limit.Get(), o.Limit.IsSet()
}

// HasLimit returns a boolean if a field has been set.
func (o *SessionAttributionExplorerQuery) HasLimit() bool {
	if o != nil && o.Limit.IsSet() {
		return true
	}

	return false
}

// SetLimit gets a reference to the given NullableInt32 and assigns it to the Limit field.
func (o *SessionAttributionExplorerQuery) SetLimit(v int32) {
	o.Limit.Set(&v)
}
// SetLimitNil sets the value for Limit to be an explicit nil
func (o *SessionAttributionExplorerQuery) SetLimitNil() {
	o.Limit.Set(nil)
}

// UnsetLimit ensures that no value is present for Limit, not even an explicit nil
func (o *SessionAttributionExplorerQuery) UnsetLimit() {
	o.Limit.Unset()
}

// GetModifiers returns the Modifiers field value if set, zero value otherwise.
func (o *SessionAttributionExplorerQuery) GetModifiers() HogQLQueryModifiers {
	if o == nil || IsNil(o.Modifiers) {
		var ret HogQLQueryModifiers
		return ret
	}
	return *o.Modifiers
}

// GetModifiersOk returns a tuple with the Modifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionAttributionExplorerQuery) GetModifiersOk() (*HogQLQueryModifiers, bool) {
	if o == nil || IsNil(o.Modifiers) {
		return nil, false
	}
	return o.Modifiers, true
}

// HasModifiers returns a boolean if a field has been set.
func (o *SessionAttributionExplorerQuery) HasModifiers() bool {
	if o != nil && !IsNil(o.Modifiers) {
		return true
	}

	return false
}

// SetModifiers gets a reference to the given HogQLQueryModifiers and assigns it to the Modifiers field.
func (o *SessionAttributionExplorerQuery) SetModifiers(v HogQLQueryModifiers) {
	o.Modifiers = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionAttributionExplorerQuery) GetOffset() int32 {
	if o == nil || IsNil(o.Offset.Get()) {
		var ret int32
		return ret
	}
	return *o.Offset.Get()
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionAttributionExplorerQuery) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Offset.Get(), o.Offset.IsSet()
}

// HasOffset returns a boolean if a field has been set.
func (o *SessionAttributionExplorerQuery) HasOffset() bool {
	if o != nil && o.Offset.IsSet() {
		return true
	}

	return false
}

// SetOffset gets a reference to the given NullableInt32 and assigns it to the Offset field.
func (o *SessionAttributionExplorerQuery) SetOffset(v int32) {
	o.Offset.Set(&v)
}
// SetOffsetNil sets the value for Offset to be an explicit nil
func (o *SessionAttributionExplorerQuery) SetOffsetNil() {
	o.Offset.Set(nil)
}

// UnsetOffset ensures that no value is present for Offset, not even an explicit nil
func (o *SessionAttributionExplorerQuery) UnsetOffset() {
	o.Offset.Unset()
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *SessionAttributionExplorerQuery) GetResponse() SessionAttributionExplorerQueryResponse {
	if o == nil || IsNil(o.Response) {
		var ret SessionAttributionExplorerQueryResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionAttributionExplorerQuery) GetResponseOk() (*SessionAttributionExplorerQueryResponse, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *SessionAttributionExplorerQuery) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given SessionAttributionExplorerQueryResponse and assigns it to the Response field.
func (o *SessionAttributionExplorerQuery) SetResponse(v SessionAttributionExplorerQueryResponse) {
	o.Response = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SessionAttributionExplorerQuery) GetTags() QueryLogTags {
	if o == nil || IsNil(o.Tags) {
		var ret QueryLogTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionAttributionExplorerQuery) GetTagsOk() (*QueryLogTags, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SessionAttributionExplorerQuery) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given QueryLogTags and assigns it to the Tags field.
func (o *SessionAttributionExplorerQuery) SetTags(v QueryLogTags) {
	o.Tags = &v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionAttributionExplorerQuery) GetVersion() float32 {
	if o == nil || IsNil(o.Version.Get()) {
		var ret float32
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionAttributionExplorerQuery) GetVersionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *SessionAttributionExplorerQuery) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableFloat32 and assigns it to the Version field.
func (o *SessionAttributionExplorerQuery) SetVersion(v float32) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *SessionAttributionExplorerQuery) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *SessionAttributionExplorerQuery) UnsetVersion() {
	o.Version.Unset()
}

func (o SessionAttributionExplorerQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionAttributionExplorerQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["groupBy"] = o.GroupBy
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if o.Limit.IsSet() {
		toSerialize["limit"] = o.Limit.Get()
	}
	if !IsNil(o.Modifiers) {
		toSerialize["modifiers"] = o.Modifiers
	}
	if o.Offset.IsSet() {
		toSerialize["offset"] = o.Offset.Get()
	}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	return toSerialize, nil
}

func (o *SessionAttributionExplorerQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"groupBy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionAttributionExplorerQuery := _SessionAttributionExplorerQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionAttributionExplorerQuery)

	if err != nil {
		return err
	}

	*o = SessionAttributionExplorerQuery(varSessionAttributionExplorerQuery)

	return err
}

type NullableSessionAttributionExplorerQuery struct {
	value *SessionAttributionExplorerQuery
	isSet bool
}

func (v NullableSessionAttributionExplorerQuery) Get() *SessionAttributionExplorerQuery {
	return v.value
}

func (v *NullableSessionAttributionExplorerQuery) Set(val *SessionAttributionExplorerQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionAttributionExplorerQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionAttributionExplorerQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionAttributionExplorerQuery(val *SessionAttributionExplorerQuery) *NullableSessionAttributionExplorerQuery {
	return &NullableSessionAttributionExplorerQuery{value: val, isSet: true}
}

func (v NullableSessionAttributionExplorerQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionAttributionExplorerQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


