/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ActorsPropertyTaxonomyQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActorsPropertyTaxonomyQuery{}

// ActorsPropertyTaxonomyQuery struct for ActorsPropertyTaxonomyQuery
type ActorsPropertyTaxonomyQuery struct {
	GroupTypeIndex NullableInt32 `json:"groupTypeIndex,omitempty"`
	Kind *string `json:"kind,omitempty"`
	MaxPropertyValues NullableInt32 `json:"maxPropertyValues,omitempty"`
	Modifiers *HogQLQueryModifiers `json:"modifiers,omitempty"`
	Properties []string `json:"properties"`
	Response *ActorsPropertyTaxonomyQueryResponse `json:"response,omitempty"`
	Tags *QueryLogTags `json:"tags,omitempty"`
	// version of the node, used for schema migrations
	Version NullableFloat32 `json:"version,omitempty"`
}

type _ActorsPropertyTaxonomyQuery ActorsPropertyTaxonomyQuery

// NewActorsPropertyTaxonomyQuery instantiates a new ActorsPropertyTaxonomyQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActorsPropertyTaxonomyQuery(properties []string) *ActorsPropertyTaxonomyQuery {
	this := ActorsPropertyTaxonomyQuery{}
	var kind string = "ActorsPropertyTaxonomyQuery"
	this.Kind = &kind
	this.Properties = properties
	return &this
}

// NewActorsPropertyTaxonomyQueryWithDefaults instantiates a new ActorsPropertyTaxonomyQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActorsPropertyTaxonomyQueryWithDefaults() *ActorsPropertyTaxonomyQuery {
	this := ActorsPropertyTaxonomyQuery{}
	var kind string = "ActorsPropertyTaxonomyQuery"
	this.Kind = &kind
	return &this
}

// GetGroupTypeIndex returns the GroupTypeIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActorsPropertyTaxonomyQuery) GetGroupTypeIndex() int32 {
	if o == nil || IsNil(o.GroupTypeIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.GroupTypeIndex.Get()
}

// GetGroupTypeIndexOk returns a tuple with the GroupTypeIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActorsPropertyTaxonomyQuery) GetGroupTypeIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroupTypeIndex.Get(), o.GroupTypeIndex.IsSet()
}

// HasGroupTypeIndex returns a boolean if a field has been set.
func (o *ActorsPropertyTaxonomyQuery) HasGroupTypeIndex() bool {
	if o != nil && o.GroupTypeIndex.IsSet() {
		return true
	}

	return false
}

// SetGroupTypeIndex gets a reference to the given NullableInt32 and assigns it to the GroupTypeIndex field.
func (o *ActorsPropertyTaxonomyQuery) SetGroupTypeIndex(v int32) {
	o.GroupTypeIndex.Set(&v)
}
// SetGroupTypeIndexNil sets the value for GroupTypeIndex to be an explicit nil
func (o *ActorsPropertyTaxonomyQuery) SetGroupTypeIndexNil() {
	o.GroupTypeIndex.Set(nil)
}

// UnsetGroupTypeIndex ensures that no value is present for GroupTypeIndex, not even an explicit nil
func (o *ActorsPropertyTaxonomyQuery) UnsetGroupTypeIndex() {
	o.GroupTypeIndex.Unset()
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ActorsPropertyTaxonomyQuery) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActorsPropertyTaxonomyQuery) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ActorsPropertyTaxonomyQuery) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ActorsPropertyTaxonomyQuery) SetKind(v string) {
	o.Kind = &v
}

// GetMaxPropertyValues returns the MaxPropertyValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActorsPropertyTaxonomyQuery) GetMaxPropertyValues() int32 {
	if o == nil || IsNil(o.MaxPropertyValues.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxPropertyValues.Get()
}

// GetMaxPropertyValuesOk returns a tuple with the MaxPropertyValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActorsPropertyTaxonomyQuery) GetMaxPropertyValuesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxPropertyValues.Get(), o.MaxPropertyValues.IsSet()
}

// HasMaxPropertyValues returns a boolean if a field has been set.
func (o *ActorsPropertyTaxonomyQuery) HasMaxPropertyValues() bool {
	if o != nil && o.MaxPropertyValues.IsSet() {
		return true
	}

	return false
}

// SetMaxPropertyValues gets a reference to the given NullableInt32 and assigns it to the MaxPropertyValues field.
func (o *ActorsPropertyTaxonomyQuery) SetMaxPropertyValues(v int32) {
	o.MaxPropertyValues.Set(&v)
}
// SetMaxPropertyValuesNil sets the value for MaxPropertyValues to be an explicit nil
func (o *ActorsPropertyTaxonomyQuery) SetMaxPropertyValuesNil() {
	o.MaxPropertyValues.Set(nil)
}

// UnsetMaxPropertyValues ensures that no value is present for MaxPropertyValues, not even an explicit nil
func (o *ActorsPropertyTaxonomyQuery) UnsetMaxPropertyValues() {
	o.MaxPropertyValues.Unset()
}

// GetModifiers returns the Modifiers field value if set, zero value otherwise.
func (o *ActorsPropertyTaxonomyQuery) GetModifiers() HogQLQueryModifiers {
	if o == nil || IsNil(o.Modifiers) {
		var ret HogQLQueryModifiers
		return ret
	}
	return *o.Modifiers
}

// GetModifiersOk returns a tuple with the Modifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActorsPropertyTaxonomyQuery) GetModifiersOk() (*HogQLQueryModifiers, bool) {
	if o == nil || IsNil(o.Modifiers) {
		return nil, false
	}
	return o.Modifiers, true
}

// HasModifiers returns a boolean if a field has been set.
func (o *ActorsPropertyTaxonomyQuery) HasModifiers() bool {
	if o != nil && !IsNil(o.Modifiers) {
		return true
	}

	return false
}

// SetModifiers gets a reference to the given HogQLQueryModifiers and assigns it to the Modifiers field.
func (o *ActorsPropertyTaxonomyQuery) SetModifiers(v HogQLQueryModifiers) {
	o.Modifiers = &v
}

// GetProperties returns the Properties field value
func (o *ActorsPropertyTaxonomyQuery) GetProperties() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *ActorsPropertyTaxonomyQuery) GetPropertiesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *ActorsPropertyTaxonomyQuery) SetProperties(v []string) {
	o.Properties = v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *ActorsPropertyTaxonomyQuery) GetResponse() ActorsPropertyTaxonomyQueryResponse {
	if o == nil || IsNil(o.Response) {
		var ret ActorsPropertyTaxonomyQueryResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActorsPropertyTaxonomyQuery) GetResponseOk() (*ActorsPropertyTaxonomyQueryResponse, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *ActorsPropertyTaxonomyQuery) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given ActorsPropertyTaxonomyQueryResponse and assigns it to the Response field.
func (o *ActorsPropertyTaxonomyQuery) SetResponse(v ActorsPropertyTaxonomyQueryResponse) {
	o.Response = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ActorsPropertyTaxonomyQuery) GetTags() QueryLogTags {
	if o == nil || IsNil(o.Tags) {
		var ret QueryLogTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActorsPropertyTaxonomyQuery) GetTagsOk() (*QueryLogTags, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ActorsPropertyTaxonomyQuery) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given QueryLogTags and assigns it to the Tags field.
func (o *ActorsPropertyTaxonomyQuery) SetTags(v QueryLogTags) {
	o.Tags = &v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActorsPropertyTaxonomyQuery) GetVersion() float32 {
	if o == nil || IsNil(o.Version.Get()) {
		var ret float32
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActorsPropertyTaxonomyQuery) GetVersionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *ActorsPropertyTaxonomyQuery) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableFloat32 and assigns it to the Version field.
func (o *ActorsPropertyTaxonomyQuery) SetVersion(v float32) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *ActorsPropertyTaxonomyQuery) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *ActorsPropertyTaxonomyQuery) UnsetVersion() {
	o.Version.Unset()
}

func (o ActorsPropertyTaxonomyQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActorsPropertyTaxonomyQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.GroupTypeIndex.IsSet() {
		toSerialize["groupTypeIndex"] = o.GroupTypeIndex.Get()
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if o.MaxPropertyValues.IsSet() {
		toSerialize["maxPropertyValues"] = o.MaxPropertyValues.Get()
	}
	if !IsNil(o.Modifiers) {
		toSerialize["modifiers"] = o.Modifiers
	}
	toSerialize["properties"] = o.Properties
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	return toSerialize, nil
}

func (o *ActorsPropertyTaxonomyQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActorsPropertyTaxonomyQuery := _ActorsPropertyTaxonomyQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActorsPropertyTaxonomyQuery)

	if err != nil {
		return err
	}

	*o = ActorsPropertyTaxonomyQuery(varActorsPropertyTaxonomyQuery)

	return err
}

type NullableActorsPropertyTaxonomyQuery struct {
	value *ActorsPropertyTaxonomyQuery
	isSet bool
}

func (v NullableActorsPropertyTaxonomyQuery) Get() *ActorsPropertyTaxonomyQuery {
	return v.value
}

func (v *NullableActorsPropertyTaxonomyQuery) Set(val *ActorsPropertyTaxonomyQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableActorsPropertyTaxonomyQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableActorsPropertyTaxonomyQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActorsPropertyTaxonomyQuery(val *ActorsPropertyTaxonomyQuery) *NullableActorsPropertyTaxonomyQuery {
	return &NullableActorsPropertyTaxonomyQuery{value: val, isSet: true}
}

func (v NullableActorsPropertyTaxonomyQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActorsPropertyTaxonomyQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


