/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"time"
)

// checks if the PatchedErrorTrackingRelease type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedErrorTrackingRelease{}

// PatchedErrorTrackingRelease struct for PatchedErrorTrackingRelease
type PatchedErrorTrackingRelease struct {
	Id *string `json:"id,omitempty"`
	HashId *string `json:"hash_id,omitempty"`
	TeamId *int32 `json:"team_id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Metadata interface{} `json:"metadata,omitempty"`
	Version *string `json:"version,omitempty"`
	Project *string `json:"project,omitempty"`
}

// NewPatchedErrorTrackingRelease instantiates a new PatchedErrorTrackingRelease object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedErrorTrackingRelease() *PatchedErrorTrackingRelease {
	this := PatchedErrorTrackingRelease{}
	return &this
}

// NewPatchedErrorTrackingReleaseWithDefaults instantiates a new PatchedErrorTrackingRelease object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedErrorTrackingReleaseWithDefaults() *PatchedErrorTrackingRelease {
	this := PatchedErrorTrackingRelease{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PatchedErrorTrackingRelease) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedErrorTrackingRelease) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PatchedErrorTrackingRelease) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PatchedErrorTrackingRelease) SetId(v string) {
	o.Id = &v
}

// GetHashId returns the HashId field value if set, zero value otherwise.
func (o *PatchedErrorTrackingRelease) GetHashId() string {
	if o == nil || IsNil(o.HashId) {
		var ret string
		return ret
	}
	return *o.HashId
}

// GetHashIdOk returns a tuple with the HashId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedErrorTrackingRelease) GetHashIdOk() (*string, bool) {
	if o == nil || IsNil(o.HashId) {
		return nil, false
	}
	return o.HashId, true
}

// HasHashId returns a boolean if a field has been set.
func (o *PatchedErrorTrackingRelease) HasHashId() bool {
	if o != nil && !IsNil(o.HashId) {
		return true
	}

	return false
}

// SetHashId gets a reference to the given string and assigns it to the HashId field.
func (o *PatchedErrorTrackingRelease) SetHashId(v string) {
	o.HashId = &v
}

// GetTeamId returns the TeamId field value if set, zero value otherwise.
func (o *PatchedErrorTrackingRelease) GetTeamId() int32 {
	if o == nil || IsNil(o.TeamId) {
		var ret int32
		return ret
	}
	return *o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedErrorTrackingRelease) GetTeamIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TeamId) {
		return nil, false
	}
	return o.TeamId, true
}

// HasTeamId returns a boolean if a field has been set.
func (o *PatchedErrorTrackingRelease) HasTeamId() bool {
	if o != nil && !IsNil(o.TeamId) {
		return true
	}

	return false
}

// SetTeamId gets a reference to the given int32 and assigns it to the TeamId field.
func (o *PatchedErrorTrackingRelease) SetTeamId(v int32) {
	o.TeamId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PatchedErrorTrackingRelease) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedErrorTrackingRelease) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PatchedErrorTrackingRelease) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *PatchedErrorTrackingRelease) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedErrorTrackingRelease) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedErrorTrackingRelease) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PatchedErrorTrackingRelease) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *PatchedErrorTrackingRelease) SetMetadata(v interface{}) {
	o.Metadata = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *PatchedErrorTrackingRelease) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedErrorTrackingRelease) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *PatchedErrorTrackingRelease) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *PatchedErrorTrackingRelease) SetVersion(v string) {
	o.Version = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *PatchedErrorTrackingRelease) GetProject() string {
	if o == nil || IsNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedErrorTrackingRelease) GetProjectOk() (*string, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *PatchedErrorTrackingRelease) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *PatchedErrorTrackingRelease) SetProject(v string) {
	o.Project = &v
}

func (o PatchedErrorTrackingRelease) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedErrorTrackingRelease) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.HashId) {
		toSerialize["hash_id"] = o.HashId
	}
	if !IsNil(o.TeamId) {
		toSerialize["team_id"] = o.TeamId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	return toSerialize, nil
}

type NullablePatchedErrorTrackingRelease struct {
	value *PatchedErrorTrackingRelease
	isSet bool
}

func (v NullablePatchedErrorTrackingRelease) Get() *PatchedErrorTrackingRelease {
	return v.value
}

func (v *NullablePatchedErrorTrackingRelease) Set(val *PatchedErrorTrackingRelease) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedErrorTrackingRelease) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedErrorTrackingRelease) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedErrorTrackingRelease(val *PatchedErrorTrackingRelease) *NullablePatchedErrorTrackingRelease {
	return &NullablePatchedErrorTrackingRelease{value: val, isSet: true}
}

func (v NullablePatchedErrorTrackingRelease) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedErrorTrackingRelease) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


