/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"fmt"
)

// ModelEnum * `events` - Events * `persons` - Persons * `sessions` - Sessions
type ModelEnum string

// List of ModelEnum
const (
	EVENTS ModelEnum = "events"
	PERSONS ModelEnum = "persons"
	SESSIONS ModelEnum = "sessions"
)

// All allowed values of ModelEnum enum
var AllowedModelEnumEnumValues = []ModelEnum{
	"events",
	"persons",
	"sessions",
}

func (v *ModelEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ModelEnum(value)
	for _, existing := range AllowedModelEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ModelEnum", value)
}

// NewModelEnumFromValue returns a pointer to a valid ModelEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModelEnumFromValue(v string) (*ModelEnum, error) {
	ev := ModelEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ModelEnum: valid values are %v", v, AllowedModelEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ModelEnum) IsValid() bool {
	for _, existing := range AllowedModelEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ModelEnum value
func (v ModelEnum) Ptr() *ModelEnum {
	return &v
}

type NullableModelEnum struct {
	value *ModelEnum
	isSet bool
}

func (v NullableModelEnum) Get() *ModelEnum {
	return v.value
}

func (v *NullableModelEnum) Set(val *ModelEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableModelEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableModelEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelEnum(val *ModelEnum) *NullableModelEnum {
	return &NullableModelEnum{value: val, isSet: true}
}

func (v NullableModelEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

