/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MinimalHedgehogConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MinimalHedgehogConfig{}

// MinimalHedgehogConfig struct for MinimalHedgehogConfig
type MinimalHedgehogConfig struct {
	Accessories []string `json:"accessories"`
	Color *HedgehogColorOptions `json:"color,omitempty"`
	UseAsProfile bool `json:"use_as_profile"`
}

type _MinimalHedgehogConfig MinimalHedgehogConfig

// NewMinimalHedgehogConfig instantiates a new MinimalHedgehogConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMinimalHedgehogConfig(accessories []string, useAsProfile bool) *MinimalHedgehogConfig {
	this := MinimalHedgehogConfig{}
	this.Accessories = accessories
	this.UseAsProfile = useAsProfile
	return &this
}

// NewMinimalHedgehogConfigWithDefaults instantiates a new MinimalHedgehogConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMinimalHedgehogConfigWithDefaults() *MinimalHedgehogConfig {
	this := MinimalHedgehogConfig{}
	return &this
}

// GetAccessories returns the Accessories field value
func (o *MinimalHedgehogConfig) GetAccessories() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Accessories
}

// GetAccessoriesOk returns a tuple with the Accessories field value
// and a boolean to check if the value has been set.
func (o *MinimalHedgehogConfig) GetAccessoriesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accessories, true
}

// SetAccessories sets field value
func (o *MinimalHedgehogConfig) SetAccessories(v []string) {
	o.Accessories = v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *MinimalHedgehogConfig) GetColor() HedgehogColorOptions {
	if o == nil || IsNil(o.Color) {
		var ret HedgehogColorOptions
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalHedgehogConfig) GetColorOk() (*HedgehogColorOptions, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *MinimalHedgehogConfig) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given HedgehogColorOptions and assigns it to the Color field.
func (o *MinimalHedgehogConfig) SetColor(v HedgehogColorOptions) {
	o.Color = &v
}

// GetUseAsProfile returns the UseAsProfile field value
func (o *MinimalHedgehogConfig) GetUseAsProfile() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UseAsProfile
}

// GetUseAsProfileOk returns a tuple with the UseAsProfile field value
// and a boolean to check if the value has been set.
func (o *MinimalHedgehogConfig) GetUseAsProfileOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UseAsProfile, true
}

// SetUseAsProfile sets field value
func (o *MinimalHedgehogConfig) SetUseAsProfile(v bool) {
	o.UseAsProfile = v
}

func (o MinimalHedgehogConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MinimalHedgehogConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accessories"] = o.Accessories
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	toSerialize["use_as_profile"] = o.UseAsProfile
	return toSerialize, nil
}

func (o *MinimalHedgehogConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accessories",
		"use_as_profile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMinimalHedgehogConfig := _MinimalHedgehogConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMinimalHedgehogConfig)

	if err != nil {
		return err
	}

	*o = MinimalHedgehogConfig(varMinimalHedgehogConfig)

	return err
}

type NullableMinimalHedgehogConfig struct {
	value *MinimalHedgehogConfig
	isSet bool
}

func (v NullableMinimalHedgehogConfig) Get() *MinimalHedgehogConfig {
	return v.value
}

func (v *NullableMinimalHedgehogConfig) Set(val *MinimalHedgehogConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableMinimalHedgehogConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableMinimalHedgehogConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMinimalHedgehogConfig(val *MinimalHedgehogConfig) *NullableMinimalHedgehogConfig {
	return &NullableMinimalHedgehogConfig{value: val, isSet: true}
}

func (v NullableMinimalHedgehogConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMinimalHedgehogConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


