/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebVitalsPathBreakdownQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebVitalsPathBreakdownQuery{}

// WebVitalsPathBreakdownQuery struct for WebVitalsPathBreakdownQuery
type WebVitalsPathBreakdownQuery struct {
	CompareFilter *CompareFilter `json:"compareFilter,omitempty"`
	ConversionGoal NullableConversiongoal1 `json:"conversionGoal,omitempty"`
	DateRange *DateRange `json:"dateRange,omitempty"`
	DoPathCleaning NullableBool `json:"doPathCleaning,omitempty"`
	FilterTestAccounts NullableBool `json:"filterTestAccounts,omitempty"`
	IncludeRevenue NullableBool `json:"includeRevenue,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Metric WebVitalsMetric `json:"metric"`
	Modifiers *HogQLQueryModifiers `json:"modifiers,omitempty"`
	OrderBy []string `json:"orderBy,omitempty"`
	Percentile WebVitalsPercentile `json:"percentile"`
	Properties []Properties2Inner1 `json:"properties"`
	Response *WebVitalsPathBreakdownQueryResponse `json:"response,omitempty"`
	Sampling *WebAnalyticsSampling `json:"sampling,omitempty"`
	Tags *QueryLogTags `json:"tags,omitempty"`
	Thresholds []float32 `json:"thresholds"`
	UseSessionsTable NullableBool `json:"useSessionsTable,omitempty"`
	// version of the node, used for schema migrations
	Version NullableFloat32 `json:"version,omitempty"`
}

type _WebVitalsPathBreakdownQuery WebVitalsPathBreakdownQuery

// NewWebVitalsPathBreakdownQuery instantiates a new WebVitalsPathBreakdownQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebVitalsPathBreakdownQuery(metric WebVitalsMetric, percentile WebVitalsPercentile, properties []Properties2Inner1, thresholds []float32) *WebVitalsPathBreakdownQuery {
	this := WebVitalsPathBreakdownQuery{}
	var conversionGoal Conversiongoal1 = null
	this.ConversionGoal = *NewNullableConversiongoal1(&conversionGoal)
	var kind string = "WebVitalsPathBreakdownQuery"
	this.Kind = &kind
	this.Metric = metric
	this.Percentile = percentile
	this.Properties = properties
	this.Thresholds = thresholds
	return &this
}

// NewWebVitalsPathBreakdownQueryWithDefaults instantiates a new WebVitalsPathBreakdownQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebVitalsPathBreakdownQueryWithDefaults() *WebVitalsPathBreakdownQuery {
	this := WebVitalsPathBreakdownQuery{}
	var conversionGoal Conversiongoal1 = null
	this.ConversionGoal = *NewNullableConversiongoal1(&conversionGoal)
	var kind string = "WebVitalsPathBreakdownQuery"
	this.Kind = &kind
	return &this
}

// GetCompareFilter returns the CompareFilter field value if set, zero value otherwise.
func (o *WebVitalsPathBreakdownQuery) GetCompareFilter() CompareFilter {
	if o == nil || IsNil(o.CompareFilter) {
		var ret CompareFilter
		return ret
	}
	return *o.CompareFilter
}

// GetCompareFilterOk returns a tuple with the CompareFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetCompareFilterOk() (*CompareFilter, bool) {
	if o == nil || IsNil(o.CompareFilter) {
		return nil, false
	}
	return o.CompareFilter, true
}

// HasCompareFilter returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasCompareFilter() bool {
	if o != nil && !IsNil(o.CompareFilter) {
		return true
	}

	return false
}

// SetCompareFilter gets a reference to the given CompareFilter and assigns it to the CompareFilter field.
func (o *WebVitalsPathBreakdownQuery) SetCompareFilter(v CompareFilter) {
	o.CompareFilter = &v
}

// GetConversionGoal returns the ConversionGoal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebVitalsPathBreakdownQuery) GetConversionGoal() Conversiongoal1 {
	if o == nil || IsNil(o.ConversionGoal.Get()) {
		var ret Conversiongoal1
		return ret
	}
	return *o.ConversionGoal.Get()
}

// GetConversionGoalOk returns a tuple with the ConversionGoal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebVitalsPathBreakdownQuery) GetConversionGoalOk() (*Conversiongoal1, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConversionGoal.Get(), o.ConversionGoal.IsSet()
}

// HasConversionGoal returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasConversionGoal() bool {
	if o != nil && o.ConversionGoal.IsSet() {
		return true
	}

	return false
}

// SetConversionGoal gets a reference to the given NullableConversiongoal1 and assigns it to the ConversionGoal field.
func (o *WebVitalsPathBreakdownQuery) SetConversionGoal(v Conversiongoal1) {
	o.ConversionGoal.Set(&v)
}
// SetConversionGoalNil sets the value for ConversionGoal to be an explicit nil
func (o *WebVitalsPathBreakdownQuery) SetConversionGoalNil() {
	o.ConversionGoal.Set(nil)
}

// UnsetConversionGoal ensures that no value is present for ConversionGoal, not even an explicit nil
func (o *WebVitalsPathBreakdownQuery) UnsetConversionGoal() {
	o.ConversionGoal.Unset()
}

// GetDateRange returns the DateRange field value if set, zero value otherwise.
func (o *WebVitalsPathBreakdownQuery) GetDateRange() DateRange {
	if o == nil || IsNil(o.DateRange) {
		var ret DateRange
		return ret
	}
	return *o.DateRange
}

// GetDateRangeOk returns a tuple with the DateRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetDateRangeOk() (*DateRange, bool) {
	if o == nil || IsNil(o.DateRange) {
		return nil, false
	}
	return o.DateRange, true
}

// HasDateRange returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasDateRange() bool {
	if o != nil && !IsNil(o.DateRange) {
		return true
	}

	return false
}

// SetDateRange gets a reference to the given DateRange and assigns it to the DateRange field.
func (o *WebVitalsPathBreakdownQuery) SetDateRange(v DateRange) {
	o.DateRange = &v
}

// GetDoPathCleaning returns the DoPathCleaning field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebVitalsPathBreakdownQuery) GetDoPathCleaning() bool {
	if o == nil || IsNil(o.DoPathCleaning.Get()) {
		var ret bool
		return ret
	}
	return *o.DoPathCleaning.Get()
}

// GetDoPathCleaningOk returns a tuple with the DoPathCleaning field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebVitalsPathBreakdownQuery) GetDoPathCleaningOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DoPathCleaning.Get(), o.DoPathCleaning.IsSet()
}

// HasDoPathCleaning returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasDoPathCleaning() bool {
	if o != nil && o.DoPathCleaning.IsSet() {
		return true
	}

	return false
}

// SetDoPathCleaning gets a reference to the given NullableBool and assigns it to the DoPathCleaning field.
func (o *WebVitalsPathBreakdownQuery) SetDoPathCleaning(v bool) {
	o.DoPathCleaning.Set(&v)
}
// SetDoPathCleaningNil sets the value for DoPathCleaning to be an explicit nil
func (o *WebVitalsPathBreakdownQuery) SetDoPathCleaningNil() {
	o.DoPathCleaning.Set(nil)
}

// UnsetDoPathCleaning ensures that no value is present for DoPathCleaning, not even an explicit nil
func (o *WebVitalsPathBreakdownQuery) UnsetDoPathCleaning() {
	o.DoPathCleaning.Unset()
}

// GetFilterTestAccounts returns the FilterTestAccounts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebVitalsPathBreakdownQuery) GetFilterTestAccounts() bool {
	if o == nil || IsNil(o.FilterTestAccounts.Get()) {
		var ret bool
		return ret
	}
	return *o.FilterTestAccounts.Get()
}

// GetFilterTestAccountsOk returns a tuple with the FilterTestAccounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebVitalsPathBreakdownQuery) GetFilterTestAccountsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.FilterTestAccounts.Get(), o.FilterTestAccounts.IsSet()
}

// HasFilterTestAccounts returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasFilterTestAccounts() bool {
	if o != nil && o.FilterTestAccounts.IsSet() {
		return true
	}

	return false
}

// SetFilterTestAccounts gets a reference to the given NullableBool and assigns it to the FilterTestAccounts field.
func (o *WebVitalsPathBreakdownQuery) SetFilterTestAccounts(v bool) {
	o.FilterTestAccounts.Set(&v)
}
// SetFilterTestAccountsNil sets the value for FilterTestAccounts to be an explicit nil
func (o *WebVitalsPathBreakdownQuery) SetFilterTestAccountsNil() {
	o.FilterTestAccounts.Set(nil)
}

// UnsetFilterTestAccounts ensures that no value is present for FilterTestAccounts, not even an explicit nil
func (o *WebVitalsPathBreakdownQuery) UnsetFilterTestAccounts() {
	o.FilterTestAccounts.Unset()
}

// GetIncludeRevenue returns the IncludeRevenue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebVitalsPathBreakdownQuery) GetIncludeRevenue() bool {
	if o == nil || IsNil(o.IncludeRevenue.Get()) {
		var ret bool
		return ret
	}
	return *o.IncludeRevenue.Get()
}

// GetIncludeRevenueOk returns a tuple with the IncludeRevenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebVitalsPathBreakdownQuery) GetIncludeRevenueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IncludeRevenue.Get(), o.IncludeRevenue.IsSet()
}

// HasIncludeRevenue returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasIncludeRevenue() bool {
	if o != nil && o.IncludeRevenue.IsSet() {
		return true
	}

	return false
}

// SetIncludeRevenue gets a reference to the given NullableBool and assigns it to the IncludeRevenue field.
func (o *WebVitalsPathBreakdownQuery) SetIncludeRevenue(v bool) {
	o.IncludeRevenue.Set(&v)
}
// SetIncludeRevenueNil sets the value for IncludeRevenue to be an explicit nil
func (o *WebVitalsPathBreakdownQuery) SetIncludeRevenueNil() {
	o.IncludeRevenue.Set(nil)
}

// UnsetIncludeRevenue ensures that no value is present for IncludeRevenue, not even an explicit nil
func (o *WebVitalsPathBreakdownQuery) UnsetIncludeRevenue() {
	o.IncludeRevenue.Unset()
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *WebVitalsPathBreakdownQuery) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *WebVitalsPathBreakdownQuery) SetKind(v string) {
	o.Kind = &v
}

// GetMetric returns the Metric field value
func (o *WebVitalsPathBreakdownQuery) GetMetric() WebVitalsMetric {
	if o == nil {
		var ret WebVitalsMetric
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetMetricOk() (*WebVitalsMetric, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *WebVitalsPathBreakdownQuery) SetMetric(v WebVitalsMetric) {
	o.Metric = v
}

// GetModifiers returns the Modifiers field value if set, zero value otherwise.
func (o *WebVitalsPathBreakdownQuery) GetModifiers() HogQLQueryModifiers {
	if o == nil || IsNil(o.Modifiers) {
		var ret HogQLQueryModifiers
		return ret
	}
	return *o.Modifiers
}

// GetModifiersOk returns a tuple with the Modifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetModifiersOk() (*HogQLQueryModifiers, bool) {
	if o == nil || IsNil(o.Modifiers) {
		return nil, false
	}
	return o.Modifiers, true
}

// HasModifiers returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasModifiers() bool {
	if o != nil && !IsNil(o.Modifiers) {
		return true
	}

	return false
}

// SetModifiers gets a reference to the given HogQLQueryModifiers and assigns it to the Modifiers field.
func (o *WebVitalsPathBreakdownQuery) SetModifiers(v HogQLQueryModifiers) {
	o.Modifiers = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebVitalsPathBreakdownQuery) GetOrderBy() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebVitalsPathBreakdownQuery) GetOrderByOk() ([]string, bool) {
	if o == nil || IsNil(o.OrderBy) {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasOrderBy() bool {
	if o != nil && !IsNil(o.OrderBy) {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given []string and assigns it to the OrderBy field.
func (o *WebVitalsPathBreakdownQuery) SetOrderBy(v []string) {
	o.OrderBy = v
}

// GetPercentile returns the Percentile field value
func (o *WebVitalsPathBreakdownQuery) GetPercentile() WebVitalsPercentile {
	if o == nil {
		var ret WebVitalsPercentile
		return ret
	}

	return o.Percentile
}

// GetPercentileOk returns a tuple with the Percentile field value
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetPercentileOk() (*WebVitalsPercentile, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percentile, true
}

// SetPercentile sets field value
func (o *WebVitalsPathBreakdownQuery) SetPercentile(v WebVitalsPercentile) {
	o.Percentile = v
}

// GetProperties returns the Properties field value
func (o *WebVitalsPathBreakdownQuery) GetProperties() []Properties2Inner1 {
	if o == nil {
		var ret []Properties2Inner1
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetPropertiesOk() ([]Properties2Inner1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *WebVitalsPathBreakdownQuery) SetProperties(v []Properties2Inner1) {
	o.Properties = v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *WebVitalsPathBreakdownQuery) GetResponse() WebVitalsPathBreakdownQueryResponse {
	if o == nil || IsNil(o.Response) {
		var ret WebVitalsPathBreakdownQueryResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetResponseOk() (*WebVitalsPathBreakdownQueryResponse, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given WebVitalsPathBreakdownQueryResponse and assigns it to the Response field.
func (o *WebVitalsPathBreakdownQuery) SetResponse(v WebVitalsPathBreakdownQueryResponse) {
	o.Response = &v
}

// GetSampling returns the Sampling field value if set, zero value otherwise.
func (o *WebVitalsPathBreakdownQuery) GetSampling() WebAnalyticsSampling {
	if o == nil || IsNil(o.Sampling) {
		var ret WebAnalyticsSampling
		return ret
	}
	return *o.Sampling
}

// GetSamplingOk returns a tuple with the Sampling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetSamplingOk() (*WebAnalyticsSampling, bool) {
	if o == nil || IsNil(o.Sampling) {
		return nil, false
	}
	return o.Sampling, true
}

// HasSampling returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasSampling() bool {
	if o != nil && !IsNil(o.Sampling) {
		return true
	}

	return false
}

// SetSampling gets a reference to the given WebAnalyticsSampling and assigns it to the Sampling field.
func (o *WebVitalsPathBreakdownQuery) SetSampling(v WebAnalyticsSampling) {
	o.Sampling = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *WebVitalsPathBreakdownQuery) GetTags() QueryLogTags {
	if o == nil || IsNil(o.Tags) {
		var ret QueryLogTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetTagsOk() (*QueryLogTags, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given QueryLogTags and assigns it to the Tags field.
func (o *WebVitalsPathBreakdownQuery) SetTags(v QueryLogTags) {
	o.Tags = &v
}

// GetThresholds returns the Thresholds field value
func (o *WebVitalsPathBreakdownQuery) GetThresholds() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.Thresholds
}

// GetThresholdsOk returns a tuple with the Thresholds field value
// and a boolean to check if the value has been set.
func (o *WebVitalsPathBreakdownQuery) GetThresholdsOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Thresholds, true
}

// SetThresholds sets field value
func (o *WebVitalsPathBreakdownQuery) SetThresholds(v []float32) {
	o.Thresholds = v
}

// GetUseSessionsTable returns the UseSessionsTable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebVitalsPathBreakdownQuery) GetUseSessionsTable() bool {
	if o == nil || IsNil(o.UseSessionsTable.Get()) {
		var ret bool
		return ret
	}
	return *o.UseSessionsTable.Get()
}

// GetUseSessionsTableOk returns a tuple with the UseSessionsTable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebVitalsPathBreakdownQuery) GetUseSessionsTableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.UseSessionsTable.Get(), o.UseSessionsTable.IsSet()
}

// HasUseSessionsTable returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasUseSessionsTable() bool {
	if o != nil && o.UseSessionsTable.IsSet() {
		return true
	}

	return false
}

// SetUseSessionsTable gets a reference to the given NullableBool and assigns it to the UseSessionsTable field.
func (o *WebVitalsPathBreakdownQuery) SetUseSessionsTable(v bool) {
	o.UseSessionsTable.Set(&v)
}
// SetUseSessionsTableNil sets the value for UseSessionsTable to be an explicit nil
func (o *WebVitalsPathBreakdownQuery) SetUseSessionsTableNil() {
	o.UseSessionsTable.Set(nil)
}

// UnsetUseSessionsTable ensures that no value is present for UseSessionsTable, not even an explicit nil
func (o *WebVitalsPathBreakdownQuery) UnsetUseSessionsTable() {
	o.UseSessionsTable.Unset()
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebVitalsPathBreakdownQuery) GetVersion() float32 {
	if o == nil || IsNil(o.Version.Get()) {
		var ret float32
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebVitalsPathBreakdownQuery) GetVersionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *WebVitalsPathBreakdownQuery) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableFloat32 and assigns it to the Version field.
func (o *WebVitalsPathBreakdownQuery) SetVersion(v float32) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *WebVitalsPathBreakdownQuery) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *WebVitalsPathBreakdownQuery) UnsetVersion() {
	o.Version.Unset()
}

func (o WebVitalsPathBreakdownQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebVitalsPathBreakdownQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompareFilter) {
		toSerialize["compareFilter"] = o.CompareFilter
	}
	if o.ConversionGoal.IsSet() {
		toSerialize["conversionGoal"] = o.ConversionGoal.Get()
	}
	if !IsNil(o.DateRange) {
		toSerialize["dateRange"] = o.DateRange
	}
	if o.DoPathCleaning.IsSet() {
		toSerialize["doPathCleaning"] = o.DoPathCleaning.Get()
	}
	if o.FilterTestAccounts.IsSet() {
		toSerialize["filterTestAccounts"] = o.FilterTestAccounts.Get()
	}
	if o.IncludeRevenue.IsSet() {
		toSerialize["includeRevenue"] = o.IncludeRevenue.Get()
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	toSerialize["metric"] = o.Metric
	if !IsNil(o.Modifiers) {
		toSerialize["modifiers"] = o.Modifiers
	}
	if o.OrderBy != nil {
		toSerialize["orderBy"] = o.OrderBy
	}
	toSerialize["percentile"] = o.Percentile
	toSerialize["properties"] = o.Properties
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if !IsNil(o.Sampling) {
		toSerialize["sampling"] = o.Sampling
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["thresholds"] = o.Thresholds
	if o.UseSessionsTable.IsSet() {
		toSerialize["useSessionsTable"] = o.UseSessionsTable.Get()
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	return toSerialize, nil
}

func (o *WebVitalsPathBreakdownQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metric",
		"percentile",
		"properties",
		"thresholds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebVitalsPathBreakdownQuery := _WebVitalsPathBreakdownQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebVitalsPathBreakdownQuery)

	if err != nil {
		return err
	}

	*o = WebVitalsPathBreakdownQuery(varWebVitalsPathBreakdownQuery)

	return err
}

type NullableWebVitalsPathBreakdownQuery struct {
	value *WebVitalsPathBreakdownQuery
	isSet bool
}

func (v NullableWebVitalsPathBreakdownQuery) Get() *WebVitalsPathBreakdownQuery {
	return v.value
}

func (v *NullableWebVitalsPathBreakdownQuery) Set(val *WebVitalsPathBreakdownQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableWebVitalsPathBreakdownQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableWebVitalsPathBreakdownQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebVitalsPathBreakdownQuery(val *WebVitalsPathBreakdownQuery) *NullableWebVitalsPathBreakdownQuery {
	return &NullableWebVitalsPathBreakdownQuery{value: val, isSet: true}
}

func (v NullableWebVitalsPathBreakdownQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebVitalsPathBreakdownQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


