/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the QueryStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryStatus{}

// QueryStatus struct for QueryStatus
type QueryStatus struct {
	// Whether the query is still running. Will be true if the query is complete, even if it errored. Either result or error will be set.
	Complete NullableBool `json:"complete,omitempty"`
	DashboardId NullableInt32 `json:"dashboard_id,omitempty"`
	// When did the query execution task finish (whether successfully or not).
	EndTime NullableTime `json:"end_time,omitempty"`
	// If the query failed, this will be set to true. More information can be found in the error_message field.
	Error NullableBool `json:"error,omitempty"`
	ErrorMessage NullableString `json:"error_message,omitempty"`
	ExpirationTime NullableTime `json:"expiration_time,omitempty"`
	Id string `json:"id"`
	InsightId NullableInt32 `json:"insight_id,omitempty"`
	Labels []string `json:"labels,omitempty"`
	// When was the query execution task picked up by a worker.
	PickupTime NullableTime `json:"pickup_time,omitempty"`
	// ONLY async queries use QueryStatus.
	QueryAsync *bool `json:"query_async,omitempty"`
	QueryProgress *ClickhouseQueryProgress `json:"query_progress,omitempty"`
	Results interface{} `json:"results,omitempty"`
	// When was query execution task enqueued.
	StartTime NullableTime `json:"start_time,omitempty"`
	TaskId NullableString `json:"task_id,omitempty"`
	TeamId int32 `json:"team_id"`
}

type _QueryStatus QueryStatus

// NewQueryStatus instantiates a new QueryStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryStatus(id string, teamId int32) *QueryStatus {
	this := QueryStatus{}
	var complete bool = false
	this.Complete = *NewNullableBool(&complete)
	var error_ bool = false
	this.Error = *NewNullableBool(&error_)
	this.Id = id
	var queryAsync bool = true
	this.QueryAsync = &queryAsync
	this.TeamId = teamId
	return &this
}

// NewQueryStatusWithDefaults instantiates a new QueryStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryStatusWithDefaults() *QueryStatus {
	this := QueryStatus{}
	var complete bool = false
	this.Complete = *NewNullableBool(&complete)
	var error_ bool = false
	this.Error = *NewNullableBool(&error_)
	var queryAsync bool = true
	this.QueryAsync = &queryAsync
	return &this
}

// GetComplete returns the Complete field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetComplete() bool {
	if o == nil || IsNil(o.Complete.Get()) {
		var ret bool
		return ret
	}
	return *o.Complete.Get()
}

// GetCompleteOk returns a tuple with the Complete field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetCompleteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Complete.Get(), o.Complete.IsSet()
}

// HasComplete returns a boolean if a field has been set.
func (o *QueryStatus) HasComplete() bool {
	if o != nil && o.Complete.IsSet() {
		return true
	}

	return false
}

// SetComplete gets a reference to the given NullableBool and assigns it to the Complete field.
func (o *QueryStatus) SetComplete(v bool) {
	o.Complete.Set(&v)
}
// SetCompleteNil sets the value for Complete to be an explicit nil
func (o *QueryStatus) SetCompleteNil() {
	o.Complete.Set(nil)
}

// UnsetComplete ensures that no value is present for Complete, not even an explicit nil
func (o *QueryStatus) UnsetComplete() {
	o.Complete.Unset()
}

// GetDashboardId returns the DashboardId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetDashboardId() int32 {
	if o == nil || IsNil(o.DashboardId.Get()) {
		var ret int32
		return ret
	}
	return *o.DashboardId.Get()
}

// GetDashboardIdOk returns a tuple with the DashboardId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetDashboardIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DashboardId.Get(), o.DashboardId.IsSet()
}

// HasDashboardId returns a boolean if a field has been set.
func (o *QueryStatus) HasDashboardId() bool {
	if o != nil && o.DashboardId.IsSet() {
		return true
	}

	return false
}

// SetDashboardId gets a reference to the given NullableInt32 and assigns it to the DashboardId field.
func (o *QueryStatus) SetDashboardId(v int32) {
	o.DashboardId.Set(&v)
}
// SetDashboardIdNil sets the value for DashboardId to be an explicit nil
func (o *QueryStatus) SetDashboardIdNil() {
	o.DashboardId.Set(nil)
}

// UnsetDashboardId ensures that no value is present for DashboardId, not even an explicit nil
func (o *QueryStatus) UnsetDashboardId() {
	o.DashboardId.Unset()
}

// GetEndTime returns the EndTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetEndTime() time.Time {
	if o == nil || IsNil(o.EndTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndTime.Get()
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndTime.Get(), o.EndTime.IsSet()
}

// HasEndTime returns a boolean if a field has been set.
func (o *QueryStatus) HasEndTime() bool {
	if o != nil && o.EndTime.IsSet() {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given NullableTime and assigns it to the EndTime field.
func (o *QueryStatus) SetEndTime(v time.Time) {
	o.EndTime.Set(&v)
}
// SetEndTimeNil sets the value for EndTime to be an explicit nil
func (o *QueryStatus) SetEndTimeNil() {
	o.EndTime.Set(nil)
}

// UnsetEndTime ensures that no value is present for EndTime, not even an explicit nil
func (o *QueryStatus) UnsetEndTime() {
	o.EndTime.Unset()
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetError() bool {
	if o == nil || IsNil(o.Error.Get()) {
		var ret bool
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetErrorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *QueryStatus) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableBool and assigns it to the Error field.
func (o *QueryStatus) SetError(v bool) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *QueryStatus) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *QueryStatus) UnsetError() {
	o.Error.Unset()
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *QueryStatus) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *QueryStatus) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *QueryStatus) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *QueryStatus) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetExpirationTime returns the ExpirationTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetExpirationTime() time.Time {
	if o == nil || IsNil(o.ExpirationTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpirationTime.Get()
}

// GetExpirationTimeOk returns a tuple with the ExpirationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetExpirationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpirationTime.Get(), o.ExpirationTime.IsSet()
}

// HasExpirationTime returns a boolean if a field has been set.
func (o *QueryStatus) HasExpirationTime() bool {
	if o != nil && o.ExpirationTime.IsSet() {
		return true
	}

	return false
}

// SetExpirationTime gets a reference to the given NullableTime and assigns it to the ExpirationTime field.
func (o *QueryStatus) SetExpirationTime(v time.Time) {
	o.ExpirationTime.Set(&v)
}
// SetExpirationTimeNil sets the value for ExpirationTime to be an explicit nil
func (o *QueryStatus) SetExpirationTimeNil() {
	o.ExpirationTime.Set(nil)
}

// UnsetExpirationTime ensures that no value is present for ExpirationTime, not even an explicit nil
func (o *QueryStatus) UnsetExpirationTime() {
	o.ExpirationTime.Unset()
}

// GetId returns the Id field value
func (o *QueryStatus) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QueryStatus) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QueryStatus) SetId(v string) {
	o.Id = v
}

// GetInsightId returns the InsightId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetInsightId() int32 {
	if o == nil || IsNil(o.InsightId.Get()) {
		var ret int32
		return ret
	}
	return *o.InsightId.Get()
}

// GetInsightIdOk returns a tuple with the InsightId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetInsightIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.InsightId.Get(), o.InsightId.IsSet()
}

// HasInsightId returns a boolean if a field has been set.
func (o *QueryStatus) HasInsightId() bool {
	if o != nil && o.InsightId.IsSet() {
		return true
	}

	return false
}

// SetInsightId gets a reference to the given NullableInt32 and assigns it to the InsightId field.
func (o *QueryStatus) SetInsightId(v int32) {
	o.InsightId.Set(&v)
}
// SetInsightIdNil sets the value for InsightId to be an explicit nil
func (o *QueryStatus) SetInsightIdNil() {
	o.InsightId.Set(nil)
}

// UnsetInsightId ensures that no value is present for InsightId, not even an explicit nil
func (o *QueryStatus) UnsetInsightId() {
	o.InsightId.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetLabels() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *QueryStatus) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *QueryStatus) SetLabels(v []string) {
	o.Labels = v
}

// GetPickupTime returns the PickupTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetPickupTime() time.Time {
	if o == nil || IsNil(o.PickupTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PickupTime.Get()
}

// GetPickupTimeOk returns a tuple with the PickupTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetPickupTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PickupTime.Get(), o.PickupTime.IsSet()
}

// HasPickupTime returns a boolean if a field has been set.
func (o *QueryStatus) HasPickupTime() bool {
	if o != nil && o.PickupTime.IsSet() {
		return true
	}

	return false
}

// SetPickupTime gets a reference to the given NullableTime and assigns it to the PickupTime field.
func (o *QueryStatus) SetPickupTime(v time.Time) {
	o.PickupTime.Set(&v)
}
// SetPickupTimeNil sets the value for PickupTime to be an explicit nil
func (o *QueryStatus) SetPickupTimeNil() {
	o.PickupTime.Set(nil)
}

// UnsetPickupTime ensures that no value is present for PickupTime, not even an explicit nil
func (o *QueryStatus) UnsetPickupTime() {
	o.PickupTime.Unset()
}

// GetQueryAsync returns the QueryAsync field value if set, zero value otherwise.
func (o *QueryStatus) GetQueryAsync() bool {
	if o == nil || IsNil(o.QueryAsync) {
		var ret bool
		return ret
	}
	return *o.QueryAsync
}

// GetQueryAsyncOk returns a tuple with the QueryAsync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryStatus) GetQueryAsyncOk() (*bool, bool) {
	if o == nil || IsNil(o.QueryAsync) {
		return nil, false
	}
	return o.QueryAsync, true
}

// HasQueryAsync returns a boolean if a field has been set.
func (o *QueryStatus) HasQueryAsync() bool {
	if o != nil && !IsNil(o.QueryAsync) {
		return true
	}

	return false
}

// SetQueryAsync gets a reference to the given bool and assigns it to the QueryAsync field.
func (o *QueryStatus) SetQueryAsync(v bool) {
	o.QueryAsync = &v
}

// GetQueryProgress returns the QueryProgress field value if set, zero value otherwise.
func (o *QueryStatus) GetQueryProgress() ClickhouseQueryProgress {
	if o == nil || IsNil(o.QueryProgress) {
		var ret ClickhouseQueryProgress
		return ret
	}
	return *o.QueryProgress
}

// GetQueryProgressOk returns a tuple with the QueryProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryStatus) GetQueryProgressOk() (*ClickhouseQueryProgress, bool) {
	if o == nil || IsNil(o.QueryProgress) {
		return nil, false
	}
	return o.QueryProgress, true
}

// HasQueryProgress returns a boolean if a field has been set.
func (o *QueryStatus) HasQueryProgress() bool {
	if o != nil && !IsNil(o.QueryProgress) {
		return true
	}

	return false
}

// SetQueryProgress gets a reference to the given ClickhouseQueryProgress and assigns it to the QueryProgress field.
func (o *QueryStatus) SetQueryProgress(v ClickhouseQueryProgress) {
	o.QueryProgress = &v
}

// GetResults returns the Results field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetResults() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetResultsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return &o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *QueryStatus) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given interface{} and assigns it to the Results field.
func (o *QueryStatus) SetResults(v interface{}) {
	o.Results = v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetStartTime() time.Time {
	if o == nil || IsNil(o.StartTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartTime.Get()
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartTime.Get(), o.StartTime.IsSet()
}

// HasStartTime returns a boolean if a field has been set.
func (o *QueryStatus) HasStartTime() bool {
	if o != nil && o.StartTime.IsSet() {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given NullableTime and assigns it to the StartTime field.
func (o *QueryStatus) SetStartTime(v time.Time) {
	o.StartTime.Set(&v)
}
// SetStartTimeNil sets the value for StartTime to be an explicit nil
func (o *QueryStatus) SetStartTimeNil() {
	o.StartTime.Set(nil)
}

// UnsetStartTime ensures that no value is present for StartTime, not even an explicit nil
func (o *QueryStatus) UnsetStartTime() {
	o.StartTime.Unset()
}

// GetTaskId returns the TaskId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryStatus) GetTaskId() string {
	if o == nil || IsNil(o.TaskId.Get()) {
		var ret string
		return ret
	}
	return *o.TaskId.Get()
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryStatus) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaskId.Get(), o.TaskId.IsSet()
}

// HasTaskId returns a boolean if a field has been set.
func (o *QueryStatus) HasTaskId() bool {
	if o != nil && o.TaskId.IsSet() {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given NullableString and assigns it to the TaskId field.
func (o *QueryStatus) SetTaskId(v string) {
	o.TaskId.Set(&v)
}
// SetTaskIdNil sets the value for TaskId to be an explicit nil
func (o *QueryStatus) SetTaskIdNil() {
	o.TaskId.Set(nil)
}

// UnsetTaskId ensures that no value is present for TaskId, not even an explicit nil
func (o *QueryStatus) UnsetTaskId() {
	o.TaskId.Unset()
}

// GetTeamId returns the TeamId field value
func (o *QueryStatus) GetTeamId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value
// and a boolean to check if the value has been set.
func (o *QueryStatus) GetTeamIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamId, true
}

// SetTeamId sets field value
func (o *QueryStatus) SetTeamId(v int32) {
	o.TeamId = v
}

func (o QueryStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Complete.IsSet() {
		toSerialize["complete"] = o.Complete.Get()
	}
	if o.DashboardId.IsSet() {
		toSerialize["dashboard_id"] = o.DashboardId.Get()
	}
	if o.EndTime.IsSet() {
		toSerialize["end_time"] = o.EndTime.Get()
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.ErrorMessage.IsSet() {
		toSerialize["error_message"] = o.ErrorMessage.Get()
	}
	if o.ExpirationTime.IsSet() {
		toSerialize["expiration_time"] = o.ExpirationTime.Get()
	}
	toSerialize["id"] = o.Id
	if o.InsightId.IsSet() {
		toSerialize["insight_id"] = o.InsightId.Get()
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.PickupTime.IsSet() {
		toSerialize["pickup_time"] = o.PickupTime.Get()
	}
	if !IsNil(o.QueryAsync) {
		toSerialize["query_async"] = o.QueryAsync
	}
	if !IsNil(o.QueryProgress) {
		toSerialize["query_progress"] = o.QueryProgress
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	if o.StartTime.IsSet() {
		toSerialize["start_time"] = o.StartTime.Get()
	}
	if o.TaskId.IsSet() {
		toSerialize["task_id"] = o.TaskId.Get()
	}
	toSerialize["team_id"] = o.TeamId
	return toSerialize, nil
}

func (o *QueryStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"team_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryStatus := _QueryStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryStatus)

	if err != nil {
		return err
	}

	*o = QueryStatus(varQueryStatus)

	return err
}

type NullableQueryStatus struct {
	value *QueryStatus
	isSet bool
}

func (v NullableQueryStatus) Get() *QueryStatus {
	return v.value
}

func (v *NullableQueryStatus) Set(val *QueryStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryStatus(val *QueryStatus) *NullableQueryStatus {
	return &NullableQueryStatus{value: val, isSet: true}
}

func (v NullableQueryStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


