/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserBasic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserBasic{}

// UserBasic struct for UserBasic
type UserBasic struct {
	Id int32 `json:"id"`
	Uuid string `json:"uuid"`
	DistinctId NullableString `json:"distinct_id,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Email string `json:"email"`
	IsEmailVerified NullableBool `json:"is_email_verified,omitempty"`
	HedgehogConfig map[string]interface{} `json:"hedgehog_config"`
	RoleAtOrganization NullableString `json:"role_at_organization,omitempty"`
}

type _UserBasic UserBasic

// NewUserBasic instantiates a new UserBasic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserBasic(id int32, uuid string, email string, hedgehogConfig map[string]interface{}) *UserBasic {
	this := UserBasic{}
	this.Id = id
	this.Uuid = uuid
	this.Email = email
	this.HedgehogConfig = hedgehogConfig
	return &this
}

// NewUserBasicWithDefaults instantiates a new UserBasic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserBasicWithDefaults() *UserBasic {
	this := UserBasic{}
	return &this
}

// GetId returns the Id field value
func (o *UserBasic) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserBasic) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserBasic) SetId(v int32) {
	o.Id = v
}

// GetUuid returns the Uuid field value
func (o *UserBasic) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *UserBasic) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *UserBasic) SetUuid(v string) {
	o.Uuid = v
}

// GetDistinctId returns the DistinctId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserBasic) GetDistinctId() string {
	if o == nil || IsNil(o.DistinctId.Get()) {
		var ret string
		return ret
	}
	return *o.DistinctId.Get()
}

// GetDistinctIdOk returns a tuple with the DistinctId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserBasic) GetDistinctIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DistinctId.Get(), o.DistinctId.IsSet()
}

// HasDistinctId returns a boolean if a field has been set.
func (o *UserBasic) HasDistinctId() bool {
	if o != nil && o.DistinctId.IsSet() {
		return true
	}

	return false
}

// SetDistinctId gets a reference to the given NullableString and assigns it to the DistinctId field.
func (o *UserBasic) SetDistinctId(v string) {
	o.DistinctId.Set(&v)
}
// SetDistinctIdNil sets the value for DistinctId to be an explicit nil
func (o *UserBasic) SetDistinctIdNil() {
	o.DistinctId.Set(nil)
}

// UnsetDistinctId ensures that no value is present for DistinctId, not even an explicit nil
func (o *UserBasic) UnsetDistinctId() {
	o.DistinctId.Unset()
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserBasic) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserBasic) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserBasic) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserBasic) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserBasic) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserBasic) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserBasic) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserBasic) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value
func (o *UserBasic) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserBasic) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserBasic) SetEmail(v string) {
	o.Email = v
}

// GetIsEmailVerified returns the IsEmailVerified field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserBasic) GetIsEmailVerified() bool {
	if o == nil || IsNil(o.IsEmailVerified.Get()) {
		var ret bool
		return ret
	}
	return *o.IsEmailVerified.Get()
}

// GetIsEmailVerifiedOk returns a tuple with the IsEmailVerified field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserBasic) GetIsEmailVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsEmailVerified.Get(), o.IsEmailVerified.IsSet()
}

// HasIsEmailVerified returns a boolean if a field has been set.
func (o *UserBasic) HasIsEmailVerified() bool {
	if o != nil && o.IsEmailVerified.IsSet() {
		return true
	}

	return false
}

// SetIsEmailVerified gets a reference to the given NullableBool and assigns it to the IsEmailVerified field.
func (o *UserBasic) SetIsEmailVerified(v bool) {
	o.IsEmailVerified.Set(&v)
}
// SetIsEmailVerifiedNil sets the value for IsEmailVerified to be an explicit nil
func (o *UserBasic) SetIsEmailVerifiedNil() {
	o.IsEmailVerified.Set(nil)
}

// UnsetIsEmailVerified ensures that no value is present for IsEmailVerified, not even an explicit nil
func (o *UserBasic) UnsetIsEmailVerified() {
	o.IsEmailVerified.Unset()
}

// GetHedgehogConfig returns the HedgehogConfig field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *UserBasic) GetHedgehogConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.HedgehogConfig
}

// GetHedgehogConfigOk returns a tuple with the HedgehogConfig field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserBasic) GetHedgehogConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.HedgehogConfig) {
		return map[string]interface{}{}, false
	}
	return o.HedgehogConfig, true
}

// SetHedgehogConfig sets field value
func (o *UserBasic) SetHedgehogConfig(v map[string]interface{}) {
	o.HedgehogConfig = v
}

// GetRoleAtOrganization returns the RoleAtOrganization field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserBasic) GetRoleAtOrganization() string {
	if o == nil || IsNil(o.RoleAtOrganization.Get()) {
		var ret string
		return ret
	}
	return *o.RoleAtOrganization.Get()
}

// GetRoleAtOrganizationOk returns a tuple with the RoleAtOrganization field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserBasic) GetRoleAtOrganizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoleAtOrganization.Get(), o.RoleAtOrganization.IsSet()
}

// HasRoleAtOrganization returns a boolean if a field has been set.
func (o *UserBasic) HasRoleAtOrganization() bool {
	if o != nil && o.RoleAtOrganization.IsSet() {
		return true
	}

	return false
}

// SetRoleAtOrganization gets a reference to the given NullableString and assigns it to the RoleAtOrganization field.
func (o *UserBasic) SetRoleAtOrganization(v string) {
	o.RoleAtOrganization.Set(&v)
}
// SetRoleAtOrganizationNil sets the value for RoleAtOrganization to be an explicit nil
func (o *UserBasic) SetRoleAtOrganizationNil() {
	o.RoleAtOrganization.Set(nil)
}

// UnsetRoleAtOrganization ensures that no value is present for RoleAtOrganization, not even an explicit nil
func (o *UserBasic) UnsetRoleAtOrganization() {
	o.RoleAtOrganization.Unset()
}

func (o UserBasic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserBasic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["uuid"] = o.Uuid
	if o.DistinctId.IsSet() {
		toSerialize["distinct_id"] = o.DistinctId.Get()
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	toSerialize["email"] = o.Email
	if o.IsEmailVerified.IsSet() {
		toSerialize["is_email_verified"] = o.IsEmailVerified.Get()
	}
	if o.HedgehogConfig != nil {
		toSerialize["hedgehog_config"] = o.HedgehogConfig
	}
	if o.RoleAtOrganization.IsSet() {
		toSerialize["role_at_organization"] = o.RoleAtOrganization.Get()
	}
	return toSerialize, nil
}

func (o *UserBasic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"uuid",
		"email",
		"hedgehog_config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserBasic := _UserBasic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserBasic)

	if err != nil {
		return err
	}

	*o = UserBasic(varUserBasic)

	return err
}

type NullableUserBasic struct {
	value *UserBasic
	isSet bool
}

func (v NullableUserBasic) Get() *UserBasic {
	return v.value
}

func (v *NullableUserBasic) Set(val *UserBasic) {
	v.value = val
	v.isSet = true
}

func (v NullableUserBasic) IsSet() bool {
	return v.isSet
}

func (v *NullableUserBasic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserBasic(val *UserBasic) *NullableUserBasic {
	return &NullableUserBasic{value: val, isSet: true}
}

func (v NullableUserBasic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserBasic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


