/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"fmt"
)

// OrderBy1 the model 'OrderBy1'
type OrderBy1 string

// List of OrderBy1
const (
	LAST_SEEN OrderBy1 = "last_seen"
	FIRST_SEEN OrderBy1 = "first_seen"
	OCCURRENCES OrderBy1 = "occurrences"
	USERS OrderBy1 = "users"
	SESSIONS OrderBy1 = "sessions"
	REVENUE OrderBy1 = "revenue"
)

// All allowed values of OrderBy1 enum
var AllowedOrderBy1EnumValues = []OrderBy1{
	"last_seen",
	"first_seen",
	"occurrences",
	"users",
	"sessions",
	"revenue",
}

func (v *OrderBy1) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrderBy1(value)
	for _, existing := range AllowedOrderBy1EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrderBy1", value)
}

// NewOrderBy1FromValue returns a pointer to a valid OrderBy1
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOrderBy1FromValue(v string) (*OrderBy1, error) {
	ev := OrderBy1(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OrderBy1: valid values are %v", v, AllowedOrderBy1EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OrderBy1) IsValid() bool {
	for _, existing := range AllowedOrderBy1EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OrderBy1 value
func (v OrderBy1) Ptr() *OrderBy1 {
	return &v
}

type NullableOrderBy1 struct {
	value *OrderBy1
	isSet bool
}

func (v NullableOrderBy1) Get() *OrderBy1 {
	return v.value
}

func (v *NullableOrderBy1) Set(val *OrderBy1) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderBy1) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderBy1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderBy1(val *OrderBy1) *NullableOrderBy1 {
	return &NullableOrderBy1{value: val, isSet: true}
}

func (v NullableOrderBy1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderBy1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

