/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
)

// checks if the PatchedErrorTrackingSuppressionRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedErrorTrackingSuppressionRule{}

// PatchedErrorTrackingSuppressionRule struct for PatchedErrorTrackingSuppressionRule
type PatchedErrorTrackingSuppressionRule struct {
	Id *string `json:"id,omitempty"`
	Filters interface{} `json:"filters,omitempty"`
	OrderKey *int32 `json:"order_key,omitempty"`
}

// NewPatchedErrorTrackingSuppressionRule instantiates a new PatchedErrorTrackingSuppressionRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedErrorTrackingSuppressionRule() *PatchedErrorTrackingSuppressionRule {
	this := PatchedErrorTrackingSuppressionRule{}
	return &this
}

// NewPatchedErrorTrackingSuppressionRuleWithDefaults instantiates a new PatchedErrorTrackingSuppressionRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedErrorTrackingSuppressionRuleWithDefaults() *PatchedErrorTrackingSuppressionRule {
	this := PatchedErrorTrackingSuppressionRule{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PatchedErrorTrackingSuppressionRule) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedErrorTrackingSuppressionRule) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PatchedErrorTrackingSuppressionRule) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PatchedErrorTrackingSuppressionRule) SetId(v string) {
	o.Id = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedErrorTrackingSuppressionRule) GetFilters() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedErrorTrackingSuppressionRule) GetFiltersOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return &o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *PatchedErrorTrackingSuppressionRule) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given interface{} and assigns it to the Filters field.
func (o *PatchedErrorTrackingSuppressionRule) SetFilters(v interface{}) {
	o.Filters = v
}

// GetOrderKey returns the OrderKey field value if set, zero value otherwise.
func (o *PatchedErrorTrackingSuppressionRule) GetOrderKey() int32 {
	if o == nil || IsNil(o.OrderKey) {
		var ret int32
		return ret
	}
	return *o.OrderKey
}

// GetOrderKeyOk returns a tuple with the OrderKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedErrorTrackingSuppressionRule) GetOrderKeyOk() (*int32, bool) {
	if o == nil || IsNil(o.OrderKey) {
		return nil, false
	}
	return o.OrderKey, true
}

// HasOrderKey returns a boolean if a field has been set.
func (o *PatchedErrorTrackingSuppressionRule) HasOrderKey() bool {
	if o != nil && !IsNil(o.OrderKey) {
		return true
	}

	return false
}

// SetOrderKey gets a reference to the given int32 and assigns it to the OrderKey field.
func (o *PatchedErrorTrackingSuppressionRule) SetOrderKey(v int32) {
	o.OrderKey = &v
}

func (o PatchedErrorTrackingSuppressionRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedErrorTrackingSuppressionRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Filters != nil {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.OrderKey) {
		toSerialize["order_key"] = o.OrderKey
	}
	return toSerialize, nil
}

type NullablePatchedErrorTrackingSuppressionRule struct {
	value *PatchedErrorTrackingSuppressionRule
	isSet bool
}

func (v NullablePatchedErrorTrackingSuppressionRule) Get() *PatchedErrorTrackingSuppressionRule {
	return v.value
}

func (v *NullablePatchedErrorTrackingSuppressionRule) Set(val *PatchedErrorTrackingSuppressionRule) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedErrorTrackingSuppressionRule) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedErrorTrackingSuppressionRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedErrorTrackingSuppressionRule(val *PatchedErrorTrackingSuppressionRule) *NullablePatchedErrorTrackingSuppressionRule {
	return &NullablePatchedErrorTrackingSuppressionRule{value: val, isSet: true}
}

func (v NullablePatchedErrorTrackingSuppressionRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedErrorTrackingSuppressionRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


