/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"fmt"
)

// EffectivePrivilegeLevelEnum the model 'EffectivePrivilegeLevelEnum'
type EffectivePrivilegeLevelEnum int32

// List of EffectivePrivilegeLevelEnum
const (
	_21 EffectivePrivilegeLevelEnum = 21
	_37 EffectivePrivilegeLevelEnum = 37
)

// All allowed values of EffectivePrivilegeLevelEnum enum
var AllowedEffectivePrivilegeLevelEnumEnumValues = []EffectivePrivilegeLevelEnum{
	21,
	37,
}

func (v *EffectivePrivilegeLevelEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EffectivePrivilegeLevelEnum(value)
	for _, existing := range AllowedEffectivePrivilegeLevelEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EffectivePrivilegeLevelEnum", value)
}

// NewEffectivePrivilegeLevelEnumFromValue returns a pointer to a valid EffectivePrivilegeLevelEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEffectivePrivilegeLevelEnumFromValue(v int32) (*EffectivePrivilegeLevelEnum, error) {
	ev := EffectivePrivilegeLevelEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EffectivePrivilegeLevelEnum: valid values are %v", v, AllowedEffectivePrivilegeLevelEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EffectivePrivilegeLevelEnum) IsValid() bool {
	for _, existing := range AllowedEffectivePrivilegeLevelEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EffectivePrivilegeLevelEnum value
func (v EffectivePrivilegeLevelEnum) Ptr() *EffectivePrivilegeLevelEnum {
	return &v
}

type NullableEffectivePrivilegeLevelEnum struct {
	value *EffectivePrivilegeLevelEnum
	isSet bool
}

func (v NullableEffectivePrivilegeLevelEnum) Get() *EffectivePrivilegeLevelEnum {
	return v.value
}

func (v *NullableEffectivePrivilegeLevelEnum) Set(val *EffectivePrivilegeLevelEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableEffectivePrivilegeLevelEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableEffectivePrivilegeLevelEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEffectivePrivilegeLevelEnum(val *EffectivePrivilegeLevelEnum) *NullableEffectivePrivilegeLevelEnum {
	return &NullableEffectivePrivilegeLevelEnum{value: val, isSet: true}
}

func (v NullableEffectivePrivilegeLevelEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEffectivePrivilegeLevelEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

