/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventTaxonomyQueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventTaxonomyQueryResponse{}

// EventTaxonomyQueryResponse struct for EventTaxonomyQueryResponse
type EventTaxonomyQueryResponse struct {
	// Query error. Returned only if 'explain' or `modifiers.debug` is true. Throws an error otherwise.
	Error NullableString `json:"error,omitempty"`
	// Generated HogQL query.
	Hogql NullableString `json:"hogql,omitempty"`
	Modifiers *HogQLQueryModifiers `json:"modifiers,omitempty"`
	QueryStatus *QueryStatus `json:"query_status,omitempty"`
	ResolvedDateRange *ResolvedDateRangeResponse `json:"resolved_date_range,omitempty"`
	Results []EventTaxonomyItem `json:"results"`
	// Measured timings for different parts of the query generation process
	Timings []QueryTiming `json:"timings,omitempty"`
}

type _EventTaxonomyQueryResponse EventTaxonomyQueryResponse

// NewEventTaxonomyQueryResponse instantiates a new EventTaxonomyQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventTaxonomyQueryResponse(results []EventTaxonomyItem) *EventTaxonomyQueryResponse {
	this := EventTaxonomyQueryResponse{}
	this.Results = results
	return &this
}

// NewEventTaxonomyQueryResponseWithDefaults instantiates a new EventTaxonomyQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventTaxonomyQueryResponseWithDefaults() *EventTaxonomyQueryResponse {
	this := EventTaxonomyQueryResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EventTaxonomyQueryResponse) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventTaxonomyQueryResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *EventTaxonomyQueryResponse) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *EventTaxonomyQueryResponse) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *EventTaxonomyQueryResponse) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *EventTaxonomyQueryResponse) UnsetError() {
	o.Error.Unset()
}

// GetHogql returns the Hogql field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EventTaxonomyQueryResponse) GetHogql() string {
	if o == nil || IsNil(o.Hogql.Get()) {
		var ret string
		return ret
	}
	return *o.Hogql.Get()
}

// GetHogqlOk returns a tuple with the Hogql field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventTaxonomyQueryResponse) GetHogqlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hogql.Get(), o.Hogql.IsSet()
}

// HasHogql returns a boolean if a field has been set.
func (o *EventTaxonomyQueryResponse) HasHogql() bool {
	if o != nil && o.Hogql.IsSet() {
		return true
	}

	return false
}

// SetHogql gets a reference to the given NullableString and assigns it to the Hogql field.
func (o *EventTaxonomyQueryResponse) SetHogql(v string) {
	o.Hogql.Set(&v)
}
// SetHogqlNil sets the value for Hogql to be an explicit nil
func (o *EventTaxonomyQueryResponse) SetHogqlNil() {
	o.Hogql.Set(nil)
}

// UnsetHogql ensures that no value is present for Hogql, not even an explicit nil
func (o *EventTaxonomyQueryResponse) UnsetHogql() {
	o.Hogql.Unset()
}

// GetModifiers returns the Modifiers field value if set, zero value otherwise.
func (o *EventTaxonomyQueryResponse) GetModifiers() HogQLQueryModifiers {
	if o == nil || IsNil(o.Modifiers) {
		var ret HogQLQueryModifiers
		return ret
	}
	return *o.Modifiers
}

// GetModifiersOk returns a tuple with the Modifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventTaxonomyQueryResponse) GetModifiersOk() (*HogQLQueryModifiers, bool) {
	if o == nil || IsNil(o.Modifiers) {
		return nil, false
	}
	return o.Modifiers, true
}

// HasModifiers returns a boolean if a field has been set.
func (o *EventTaxonomyQueryResponse) HasModifiers() bool {
	if o != nil && !IsNil(o.Modifiers) {
		return true
	}

	return false
}

// SetModifiers gets a reference to the given HogQLQueryModifiers and assigns it to the Modifiers field.
func (o *EventTaxonomyQueryResponse) SetModifiers(v HogQLQueryModifiers) {
	o.Modifiers = &v
}

// GetQueryStatus returns the QueryStatus field value if set, zero value otherwise.
func (o *EventTaxonomyQueryResponse) GetQueryStatus() QueryStatus {
	if o == nil || IsNil(o.QueryStatus) {
		var ret QueryStatus
		return ret
	}
	return *o.QueryStatus
}

// GetQueryStatusOk returns a tuple with the QueryStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventTaxonomyQueryResponse) GetQueryStatusOk() (*QueryStatus, bool) {
	if o == nil || IsNil(o.QueryStatus) {
		return nil, false
	}
	return o.QueryStatus, true
}

// HasQueryStatus returns a boolean if a field has been set.
func (o *EventTaxonomyQueryResponse) HasQueryStatus() bool {
	if o != nil && !IsNil(o.QueryStatus) {
		return true
	}

	return false
}

// SetQueryStatus gets a reference to the given QueryStatus and assigns it to the QueryStatus field.
func (o *EventTaxonomyQueryResponse) SetQueryStatus(v QueryStatus) {
	o.QueryStatus = &v
}

// GetResolvedDateRange returns the ResolvedDateRange field value if set, zero value otherwise.
func (o *EventTaxonomyQueryResponse) GetResolvedDateRange() ResolvedDateRangeResponse {
	if o == nil || IsNil(o.ResolvedDateRange) {
		var ret ResolvedDateRangeResponse
		return ret
	}
	return *o.ResolvedDateRange
}

// GetResolvedDateRangeOk returns a tuple with the ResolvedDateRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventTaxonomyQueryResponse) GetResolvedDateRangeOk() (*ResolvedDateRangeResponse, bool) {
	if o == nil || IsNil(o.ResolvedDateRange) {
		return nil, false
	}
	return o.ResolvedDateRange, true
}

// HasResolvedDateRange returns a boolean if a field has been set.
func (o *EventTaxonomyQueryResponse) HasResolvedDateRange() bool {
	if o != nil && !IsNil(o.ResolvedDateRange) {
		return true
	}

	return false
}

// SetResolvedDateRange gets a reference to the given ResolvedDateRangeResponse and assigns it to the ResolvedDateRange field.
func (o *EventTaxonomyQueryResponse) SetResolvedDateRange(v ResolvedDateRangeResponse) {
	o.ResolvedDateRange = &v
}

// GetResults returns the Results field value
func (o *EventTaxonomyQueryResponse) GetResults() []EventTaxonomyItem {
	if o == nil {
		var ret []EventTaxonomyItem
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *EventTaxonomyQueryResponse) GetResultsOk() ([]EventTaxonomyItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *EventTaxonomyQueryResponse) SetResults(v []EventTaxonomyItem) {
	o.Results = v
}

// GetTimings returns the Timings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EventTaxonomyQueryResponse) GetTimings() []QueryTiming {
	if o == nil {
		var ret []QueryTiming
		return ret
	}
	return o.Timings
}

// GetTimingsOk returns a tuple with the Timings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventTaxonomyQueryResponse) GetTimingsOk() ([]QueryTiming, bool) {
	if o == nil || IsNil(o.Timings) {
		return nil, false
	}
	return o.Timings, true
}

// HasTimings returns a boolean if a field has been set.
func (o *EventTaxonomyQueryResponse) HasTimings() bool {
	if o != nil && !IsNil(o.Timings) {
		return true
	}

	return false
}

// SetTimings gets a reference to the given []QueryTiming and assigns it to the Timings field.
func (o *EventTaxonomyQueryResponse) SetTimings(v []QueryTiming) {
	o.Timings = v
}

func (o EventTaxonomyQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventTaxonomyQueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.Hogql.IsSet() {
		toSerialize["hogql"] = o.Hogql.Get()
	}
	if !IsNil(o.Modifiers) {
		toSerialize["modifiers"] = o.Modifiers
	}
	if !IsNil(o.QueryStatus) {
		toSerialize["query_status"] = o.QueryStatus
	}
	if !IsNil(o.ResolvedDateRange) {
		toSerialize["resolved_date_range"] = o.ResolvedDateRange
	}
	toSerialize["results"] = o.Results
	if o.Timings != nil {
		toSerialize["timings"] = o.Timings
	}
	return toSerialize, nil
}

func (o *EventTaxonomyQueryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventTaxonomyQueryResponse := _EventTaxonomyQueryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventTaxonomyQueryResponse)

	if err != nil {
		return err
	}

	*o = EventTaxonomyQueryResponse(varEventTaxonomyQueryResponse)

	return err
}

type NullableEventTaxonomyQueryResponse struct {
	value *EventTaxonomyQueryResponse
	isSet bool
}

func (v NullableEventTaxonomyQueryResponse) Get() *EventTaxonomyQueryResponse {
	return v.value
}

func (v *NullableEventTaxonomyQueryResponse) Set(val *EventTaxonomyQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEventTaxonomyQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEventTaxonomyQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventTaxonomyQueryResponse(val *EventTaxonomyQueryResponse) *NullableEventTaxonomyQueryResponse {
	return &NullableEventTaxonomyQueryResponse{value: val, isSet: true}
}

func (v NullableEventTaxonomyQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventTaxonomyQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


