/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
)

// checks if the QueryResponseAlternative5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryResponseAlternative5{}

// QueryResponseAlternative5 struct for QueryResponseAlternative5
type QueryResponseAlternative5 struct {
	Breakdown []BreakdownItem `json:"breakdown,omitempty"`
	Breakdowns []MultipleBreakdownOptions `json:"breakdowns,omitempty"`
	Compare []CompareItem `json:"compare,omitempty"`
	Day []DayItem `json:"day,omitempty"`
	Interval []IntervalItem `json:"interval,omitempty"`
	Series []Series `json:"series,omitempty"`
	Status []StatusItem `json:"status,omitempty"`
}

// NewQueryResponseAlternative5 instantiates a new QueryResponseAlternative5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryResponseAlternative5() *QueryResponseAlternative5 {
	this := QueryResponseAlternative5{}
	return &this
}

// NewQueryResponseAlternative5WithDefaults instantiates a new QueryResponseAlternative5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryResponseAlternative5WithDefaults() *QueryResponseAlternative5 {
	this := QueryResponseAlternative5{}
	return &this
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryResponseAlternative5) GetBreakdown() []BreakdownItem {
	if o == nil {
		var ret []BreakdownItem
		return ret
	}
	return o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryResponseAlternative5) GetBreakdownOk() ([]BreakdownItem, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *QueryResponseAlternative5) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given []BreakdownItem and assigns it to the Breakdown field.
func (o *QueryResponseAlternative5) SetBreakdown(v []BreakdownItem) {
	o.Breakdown = v
}

// GetBreakdowns returns the Breakdowns field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryResponseAlternative5) GetBreakdowns() []MultipleBreakdownOptions {
	if o == nil {
		var ret []MultipleBreakdownOptions
		return ret
	}
	return o.Breakdowns
}

// GetBreakdownsOk returns a tuple with the Breakdowns field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryResponseAlternative5) GetBreakdownsOk() ([]MultipleBreakdownOptions, bool) {
	if o == nil || IsNil(o.Breakdowns) {
		return nil, false
	}
	return o.Breakdowns, true
}

// HasBreakdowns returns a boolean if a field has been set.
func (o *QueryResponseAlternative5) HasBreakdowns() bool {
	if o != nil && !IsNil(o.Breakdowns) {
		return true
	}

	return false
}

// SetBreakdowns gets a reference to the given []MultipleBreakdownOptions and assigns it to the Breakdowns field.
func (o *QueryResponseAlternative5) SetBreakdowns(v []MultipleBreakdownOptions) {
	o.Breakdowns = v
}

// GetCompare returns the Compare field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryResponseAlternative5) GetCompare() []CompareItem {
	if o == nil {
		var ret []CompareItem
		return ret
	}
	return o.Compare
}

// GetCompareOk returns a tuple with the Compare field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryResponseAlternative5) GetCompareOk() ([]CompareItem, bool) {
	if o == nil || IsNil(o.Compare) {
		return nil, false
	}
	return o.Compare, true
}

// HasCompare returns a boolean if a field has been set.
func (o *QueryResponseAlternative5) HasCompare() bool {
	if o != nil && !IsNil(o.Compare) {
		return true
	}

	return false
}

// SetCompare gets a reference to the given []CompareItem and assigns it to the Compare field.
func (o *QueryResponseAlternative5) SetCompare(v []CompareItem) {
	o.Compare = v
}

// GetDay returns the Day field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryResponseAlternative5) GetDay() []DayItem {
	if o == nil {
		var ret []DayItem
		return ret
	}
	return o.Day
}

// GetDayOk returns a tuple with the Day field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryResponseAlternative5) GetDayOk() ([]DayItem, bool) {
	if o == nil || IsNil(o.Day) {
		return nil, false
	}
	return o.Day, true
}

// HasDay returns a boolean if a field has been set.
func (o *QueryResponseAlternative5) HasDay() bool {
	if o != nil && !IsNil(o.Day) {
		return true
	}

	return false
}

// SetDay gets a reference to the given []DayItem and assigns it to the Day field.
func (o *QueryResponseAlternative5) SetDay(v []DayItem) {
	o.Day = v
}

// GetInterval returns the Interval field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryResponseAlternative5) GetInterval() []IntervalItem {
	if o == nil {
		var ret []IntervalItem
		return ret
	}
	return o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryResponseAlternative5) GetIntervalOk() ([]IntervalItem, bool) {
	if o == nil || IsNil(o.Interval) {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *QueryResponseAlternative5) HasInterval() bool {
	if o != nil && !IsNil(o.Interval) {
		return true
	}

	return false
}

// SetInterval gets a reference to the given []IntervalItem and assigns it to the Interval field.
func (o *QueryResponseAlternative5) SetInterval(v []IntervalItem) {
	o.Interval = v
}

// GetSeries returns the Series field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryResponseAlternative5) GetSeries() []Series {
	if o == nil {
		var ret []Series
		return ret
	}
	return o.Series
}

// GetSeriesOk returns a tuple with the Series field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryResponseAlternative5) GetSeriesOk() ([]Series, bool) {
	if o == nil || IsNil(o.Series) {
		return nil, false
	}
	return o.Series, true
}

// HasSeries returns a boolean if a field has been set.
func (o *QueryResponseAlternative5) HasSeries() bool {
	if o != nil && !IsNil(o.Series) {
		return true
	}

	return false
}

// SetSeries gets a reference to the given []Series and assigns it to the Series field.
func (o *QueryResponseAlternative5) SetSeries(v []Series) {
	o.Series = v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryResponseAlternative5) GetStatus() []StatusItem {
	if o == nil {
		var ret []StatusItem
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryResponseAlternative5) GetStatusOk() ([]StatusItem, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *QueryResponseAlternative5) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given []StatusItem and assigns it to the Status field.
func (o *QueryResponseAlternative5) SetStatus(v []StatusItem) {
	o.Status = v
}

func (o QueryResponseAlternative5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryResponseAlternative5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Breakdown != nil {
		toSerialize["breakdown"] = o.Breakdown
	}
	if o.Breakdowns != nil {
		toSerialize["breakdowns"] = o.Breakdowns
	}
	if o.Compare != nil {
		toSerialize["compare"] = o.Compare
	}
	if o.Day != nil {
		toSerialize["day"] = o.Day
	}
	if o.Interval != nil {
		toSerialize["interval"] = o.Interval
	}
	if o.Series != nil {
		toSerialize["series"] = o.Series
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableQueryResponseAlternative5 struct {
	value *QueryResponseAlternative5
	isSet bool
}

func (v NullableQueryResponseAlternative5) Get() *QueryResponseAlternative5 {
	return v.value
}

func (v *NullableQueryResponseAlternative5) Set(val *QueryResponseAlternative5) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryResponseAlternative5) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryResponseAlternative5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryResponseAlternative5(val *QueryResponseAlternative5) *NullableQueryResponseAlternative5 {
	return &NullableQueryResponseAlternative5{value: val, isSet: true}
}

func (v NullableQueryResponseAlternative5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryResponseAlternative5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


