/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MatchedRecording type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MatchedRecording{}

// MatchedRecording struct for MatchedRecording
type MatchedRecording struct {
	Events []MatchedRecordingEvent `json:"events"`
	SessionId NullableString `json:"session_id,omitempty"`
}

type _MatchedRecording MatchedRecording

// NewMatchedRecording instantiates a new MatchedRecording object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchedRecording(events []MatchedRecordingEvent) *MatchedRecording {
	this := MatchedRecording{}
	this.Events = events
	return &this
}

// NewMatchedRecordingWithDefaults instantiates a new MatchedRecording object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchedRecordingWithDefaults() *MatchedRecording {
	this := MatchedRecording{}
	return &this
}

// GetEvents returns the Events field value
func (o *MatchedRecording) GetEvents() []MatchedRecordingEvent {
	if o == nil {
		var ret []MatchedRecordingEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *MatchedRecording) GetEventsOk() ([]MatchedRecordingEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *MatchedRecording) SetEvents(v []MatchedRecordingEvent) {
	o.Events = v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MatchedRecording) GetSessionId() string {
	if o == nil || IsNil(o.SessionId.Get()) {
		var ret string
		return ret
	}
	return *o.SessionId.Get()
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MatchedRecording) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SessionId.Get(), o.SessionId.IsSet()
}

// HasSessionId returns a boolean if a field has been set.
func (o *MatchedRecording) HasSessionId() bool {
	if o != nil && o.SessionId.IsSet() {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given NullableString and assigns it to the SessionId field.
func (o *MatchedRecording) SetSessionId(v string) {
	o.SessionId.Set(&v)
}
// SetSessionIdNil sets the value for SessionId to be an explicit nil
func (o *MatchedRecording) SetSessionIdNil() {
	o.SessionId.Set(nil)
}

// UnsetSessionId ensures that no value is present for SessionId, not even an explicit nil
func (o *MatchedRecording) UnsetSessionId() {
	o.SessionId.Unset()
}

func (o MatchedRecording) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MatchedRecording) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	if o.SessionId.IsSet() {
		toSerialize["session_id"] = o.SessionId.Get()
	}
	return toSerialize, nil
}

func (o *MatchedRecording) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMatchedRecording := _MatchedRecording{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMatchedRecording)

	if err != nil {
		return err
	}

	*o = MatchedRecording(varMatchedRecording)

	return err
}

type NullableMatchedRecording struct {
	value *MatchedRecording
	isSet bool
}

func (v NullableMatchedRecording) Get() *MatchedRecording {
	return v.value
}

func (v *NullableMatchedRecording) Set(val *MatchedRecording) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchedRecording) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchedRecording) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchedRecording(val *MatchedRecording) *NullableMatchedRecording {
	return &NullableMatchedRecording{value: val, isSet: true}
}

func (v NullableMatchedRecording) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchedRecording) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


