/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LLMTrace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMTrace{}

// LLMTrace struct for LLMTrace
type LLMTrace struct {
	AiSessionId NullableString `json:"aiSessionId,omitempty"`
	CreatedAt string `json:"createdAt"`
	ErrorCount NullableFloat32 `json:"errorCount,omitempty"`
	Events []LLMTraceEvent `json:"events"`
	Id string `json:"id"`
	InputCost NullableFloat32 `json:"inputCost,omitempty"`
	InputState interface{} `json:"inputState,omitempty"`
	InputTokens NullableFloat32 `json:"inputTokens,omitempty"`
	OutputCost NullableFloat32 `json:"outputCost,omitempty"`
	OutputState interface{} `json:"outputState,omitempty"`
	OutputTokens NullableFloat32 `json:"outputTokens,omitempty"`
	Person LLMTracePerson `json:"person"`
	TotalCost NullableFloat32 `json:"totalCost,omitempty"`
	TotalLatency NullableFloat32 `json:"totalLatency,omitempty"`
	TraceName NullableString `json:"traceName,omitempty"`
}

type _LLMTrace LLMTrace

// NewLLMTrace instantiates a new LLMTrace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMTrace(createdAt string, events []LLMTraceEvent, id string, person LLMTracePerson) *LLMTrace {
	this := LLMTrace{}
	this.CreatedAt = createdAt
	this.Events = events
	this.Id = id
	this.Person = person
	return &this
}

// NewLLMTraceWithDefaults instantiates a new LLMTrace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMTraceWithDefaults() *LLMTrace {
	this := LLMTrace{}
	return &this
}

// GetAiSessionId returns the AiSessionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetAiSessionId() string {
	if o == nil || IsNil(o.AiSessionId.Get()) {
		var ret string
		return ret
	}
	return *o.AiSessionId.Get()
}

// GetAiSessionIdOk returns a tuple with the AiSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetAiSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AiSessionId.Get(), o.AiSessionId.IsSet()
}

// HasAiSessionId returns a boolean if a field has been set.
func (o *LLMTrace) HasAiSessionId() bool {
	if o != nil && o.AiSessionId.IsSet() {
		return true
	}

	return false
}

// SetAiSessionId gets a reference to the given NullableString and assigns it to the AiSessionId field.
func (o *LLMTrace) SetAiSessionId(v string) {
	o.AiSessionId.Set(&v)
}
// SetAiSessionIdNil sets the value for AiSessionId to be an explicit nil
func (o *LLMTrace) SetAiSessionIdNil() {
	o.AiSessionId.Set(nil)
}

// UnsetAiSessionId ensures that no value is present for AiSessionId, not even an explicit nil
func (o *LLMTrace) UnsetAiSessionId() {
	o.AiSessionId.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *LLMTrace) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *LLMTrace) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *LLMTrace) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetErrorCount returns the ErrorCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetErrorCount() float32 {
	if o == nil || IsNil(o.ErrorCount.Get()) {
		var ret float32
		return ret
	}
	return *o.ErrorCount.Get()
}

// GetErrorCountOk returns a tuple with the ErrorCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetErrorCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCount.Get(), o.ErrorCount.IsSet()
}

// HasErrorCount returns a boolean if a field has been set.
func (o *LLMTrace) HasErrorCount() bool {
	if o != nil && o.ErrorCount.IsSet() {
		return true
	}

	return false
}

// SetErrorCount gets a reference to the given NullableFloat32 and assigns it to the ErrorCount field.
func (o *LLMTrace) SetErrorCount(v float32) {
	o.ErrorCount.Set(&v)
}
// SetErrorCountNil sets the value for ErrorCount to be an explicit nil
func (o *LLMTrace) SetErrorCountNil() {
	o.ErrorCount.Set(nil)
}

// UnsetErrorCount ensures that no value is present for ErrorCount, not even an explicit nil
func (o *LLMTrace) UnsetErrorCount() {
	o.ErrorCount.Unset()
}

// GetEvents returns the Events field value
func (o *LLMTrace) GetEvents() []LLMTraceEvent {
	if o == nil {
		var ret []LLMTraceEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *LLMTrace) GetEventsOk() ([]LLMTraceEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *LLMTrace) SetEvents(v []LLMTraceEvent) {
	o.Events = v
}

// GetId returns the Id field value
func (o *LLMTrace) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LLMTrace) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LLMTrace) SetId(v string) {
	o.Id = v
}

// GetInputCost returns the InputCost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetInputCost() float32 {
	if o == nil || IsNil(o.InputCost.Get()) {
		var ret float32
		return ret
	}
	return *o.InputCost.Get()
}

// GetInputCostOk returns a tuple with the InputCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetInputCostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputCost.Get(), o.InputCost.IsSet()
}

// HasInputCost returns a boolean if a field has been set.
func (o *LLMTrace) HasInputCost() bool {
	if o != nil && o.InputCost.IsSet() {
		return true
	}

	return false
}

// SetInputCost gets a reference to the given NullableFloat32 and assigns it to the InputCost field.
func (o *LLMTrace) SetInputCost(v float32) {
	o.InputCost.Set(&v)
}
// SetInputCostNil sets the value for InputCost to be an explicit nil
func (o *LLMTrace) SetInputCostNil() {
	o.InputCost.Set(nil)
}

// UnsetInputCost ensures that no value is present for InputCost, not even an explicit nil
func (o *LLMTrace) UnsetInputCost() {
	o.InputCost.Unset()
}

// GetInputState returns the InputState field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetInputState() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InputState
}

// GetInputStateOk returns a tuple with the InputState field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetInputStateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InputState) {
		return nil, false
	}
	return &o.InputState, true
}

// HasInputState returns a boolean if a field has been set.
func (o *LLMTrace) HasInputState() bool {
	if o != nil && !IsNil(o.InputState) {
		return true
	}

	return false
}

// SetInputState gets a reference to the given interface{} and assigns it to the InputState field.
func (o *LLMTrace) SetInputState(v interface{}) {
	o.InputState = v
}

// GetInputTokens returns the InputTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetInputTokens() float32 {
	if o == nil || IsNil(o.InputTokens.Get()) {
		var ret float32
		return ret
	}
	return *o.InputTokens.Get()
}

// GetInputTokensOk returns a tuple with the InputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetInputTokensOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputTokens.Get(), o.InputTokens.IsSet()
}

// HasInputTokens returns a boolean if a field has been set.
func (o *LLMTrace) HasInputTokens() bool {
	if o != nil && o.InputTokens.IsSet() {
		return true
	}

	return false
}

// SetInputTokens gets a reference to the given NullableFloat32 and assigns it to the InputTokens field.
func (o *LLMTrace) SetInputTokens(v float32) {
	o.InputTokens.Set(&v)
}
// SetInputTokensNil sets the value for InputTokens to be an explicit nil
func (o *LLMTrace) SetInputTokensNil() {
	o.InputTokens.Set(nil)
}

// UnsetInputTokens ensures that no value is present for InputTokens, not even an explicit nil
func (o *LLMTrace) UnsetInputTokens() {
	o.InputTokens.Unset()
}

// GetOutputCost returns the OutputCost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetOutputCost() float32 {
	if o == nil || IsNil(o.OutputCost.Get()) {
		var ret float32
		return ret
	}
	return *o.OutputCost.Get()
}

// GetOutputCostOk returns a tuple with the OutputCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetOutputCostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputCost.Get(), o.OutputCost.IsSet()
}

// HasOutputCost returns a boolean if a field has been set.
func (o *LLMTrace) HasOutputCost() bool {
	if o != nil && o.OutputCost.IsSet() {
		return true
	}

	return false
}

// SetOutputCost gets a reference to the given NullableFloat32 and assigns it to the OutputCost field.
func (o *LLMTrace) SetOutputCost(v float32) {
	o.OutputCost.Set(&v)
}
// SetOutputCostNil sets the value for OutputCost to be an explicit nil
func (o *LLMTrace) SetOutputCostNil() {
	o.OutputCost.Set(nil)
}

// UnsetOutputCost ensures that no value is present for OutputCost, not even an explicit nil
func (o *LLMTrace) UnsetOutputCost() {
	o.OutputCost.Unset()
}

// GetOutputState returns the OutputState field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetOutputState() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.OutputState
}

// GetOutputStateOk returns a tuple with the OutputState field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetOutputStateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.OutputState) {
		return nil, false
	}
	return &o.OutputState, true
}

// HasOutputState returns a boolean if a field has been set.
func (o *LLMTrace) HasOutputState() bool {
	if o != nil && !IsNil(o.OutputState) {
		return true
	}

	return false
}

// SetOutputState gets a reference to the given interface{} and assigns it to the OutputState field.
func (o *LLMTrace) SetOutputState(v interface{}) {
	o.OutputState = v
}

// GetOutputTokens returns the OutputTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetOutputTokens() float32 {
	if o == nil || IsNil(o.OutputTokens.Get()) {
		var ret float32
		return ret
	}
	return *o.OutputTokens.Get()
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetOutputTokensOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputTokens.Get(), o.OutputTokens.IsSet()
}

// HasOutputTokens returns a boolean if a field has been set.
func (o *LLMTrace) HasOutputTokens() bool {
	if o != nil && o.OutputTokens.IsSet() {
		return true
	}

	return false
}

// SetOutputTokens gets a reference to the given NullableFloat32 and assigns it to the OutputTokens field.
func (o *LLMTrace) SetOutputTokens(v float32) {
	o.OutputTokens.Set(&v)
}
// SetOutputTokensNil sets the value for OutputTokens to be an explicit nil
func (o *LLMTrace) SetOutputTokensNil() {
	o.OutputTokens.Set(nil)
}

// UnsetOutputTokens ensures that no value is present for OutputTokens, not even an explicit nil
func (o *LLMTrace) UnsetOutputTokens() {
	o.OutputTokens.Unset()
}

// GetPerson returns the Person field value
func (o *LLMTrace) GetPerson() LLMTracePerson {
	if o == nil {
		var ret LLMTracePerson
		return ret
	}

	return o.Person
}

// GetPersonOk returns a tuple with the Person field value
// and a boolean to check if the value has been set.
func (o *LLMTrace) GetPersonOk() (*LLMTracePerson, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Person, true
}

// SetPerson sets field value
func (o *LLMTrace) SetPerson(v LLMTracePerson) {
	o.Person = v
}

// GetTotalCost returns the TotalCost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetTotalCost() float32 {
	if o == nil || IsNil(o.TotalCost.Get()) {
		var ret float32
		return ret
	}
	return *o.TotalCost.Get()
}

// GetTotalCostOk returns a tuple with the TotalCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetTotalCostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalCost.Get(), o.TotalCost.IsSet()
}

// HasTotalCost returns a boolean if a field has been set.
func (o *LLMTrace) HasTotalCost() bool {
	if o != nil && o.TotalCost.IsSet() {
		return true
	}

	return false
}

// SetTotalCost gets a reference to the given NullableFloat32 and assigns it to the TotalCost field.
func (o *LLMTrace) SetTotalCost(v float32) {
	o.TotalCost.Set(&v)
}
// SetTotalCostNil sets the value for TotalCost to be an explicit nil
func (o *LLMTrace) SetTotalCostNil() {
	o.TotalCost.Set(nil)
}

// UnsetTotalCost ensures that no value is present for TotalCost, not even an explicit nil
func (o *LLMTrace) UnsetTotalCost() {
	o.TotalCost.Unset()
}

// GetTotalLatency returns the TotalLatency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetTotalLatency() float32 {
	if o == nil || IsNil(o.TotalLatency.Get()) {
		var ret float32
		return ret
	}
	return *o.TotalLatency.Get()
}

// GetTotalLatencyOk returns a tuple with the TotalLatency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetTotalLatencyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalLatency.Get(), o.TotalLatency.IsSet()
}

// HasTotalLatency returns a boolean if a field has been set.
func (o *LLMTrace) HasTotalLatency() bool {
	if o != nil && o.TotalLatency.IsSet() {
		return true
	}

	return false
}

// SetTotalLatency gets a reference to the given NullableFloat32 and assigns it to the TotalLatency field.
func (o *LLMTrace) SetTotalLatency(v float32) {
	o.TotalLatency.Set(&v)
}
// SetTotalLatencyNil sets the value for TotalLatency to be an explicit nil
func (o *LLMTrace) SetTotalLatencyNil() {
	o.TotalLatency.Set(nil)
}

// UnsetTotalLatency ensures that no value is present for TotalLatency, not even an explicit nil
func (o *LLMTrace) UnsetTotalLatency() {
	o.TotalLatency.Unset()
}

// GetTraceName returns the TraceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMTrace) GetTraceName() string {
	if o == nil || IsNil(o.TraceName.Get()) {
		var ret string
		return ret
	}
	return *o.TraceName.Get()
}

// GetTraceNameOk returns a tuple with the TraceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMTrace) GetTraceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TraceName.Get(), o.TraceName.IsSet()
}

// HasTraceName returns a boolean if a field has been set.
func (o *LLMTrace) HasTraceName() bool {
	if o != nil && o.TraceName.IsSet() {
		return true
	}

	return false
}

// SetTraceName gets a reference to the given NullableString and assigns it to the TraceName field.
func (o *LLMTrace) SetTraceName(v string) {
	o.TraceName.Set(&v)
}
// SetTraceNameNil sets the value for TraceName to be an explicit nil
func (o *LLMTrace) SetTraceNameNil() {
	o.TraceName.Set(nil)
}

// UnsetTraceName ensures that no value is present for TraceName, not even an explicit nil
func (o *LLMTrace) UnsetTraceName() {
	o.TraceName.Unset()
}

func (o LLMTrace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMTrace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AiSessionId.IsSet() {
		toSerialize["aiSessionId"] = o.AiSessionId.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt
	if o.ErrorCount.IsSet() {
		toSerialize["errorCount"] = o.ErrorCount.Get()
	}
	toSerialize["events"] = o.Events
	toSerialize["id"] = o.Id
	if o.InputCost.IsSet() {
		toSerialize["inputCost"] = o.InputCost.Get()
	}
	if o.InputState != nil {
		toSerialize["inputState"] = o.InputState
	}
	if o.InputTokens.IsSet() {
		toSerialize["inputTokens"] = o.InputTokens.Get()
	}
	if o.OutputCost.IsSet() {
		toSerialize["outputCost"] = o.OutputCost.Get()
	}
	if o.OutputState != nil {
		toSerialize["outputState"] = o.OutputState
	}
	if o.OutputTokens.IsSet() {
		toSerialize["outputTokens"] = o.OutputTokens.Get()
	}
	toSerialize["person"] = o.Person
	if o.TotalCost.IsSet() {
		toSerialize["totalCost"] = o.TotalCost.Get()
	}
	if o.TotalLatency.IsSet() {
		toSerialize["totalLatency"] = o.TotalLatency.Get()
	}
	if o.TraceName.IsSet() {
		toSerialize["traceName"] = o.TraceName.Get()
	}
	return toSerialize, nil
}

func (o *LLMTrace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"events",
		"id",
		"person",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMTrace := _LLMTrace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMTrace)

	if err != nil {
		return err
	}

	*o = LLMTrace(varLLMTrace)

	return err
}

type NullableLLMTrace struct {
	value *LLMTrace
	isSet bool
}

func (v NullableLLMTrace) Get() *LLMTrace {
	return v.value
}

func (v *NullableLLMTrace) Set(val *LLMTrace) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMTrace) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMTrace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMTrace(val *LLMTrace) *NullableLLMTrace {
	return &NullableLLMTrace{value: val, isSet: true}
}

func (v NullableLLMTrace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMTrace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


