/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
)

// checks if the CreateRecordingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRecordingRequest{}

// CreateRecordingRequest Request body for creating a new recording
type CreateRecordingRequest struct {
	// Meeting platform being recorded  * `zoom` - zoom * `teams` - teams * `meet` - meet * `desktop_audio` - desktop_audio * `slack` - slack
	Platform *CreateRecordingRequestPlatformEnum `json:"platform,omitempty"`
}

// NewCreateRecordingRequest instantiates a new CreateRecordingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRecordingRequest() *CreateRecordingRequest {
	this := CreateRecordingRequest{}
	var platform CreateRecordingRequestPlatformEnum = DESKTOP_AUDIO
	this.Platform = &platform
	return &this
}

// NewCreateRecordingRequestWithDefaults instantiates a new CreateRecordingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRecordingRequestWithDefaults() *CreateRecordingRequest {
	this := CreateRecordingRequest{}
	var platform CreateRecordingRequestPlatformEnum = DESKTOP_AUDIO
	this.Platform = &platform
	return &this
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *CreateRecordingRequest) GetPlatform() CreateRecordingRequestPlatformEnum {
	if o == nil || IsNil(o.Platform) {
		var ret CreateRecordingRequestPlatformEnum
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordingRequest) GetPlatformOk() (*CreateRecordingRequestPlatformEnum, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *CreateRecordingRequest) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given CreateRecordingRequestPlatformEnum and assigns it to the Platform field.
func (o *CreateRecordingRequest) SetPlatform(v CreateRecordingRequestPlatformEnum) {
	o.Platform = &v
}

func (o CreateRecordingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRecordingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	return toSerialize, nil
}

type NullableCreateRecordingRequest struct {
	value *CreateRecordingRequest
	isSet bool
}

func (v NullableCreateRecordingRequest) Get() *CreateRecordingRequest {
	return v.value
}

func (v *NullableCreateRecordingRequest) Set(val *CreateRecordingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRecordingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRecordingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRecordingRequest(val *CreateRecordingRequest) *NullableCreateRecordingRequest {
	return &NullableCreateRecordingRequest{value: val, isSet: true}
}

func (v NullableCreateRecordingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRecordingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


