/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomChannelCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomChannelCondition{}

// CustomChannelCondition struct for CustomChannelCondition
type CustomChannelCondition struct {
	Id string `json:"id"`
	Key CustomChannelField `json:"key"`
	Op CustomChannelOperator `json:"op"`
	Value NullableValue1 `json:"value,omitempty"`
}

type _CustomChannelCondition CustomChannelCondition

// NewCustomChannelCondition instantiates a new CustomChannelCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomChannelCondition(id string, key CustomChannelField, op CustomChannelOperator) *CustomChannelCondition {
	this := CustomChannelCondition{}
	this.Id = id
	this.Key = key
	this.Op = op
	var value Value1 = null
	this.Value = *NewNullableValue1(&value)
	return &this
}

// NewCustomChannelConditionWithDefaults instantiates a new CustomChannelCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomChannelConditionWithDefaults() *CustomChannelCondition {
	this := CustomChannelCondition{}
	var value Value1 = null
	this.Value = *NewNullableValue1(&value)
	return &this
}

// GetId returns the Id field value
func (o *CustomChannelCondition) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomChannelCondition) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomChannelCondition) SetId(v string) {
	o.Id = v
}

// GetKey returns the Key field value
func (o *CustomChannelCondition) GetKey() CustomChannelField {
	if o == nil {
		var ret CustomChannelField
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CustomChannelCondition) GetKeyOk() (*CustomChannelField, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CustomChannelCondition) SetKey(v CustomChannelField) {
	o.Key = v
}

// GetOp returns the Op field value
func (o *CustomChannelCondition) GetOp() CustomChannelOperator {
	if o == nil {
		var ret CustomChannelOperator
		return ret
	}

	return o.Op
}

// GetOpOk returns a tuple with the Op field value
// and a boolean to check if the value has been set.
func (o *CustomChannelCondition) GetOpOk() (*CustomChannelOperator, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Op, true
}

// SetOp sets field value
func (o *CustomChannelCondition) SetOp(v CustomChannelOperator) {
	o.Op = v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomChannelCondition) GetValue() Value1 {
	if o == nil || IsNil(o.Value.Get()) {
		var ret Value1
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomChannelCondition) GetValueOk() (*Value1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *CustomChannelCondition) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableValue1 and assigns it to the Value field.
func (o *CustomChannelCondition) SetValue(v Value1) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *CustomChannelCondition) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *CustomChannelCondition) UnsetValue() {
	o.Value.Unset()
}

func (o CustomChannelCondition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomChannelCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["key"] = o.Key
	toSerialize["op"] = o.Op
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	return toSerialize, nil
}

func (o *CustomChannelCondition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"key",
		"op",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomChannelCondition := _CustomChannelCondition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomChannelCondition)

	if err != nil {
		return err
	}

	*o = CustomChannelCondition(varCustomChannelCondition)

	return err
}

type NullableCustomChannelCondition struct {
	value *CustomChannelCondition
	isSet bool
}

func (v NullableCustomChannelCondition) Get() *CustomChannelCondition {
	return v.value
}

func (v *NullableCustomChannelCondition) Set(val *CustomChannelCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomChannelCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomChannelCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomChannelCondition(val *CustomChannelCondition) *NullableCustomChannelCondition {
	return &NullableCustomChannelCondition{value: val, isSet: true}
}

func (v NullableCustomChannelCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomChannelCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


