/*
PostHog API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package posthogapi

import (
	"encoding/json"
	"fmt"
)

// AttributionModeEnum * `first_touch` - First Touch * `last_touch` - Last Touch
type AttributionModeEnum string

// List of AttributionModeEnum
const (
	FIRST_TOUCH AttributionModeEnum = "first_touch"
	LAST_TOUCH AttributionModeEnum = "last_touch"
)

// All allowed values of AttributionModeEnum enum
var AllowedAttributionModeEnumEnumValues = []AttributionModeEnum{
	"first_touch",
	"last_touch",
}

func (v *AttributionModeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AttributionModeEnum(value)
	for _, existing := range AllowedAttributionModeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AttributionModeEnum", value)
}

// NewAttributionModeEnumFromValue returns a pointer to a valid AttributionModeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAttributionModeEnumFromValue(v string) (*AttributionModeEnum, error) {
	ev := AttributionModeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AttributionModeEnum: valid values are %v", v, AllowedAttributionModeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AttributionModeEnum) IsValid() bool {
	for _, existing := range AllowedAttributionModeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AttributionModeEnum value
func (v AttributionModeEnum) Ptr() *AttributionModeEnum {
	return &v
}

type NullableAttributionModeEnum struct {
	value *AttributionModeEnum
	isSet bool
}

func (v NullableAttributionModeEnum) Get() *AttributionModeEnum {
	return v.value
}

func (v *NullableAttributionModeEnum) Set(val *AttributionModeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributionModeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributionModeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributionModeEnum(val *AttributionModeEnum) *NullableAttributionModeEnum {
	return &NullableAttributionModeEnum{value: val, isSet: true}
}

func (v NullableAttributionModeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributionModeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

