/*
PostHog API

Testing AdvancedActivityLogsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package posthogapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/posthog/terraform-provider"
)

func Test_posthogapi_AdvancedActivityLogsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AdvancedActivityLogsAPIService AdvancedActivityLogsAvailableFiltersRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.AdvancedActivityLogsAPI.AdvancedActivityLogsAvailableFiltersRetrieve(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdvancedActivityLogsAPIService AdvancedActivityLogsExportCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.AdvancedActivityLogsAPI.AdvancedActivityLogsExportCreate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdvancedActivityLogsAPIService AdvancedActivityLogsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.AdvancedActivityLogsAPI.AdvancedActivityLogsList(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
