/*
PostHog API

Testing LLMGatewayAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package posthogapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/posthog/terraform-provider"
)

func Test_posthogapi_LLMGatewayAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LLMGatewayAPIService LlmGatewayV1ChatCompletionsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.LLMGatewayAPI.LlmGatewayV1ChatCompletionsCreate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LLMGatewayAPIService LlmGatewayV1MessagesCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.LLMGatewayAPI.LlmGatewayV1MessagesCreate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
