/*
PostHog API

Testing EnvironmentsRollbackAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package posthogapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/posthog/terraform-provider"
)

func Test_posthogapi_EnvironmentsRollbackAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EnvironmentsRollbackAPIService EnvironmentsRollbackCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.EnvironmentsRollbackAPI.EnvironmentsRollbackCreate(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
